/**
 * Csp_Get_List_Indicadores_OutRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.portalmobile.meta4.schemas.types;

public class Csp_Get_List_Indicadores_OutRecord  implements java.io.Serializable {
    private java.lang.String csp_Id_Indicador;

    private java.lang.String csp_Nombre;

    private java.lang.String csp_Semaforo;

    private java.lang.String csp_Tendencia_Aa;

    private java.lang.String csp_Tendencia_Ma;

    private java.lang.String csp_Valor_Aa;

    private java.lang.String csp_Valor_Actual;

    private java.lang.String csp_Valor_Ma;

    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    public Csp_Get_List_Indicadores_OutRecord() {
    }

    public Csp_Get_List_Indicadores_OutRecord(
           java.lang.String csp_Id_Indicador,
           java.lang.String csp_Nombre,
           java.lang.String csp_Semaforo,
           java.lang.String csp_Tendencia_Aa,
           java.lang.String csp_Tendencia_Ma,
           java.lang.String csp_Valor_Aa,
           java.lang.String csp_Valor_Actual,
           java.lang.String csp_Valor_Ma,
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete) {
           this.csp_Id_Indicador = csp_Id_Indicador;
           this.csp_Nombre = csp_Nombre;
           this.csp_Semaforo = csp_Semaforo;
           this.csp_Tendencia_Aa = csp_Tendencia_Aa;
           this.csp_Tendencia_Ma = csp_Tendencia_Ma;
           this.csp_Valor_Aa = csp_Valor_Aa;
           this.csp_Valor_Actual = csp_Valor_Actual;
           this.csp_Valor_Ma = csp_Valor_Ma;
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the csp_Id_Indicador value for this Csp_Get_List_Indicadores_OutRecord.
     * 
     * @return csp_Id_Indicador
     */
    public java.lang.String getCsp_Id_Indicador() {
        return csp_Id_Indicador;
    }


    /**
     * Sets the csp_Id_Indicador value for this Csp_Get_List_Indicadores_OutRecord.
     * 
     * @param csp_Id_Indicador
     */
    public void setCsp_Id_Indicador(java.lang.String csp_Id_Indicador) {
        this.csp_Id_Indicador = csp_Id_Indicador;
    }


    /**
     * Gets the csp_Nombre value for this Csp_Get_List_Indicadores_OutRecord.
     * 
     * @return csp_Nombre
     */
    public java.lang.String getCsp_Nombre() {
        return csp_Nombre;
    }


    /**
     * Sets the csp_Nombre value for this Csp_Get_List_Indicadores_OutRecord.
     * 
     * @param csp_Nombre
     */
    public void setCsp_Nombre(java.lang.String csp_Nombre) {
        this.csp_Nombre = csp_Nombre;
    }


    /**
     * Gets the csp_Semaforo value for this Csp_Get_List_Indicadores_OutRecord.
     * 
     * @return csp_Semaforo
     */
    public java.lang.String getCsp_Semaforo() {
        return csp_Semaforo;
    }


    /**
     * Sets the csp_Semaforo value for this Csp_Get_List_Indicadores_OutRecord.
     * 
     * @param csp_Semaforo
     */
    public void setCsp_Semaforo(java.lang.String csp_Semaforo) {
        this.csp_Semaforo = csp_Semaforo;
    }


    /**
     * Gets the csp_Tendencia_Aa value for this Csp_Get_List_Indicadores_OutRecord.
     * 
     * @return csp_Tendencia_Aa
     */
    public java.lang.String getCsp_Tendencia_Aa() {
        return csp_Tendencia_Aa;
    }


    /**
     * Sets the csp_Tendencia_Aa value for this Csp_Get_List_Indicadores_OutRecord.
     * 
     * @param csp_Tendencia_Aa
     */
    public void setCsp_Tendencia_Aa(java.lang.String csp_Tendencia_Aa) {
        this.csp_Tendencia_Aa = csp_Tendencia_Aa;
    }


    /**
     * Gets the csp_Tendencia_Ma value for this Csp_Get_List_Indicadores_OutRecord.
     * 
     * @return csp_Tendencia_Ma
     */
    public java.lang.String getCsp_Tendencia_Ma() {
        return csp_Tendencia_Ma;
    }


    /**
     * Sets the csp_Tendencia_Ma value for this Csp_Get_List_Indicadores_OutRecord.
     * 
     * @param csp_Tendencia_Ma
     */
    public void setCsp_Tendencia_Ma(java.lang.String csp_Tendencia_Ma) {
        this.csp_Tendencia_Ma = csp_Tendencia_Ma;
    }


    /**
     * Gets the csp_Valor_Aa value for this Csp_Get_List_Indicadores_OutRecord.
     * 
     * @return csp_Valor_Aa
     */
    public java.lang.String getCsp_Valor_Aa() {
        return csp_Valor_Aa;
    }


    /**
     * Sets the csp_Valor_Aa value for this Csp_Get_List_Indicadores_OutRecord.
     * 
     * @param csp_Valor_Aa
     */
    public void setCsp_Valor_Aa(java.lang.String csp_Valor_Aa) {
        this.csp_Valor_Aa = csp_Valor_Aa;
    }


    /**
     * Gets the csp_Valor_Actual value for this Csp_Get_List_Indicadores_OutRecord.
     * 
     * @return csp_Valor_Actual
     */
    public java.lang.String getCsp_Valor_Actual() {
        return csp_Valor_Actual;
    }


    /**
     * Sets the csp_Valor_Actual value for this Csp_Get_List_Indicadores_OutRecord.
     * 
     * @param csp_Valor_Actual
     */
    public void setCsp_Valor_Actual(java.lang.String csp_Valor_Actual) {
        this.csp_Valor_Actual = csp_Valor_Actual;
    }


    /**
     * Gets the csp_Valor_Ma value for this Csp_Get_List_Indicadores_OutRecord.
     * 
     * @return csp_Valor_Ma
     */
    public java.lang.String getCsp_Valor_Ma() {
        return csp_Valor_Ma;
    }


    /**
     * Sets the csp_Valor_Ma value for this Csp_Get_List_Indicadores_OutRecord.
     * 
     * @param csp_Valor_Ma
     */
    public void setCsp_Valor_Ma(java.lang.String csp_Valor_Ma) {
        this.csp_Valor_Ma = csp_Valor_Ma;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Csp_Get_List_Indicadores_OutRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Csp_Get_List_Indicadores_OutRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Csp_Get_List_Indicadores_OutRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Csp_Get_List_Indicadores_OutRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Csp_Get_List_Indicadores_OutRecord)) return false;
        Csp_Get_List_Indicadores_OutRecord other = (Csp_Get_List_Indicadores_OutRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.csp_Id_Indicador==null && other.getCsp_Id_Indicador()==null) || 
             (this.csp_Id_Indicador!=null &&
              this.csp_Id_Indicador.equals(other.getCsp_Id_Indicador()))) &&
            ((this.csp_Nombre==null && other.getCsp_Nombre()==null) || 
             (this.csp_Nombre!=null &&
              this.csp_Nombre.equals(other.getCsp_Nombre()))) &&
            ((this.csp_Semaforo==null && other.getCsp_Semaforo()==null) || 
             (this.csp_Semaforo!=null &&
              this.csp_Semaforo.equals(other.getCsp_Semaforo()))) &&
            ((this.csp_Tendencia_Aa==null && other.getCsp_Tendencia_Aa()==null) || 
             (this.csp_Tendencia_Aa!=null &&
              this.csp_Tendencia_Aa.equals(other.getCsp_Tendencia_Aa()))) &&
            ((this.csp_Tendencia_Ma==null && other.getCsp_Tendencia_Ma()==null) || 
             (this.csp_Tendencia_Ma!=null &&
              this.csp_Tendencia_Ma.equals(other.getCsp_Tendencia_Ma()))) &&
            ((this.csp_Valor_Aa==null && other.getCsp_Valor_Aa()==null) || 
             (this.csp_Valor_Aa!=null &&
              this.csp_Valor_Aa.equals(other.getCsp_Valor_Aa()))) &&
            ((this.csp_Valor_Actual==null && other.getCsp_Valor_Actual()==null) || 
             (this.csp_Valor_Actual!=null &&
              this.csp_Valor_Actual.equals(other.getCsp_Valor_Actual()))) &&
            ((this.csp_Valor_Ma==null && other.getCsp_Valor_Ma()==null) || 
             (this.csp_Valor_Ma!=null &&
              this.csp_Valor_Ma.equals(other.getCsp_Valor_Ma()))) &&
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete();
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getCsp_Id_Indicador() != null) {
            _hashCode += getCsp_Id_Indicador().hashCode();
        }
        if (getCsp_Nombre() != null) {
            _hashCode += getCsp_Nombre().hashCode();
        }
        if (getCsp_Semaforo() != null) {
            _hashCode += getCsp_Semaforo().hashCode();
        }
        if (getCsp_Tendencia_Aa() != null) {
            _hashCode += getCsp_Tendencia_Aa().hashCode();
        }
        if (getCsp_Tendencia_Ma() != null) {
            _hashCode += getCsp_Tendencia_Ma().hashCode();
        }
        if (getCsp_Valor_Aa() != null) {
            _hashCode += getCsp_Valor_Aa().hashCode();
        }
        if (getCsp_Valor_Actual() != null) {
            _hashCode += getCsp_Valor_Actual().hashCode();
        }
        if (getCsp_Valor_Ma() != null) {
            _hashCode += getCsp_Valor_Ma().hashCode();
        }
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Csp_Get_List_Indicadores_OutRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Csp_Get_List_Indicadores_OutRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Id_Indicador");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Id_Indicador"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Nombre");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Nombre"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Semaforo");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Semaforo"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Tendencia_Aa");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Tendencia_Aa"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Tendencia_Ma");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Tendencia_Ma"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Valor_Aa");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Valor_Aa"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Valor_Actual");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Valor_Actual"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Valor_Ma");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Valor_Ma"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
