/**
 * Csp_Get_Mobile_NotifRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.portalmobile.meta4.schemas.types;

public class Csp_Get_Mobile_NotifRecord  implements java.io.Serializable {
    private java.lang.String csp_Chk_Del_Mobile;

    private java.lang.String csp_Chk_Recibido;

    private java.lang.String csp_Descripcion;

    private java.util.Calendar csp_Dt_Caducidad;

    private java.util.Calendar csp_Dt_Envio;

    private java.lang.String csp_Mensaje;

    private java.lang.Double csp_Ordinal;

    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    private java.lang.String std_Id_Person;

    public Csp_Get_Mobile_NotifRecord() {
    }

    public Csp_Get_Mobile_NotifRecord(
           java.lang.String csp_Chk_Del_Mobile,
           java.lang.String csp_Chk_Recibido,
           java.lang.String csp_Descripcion,
           java.util.Calendar csp_Dt_Caducidad,
           java.util.Calendar csp_Dt_Envio,
           java.lang.String csp_Mensaje,
           java.lang.Double csp_Ordinal,
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete,
           java.lang.String std_Id_Person) {
           this.csp_Chk_Del_Mobile = csp_Chk_Del_Mobile;
           this.csp_Chk_Recibido = csp_Chk_Recibido;
           this.csp_Descripcion = csp_Descripcion;
           this.csp_Dt_Caducidad = csp_Dt_Caducidad;
           this.csp_Dt_Envio = csp_Dt_Envio;
           this.csp_Mensaje = csp_Mensaje;
           this.csp_Ordinal = csp_Ordinal;
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
           this.std_Id_Person = std_Id_Person;
    }


    /**
     * Gets the csp_Chk_Del_Mobile value for this Csp_Get_Mobile_NotifRecord.
     * 
     * @return csp_Chk_Del_Mobile
     */
    public java.lang.String getCsp_Chk_Del_Mobile() {
        return csp_Chk_Del_Mobile;
    }


    /**
     * Sets the csp_Chk_Del_Mobile value for this Csp_Get_Mobile_NotifRecord.
     * 
     * @param csp_Chk_Del_Mobile
     */
    public void setCsp_Chk_Del_Mobile(java.lang.String csp_Chk_Del_Mobile) {
        this.csp_Chk_Del_Mobile = csp_Chk_Del_Mobile;
    }


    /**
     * Gets the csp_Chk_Recibido value for this Csp_Get_Mobile_NotifRecord.
     * 
     * @return csp_Chk_Recibido
     */
    public java.lang.String getCsp_Chk_Recibido() {
        return csp_Chk_Recibido;
    }


    /**
     * Sets the csp_Chk_Recibido value for this Csp_Get_Mobile_NotifRecord.
     * 
     * @param csp_Chk_Recibido
     */
    public void setCsp_Chk_Recibido(java.lang.String csp_Chk_Recibido) {
        this.csp_Chk_Recibido = csp_Chk_Recibido;
    }


    /**
     * Gets the csp_Descripcion value for this Csp_Get_Mobile_NotifRecord.
     * 
     * @return csp_Descripcion
     */
    public java.lang.String getCsp_Descripcion() {
        return csp_Descripcion;
    }


    /**
     * Sets the csp_Descripcion value for this Csp_Get_Mobile_NotifRecord.
     * 
     * @param csp_Descripcion
     */
    public void setCsp_Descripcion(java.lang.String csp_Descripcion) {
        this.csp_Descripcion = csp_Descripcion;
    }


    /**
     * Gets the csp_Dt_Caducidad value for this Csp_Get_Mobile_NotifRecord.
     * 
     * @return csp_Dt_Caducidad
     */
    public java.util.Calendar getCsp_Dt_Caducidad() {
        return csp_Dt_Caducidad;
    }


    /**
     * Sets the csp_Dt_Caducidad value for this Csp_Get_Mobile_NotifRecord.
     * 
     * @param csp_Dt_Caducidad
     */
    public void setCsp_Dt_Caducidad(java.util.Calendar csp_Dt_Caducidad) {
        this.csp_Dt_Caducidad = csp_Dt_Caducidad;
    }


    /**
     * Gets the csp_Dt_Envio value for this Csp_Get_Mobile_NotifRecord.
     * 
     * @return csp_Dt_Envio
     */
    public java.util.Calendar getCsp_Dt_Envio() {
        return csp_Dt_Envio;
    }


    /**
     * Sets the csp_Dt_Envio value for this Csp_Get_Mobile_NotifRecord.
     * 
     * @param csp_Dt_Envio
     */
    public void setCsp_Dt_Envio(java.util.Calendar csp_Dt_Envio) {
        this.csp_Dt_Envio = csp_Dt_Envio;
    }


    /**
     * Gets the csp_Mensaje value for this Csp_Get_Mobile_NotifRecord.
     * 
     * @return csp_Mensaje
     */
    public java.lang.String getCsp_Mensaje() {
        return csp_Mensaje;
    }


    /**
     * Sets the csp_Mensaje value for this Csp_Get_Mobile_NotifRecord.
     * 
     * @param csp_Mensaje
     */
    public void setCsp_Mensaje(java.lang.String csp_Mensaje) {
        this.csp_Mensaje = csp_Mensaje;
    }


    /**
     * Gets the csp_Ordinal value for this Csp_Get_Mobile_NotifRecord.
     * 
     * @return csp_Ordinal
     */
    public java.lang.Double getCsp_Ordinal() {
        return csp_Ordinal;
    }


    /**
     * Sets the csp_Ordinal value for this Csp_Get_Mobile_NotifRecord.
     * 
     * @param csp_Ordinal
     */
    public void setCsp_Ordinal(java.lang.Double csp_Ordinal) {
        this.csp_Ordinal = csp_Ordinal;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Csp_Get_Mobile_NotifRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Csp_Get_Mobile_NotifRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Csp_Get_Mobile_NotifRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Csp_Get_Mobile_NotifRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the std_Id_Person value for this Csp_Get_Mobile_NotifRecord.
     * 
     * @return std_Id_Person
     */
    public java.lang.String getStd_Id_Person() {
        return std_Id_Person;
    }


    /**
     * Sets the std_Id_Person value for this Csp_Get_Mobile_NotifRecord.
     * 
     * @param std_Id_Person
     */
    public void setStd_Id_Person(java.lang.String std_Id_Person) {
        this.std_Id_Person = std_Id_Person;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Csp_Get_Mobile_NotifRecord)) return false;
        Csp_Get_Mobile_NotifRecord other = (Csp_Get_Mobile_NotifRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.csp_Chk_Del_Mobile==null && other.getCsp_Chk_Del_Mobile()==null) || 
             (this.csp_Chk_Del_Mobile!=null &&
              this.csp_Chk_Del_Mobile.equals(other.getCsp_Chk_Del_Mobile()))) &&
            ((this.csp_Chk_Recibido==null && other.getCsp_Chk_Recibido()==null) || 
             (this.csp_Chk_Recibido!=null &&
              this.csp_Chk_Recibido.equals(other.getCsp_Chk_Recibido()))) &&
            ((this.csp_Descripcion==null && other.getCsp_Descripcion()==null) || 
             (this.csp_Descripcion!=null &&
              this.csp_Descripcion.equals(other.getCsp_Descripcion()))) &&
            ((this.csp_Dt_Caducidad==null && other.getCsp_Dt_Caducidad()==null) || 
             (this.csp_Dt_Caducidad!=null &&
              this.csp_Dt_Caducidad.equals(other.getCsp_Dt_Caducidad()))) &&
            ((this.csp_Dt_Envio==null && other.getCsp_Dt_Envio()==null) || 
             (this.csp_Dt_Envio!=null &&
              this.csp_Dt_Envio.equals(other.getCsp_Dt_Envio()))) &&
            ((this.csp_Mensaje==null && other.getCsp_Mensaje()==null) || 
             (this.csp_Mensaje!=null &&
              this.csp_Mensaje.equals(other.getCsp_Mensaje()))) &&
            ((this.csp_Ordinal==null && other.getCsp_Ordinal()==null) || 
             (this.csp_Ordinal!=null &&
              this.csp_Ordinal.equals(other.getCsp_Ordinal()))) &&
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete() &&
            ((this.std_Id_Person==null && other.getStd_Id_Person()==null) || 
             (this.std_Id_Person!=null &&
              this.std_Id_Person.equals(other.getStd_Id_Person())));
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getCsp_Chk_Del_Mobile() != null) {
            _hashCode += getCsp_Chk_Del_Mobile().hashCode();
        }
        if (getCsp_Chk_Recibido() != null) {
            _hashCode += getCsp_Chk_Recibido().hashCode();
        }
        if (getCsp_Descripcion() != null) {
            _hashCode += getCsp_Descripcion().hashCode();
        }
        if (getCsp_Dt_Caducidad() != null) {
            _hashCode += getCsp_Dt_Caducidad().hashCode();
        }
        if (getCsp_Dt_Envio() != null) {
            _hashCode += getCsp_Dt_Envio().hashCode();
        }
        if (getCsp_Mensaje() != null) {
            _hashCode += getCsp_Mensaje().hashCode();
        }
        if (getCsp_Ordinal() != null) {
            _hashCode += getCsp_Ordinal().hashCode();
        }
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        if (getStd_Id_Person() != null) {
            _hashCode += getStd_Id_Person().hashCode();
        }
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Csp_Get_Mobile_NotifRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Csp_Get_Mobile_NotifRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Chk_Del_Mobile");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Chk_Del_Mobile"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Chk_Recibido");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Chk_Recibido"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Descripcion");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Descripcion"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Dt_Caducidad");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Dt_Caducidad"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "dateTime"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Dt_Envio");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Dt_Envio"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "dateTime"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Mensaje");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Mensaje"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Ordinal");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Ordinal"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Id_Person");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Id_Person"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
