/**
 * Csp_Params_Process_MvlRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.portalmobile.meta4.schemas.types;

public class Csp_Params_Process_MvlRecord  implements java.io.Serializable {
    private java.lang.String csp_Id_Parametro;

    private java.lang.String csp_Id_Proceso;

    private java.lang.String csp_Value;

    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    public Csp_Params_Process_MvlRecord() {
    }

    public Csp_Params_Process_MvlRecord(
           java.lang.String csp_Id_Parametro,
           java.lang.String csp_Id_Proceso,
           java.lang.String csp_Value,
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete) {
           this.csp_Id_Parametro = csp_Id_Parametro;
           this.csp_Id_Proceso = csp_Id_Proceso;
           this.csp_Value = csp_Value;
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the csp_Id_Parametro value for this Csp_Params_Process_MvlRecord.
     * 
     * @return csp_Id_Parametro
     */
    public java.lang.String getCsp_Id_Parametro() {
        return csp_Id_Parametro;
    }


    /**
     * Sets the csp_Id_Parametro value for this Csp_Params_Process_MvlRecord.
     * 
     * @param csp_Id_Parametro
     */
    public void setCsp_Id_Parametro(java.lang.String csp_Id_Parametro) {
        this.csp_Id_Parametro = csp_Id_Parametro;
    }


    /**
     * Gets the csp_Id_Proceso value for this Csp_Params_Process_MvlRecord.
     * 
     * @return csp_Id_Proceso
     */
    public java.lang.String getCsp_Id_Proceso() {
        return csp_Id_Proceso;
    }


    /**
     * Sets the csp_Id_Proceso value for this Csp_Params_Process_MvlRecord.
     * 
     * @param csp_Id_Proceso
     */
    public void setCsp_Id_Proceso(java.lang.String csp_Id_Proceso) {
        this.csp_Id_Proceso = csp_Id_Proceso;
    }


    /**
     * Gets the csp_Value value for this Csp_Params_Process_MvlRecord.
     * 
     * @return csp_Value
     */
    public java.lang.String getCsp_Value() {
        return csp_Value;
    }


    /**
     * Sets the csp_Value value for this Csp_Params_Process_MvlRecord.
     * 
     * @param csp_Value
     */
    public void setCsp_Value(java.lang.String csp_Value) {
        this.csp_Value = csp_Value;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Csp_Params_Process_MvlRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Csp_Params_Process_MvlRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Csp_Params_Process_MvlRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Csp_Params_Process_MvlRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Csp_Params_Process_MvlRecord)) return false;
        Csp_Params_Process_MvlRecord other = (Csp_Params_Process_MvlRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.csp_Id_Parametro==null && other.getCsp_Id_Parametro()==null) || 
             (this.csp_Id_Parametro!=null &&
              this.csp_Id_Parametro.equals(other.getCsp_Id_Parametro()))) &&
            ((this.csp_Id_Proceso==null && other.getCsp_Id_Proceso()==null) || 
             (this.csp_Id_Proceso!=null &&
              this.csp_Id_Proceso.equals(other.getCsp_Id_Proceso()))) &&
            ((this.csp_Value==null && other.getCsp_Value()==null) || 
             (this.csp_Value!=null &&
              this.csp_Value.equals(other.getCsp_Value()))) &&
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete();
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getCsp_Id_Parametro() != null) {
            _hashCode += getCsp_Id_Parametro().hashCode();
        }
        if (getCsp_Id_Proceso() != null) {
            _hashCode += getCsp_Id_Proceso().hashCode();
        }
        if (getCsp_Value() != null) {
            _hashCode += getCsp_Value().hashCode();
        }
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Csp_Params_Process_MvlRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Csp_Params_Process_MvlRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Id_Parametro");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Id_Parametro"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Id_Proceso");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Id_Proceso"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Value");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Value"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
