/**
 * Csp_App_Other_UserRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.portalmobile.meta4.schemas.types;

public class Csp_App_Other_UserRecord  implements java.io.Serializable {
    private java.lang.String id_App_User;

    private java.lang.String is_Lock;

    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    private java.lang.String n_Password;

    public Csp_App_Other_UserRecord() {
    }

    public Csp_App_Other_UserRecord(
           java.lang.String id_App_User,
           java.lang.String is_Lock,
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete,
           java.lang.String n_Password) {
           this.id_App_User = id_App_User;
           this.is_Lock = is_Lock;
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
           this.n_Password = n_Password;
    }


    /**
     * Gets the id_App_User value for this Csp_App_Other_UserRecord.
     * 
     * @return id_App_User
     */
    public java.lang.String getId_App_User() {
        return id_App_User;
    }


    /**
     * Sets the id_App_User value for this Csp_App_Other_UserRecord.
     * 
     * @param id_App_User
     */
    public void setId_App_User(java.lang.String id_App_User) {
        this.id_App_User = id_App_User;
    }


    /**
     * Gets the is_Lock value for this Csp_App_Other_UserRecord.
     * 
     * @return is_Lock
     */
    public java.lang.String getIs_Lock() {
        return is_Lock;
    }


    /**
     * Sets the is_Lock value for this Csp_App_Other_UserRecord.
     * 
     * @param is_Lock
     */
    public void setIs_Lock(java.lang.String is_Lock) {
        this.is_Lock = is_Lock;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Csp_App_Other_UserRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Csp_App_Other_UserRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Csp_App_Other_UserRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Csp_App_Other_UserRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the n_Password value for this Csp_App_Other_UserRecord.
     * 
     * @return n_Password
     */
    public java.lang.String getN_Password() {
        return n_Password;
    }


    /**
     * Sets the n_Password value for this Csp_App_Other_UserRecord.
     * 
     * @param n_Password
     */
    public void setN_Password(java.lang.String n_Password) {
        this.n_Password = n_Password;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Csp_App_Other_UserRecord)) return false;
        Csp_App_Other_UserRecord other = (Csp_App_Other_UserRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.id_App_User==null && other.getId_App_User()==null) || 
             (this.id_App_User!=null &&
              this.id_App_User.equals(other.getId_App_User()))) &&
            ((this.is_Lock==null && other.getIs_Lock()==null) || 
             (this.is_Lock!=null &&
              this.is_Lock.equals(other.getIs_Lock()))) &&
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete() &&
            ((this.n_Password==null && other.getN_Password()==null) || 
             (this.n_Password!=null &&
              this.n_Password.equals(other.getN_Password())));
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getId_App_User() != null) {
            _hashCode += getId_App_User().hashCode();
        }
        if (getIs_Lock() != null) {
            _hashCode += getIs_Lock().hashCode();
        }
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        if (getN_Password() != null) {
            _hashCode += getN_Password().hashCode();
        }
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Csp_App_Other_UserRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Csp_App_Other_UserRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("id_App_User");
        elemField.setXmlName(new javax.xml.namespace.QName("", "id_App_User"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("is_Lock");
        elemField.setXmlName(new javax.xml.namespace.QName("", "is_Lock"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("n_Password");
        elemField.setXmlName(new javax.xml.namespace.QName("", "n_Password"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
