/**
 * Csp_Mvl_Usr_SegRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.portalmobile.meta4.schemas.types;

public class Csp_Mvl_Usr_SegRecord  implements java.io.Serializable {
    private java.lang.String csp_Id_Tp_Disp;

    private java.lang.String csp_Uuid_Movil;

    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    private java.lang.String std_Id_Person;

    public Csp_Mvl_Usr_SegRecord() {
    }

    public Csp_Mvl_Usr_SegRecord(
           java.lang.String csp_Id_Tp_Disp,
           java.lang.String csp_Uuid_Movil,
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete,
           java.lang.String std_Id_Person) {
           this.csp_Id_Tp_Disp = csp_Id_Tp_Disp;
           this.csp_Uuid_Movil = csp_Uuid_Movil;
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
           this.std_Id_Person = std_Id_Person;
    }


    /**
     * Gets the csp_Id_Tp_Disp value for this Csp_Mvl_Usr_SegRecord.
     * 
     * @return csp_Id_Tp_Disp
     */
    public java.lang.String getCsp_Id_Tp_Disp() {
        return csp_Id_Tp_Disp;
    }


    /**
     * Sets the csp_Id_Tp_Disp value for this Csp_Mvl_Usr_SegRecord.
     * 
     * @param csp_Id_Tp_Disp
     */
    public void setCsp_Id_Tp_Disp(java.lang.String csp_Id_Tp_Disp) {
        this.csp_Id_Tp_Disp = csp_Id_Tp_Disp;
    }


    /**
     * Gets the csp_Uuid_Movil value for this Csp_Mvl_Usr_SegRecord.
     * 
     * @return csp_Uuid_Movil
     */
    public java.lang.String getCsp_Uuid_Movil() {
        return csp_Uuid_Movil;
    }


    /**
     * Sets the csp_Uuid_Movil value for this Csp_Mvl_Usr_SegRecord.
     * 
     * @param csp_Uuid_Movil
     */
    public void setCsp_Uuid_Movil(java.lang.String csp_Uuid_Movil) {
        this.csp_Uuid_Movil = csp_Uuid_Movil;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Csp_Mvl_Usr_SegRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Csp_Mvl_Usr_SegRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Csp_Mvl_Usr_SegRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Csp_Mvl_Usr_SegRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the std_Id_Person value for this Csp_Mvl_Usr_SegRecord.
     * 
     * @return std_Id_Person
     */
    public java.lang.String getStd_Id_Person() {
        return std_Id_Person;
    }


    /**
     * Sets the std_Id_Person value for this Csp_Mvl_Usr_SegRecord.
     * 
     * @param std_Id_Person
     */
    public void setStd_Id_Person(java.lang.String std_Id_Person) {
        this.std_Id_Person = std_Id_Person;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Csp_Mvl_Usr_SegRecord)) return false;
        Csp_Mvl_Usr_SegRecord other = (Csp_Mvl_Usr_SegRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.csp_Id_Tp_Disp==null && other.getCsp_Id_Tp_Disp()==null) || 
             (this.csp_Id_Tp_Disp!=null &&
              this.csp_Id_Tp_Disp.equals(other.getCsp_Id_Tp_Disp()))) &&
            ((this.csp_Uuid_Movil==null && other.getCsp_Uuid_Movil()==null) || 
             (this.csp_Uuid_Movil!=null &&
              this.csp_Uuid_Movil.equals(other.getCsp_Uuid_Movil()))) &&
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete() &&
            ((this.std_Id_Person==null && other.getStd_Id_Person()==null) || 
             (this.std_Id_Person!=null &&
              this.std_Id_Person.equals(other.getStd_Id_Person())));
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getCsp_Id_Tp_Disp() != null) {
            _hashCode += getCsp_Id_Tp_Disp().hashCode();
        }
        if (getCsp_Uuid_Movil() != null) {
            _hashCode += getCsp_Uuid_Movil().hashCode();
        }
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        if (getStd_Id_Person() != null) {
            _hashCode += getStd_Id_Person().hashCode();
        }
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Csp_Mvl_Usr_SegRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Csp_Mvl_Usr_SegRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Id_Tp_Disp");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Id_Tp_Disp"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Uuid_Movil");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Uuid_Movil"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Id_Person");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Id_Person"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
