/**
 * Csp_Get_List_Dates_OutRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.portalmobile.meta4.schemas.types;

public class Csp_Get_List_Dates_OutRecord  implements java.io.Serializable {
    private java.lang.String csp_Anio;

    private java.lang.String csp_Fecha;

    private java.lang.String csp_Mes;

    private java.lang.String csp_Nombre_Fecha;

    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    public Csp_Get_List_Dates_OutRecord() {
    }

    public Csp_Get_List_Dates_OutRecord(
           java.lang.String csp_Anio,
           java.lang.String csp_Fecha,
           java.lang.String csp_Mes,
           java.lang.String csp_Nombre_Fecha,
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete) {
           this.csp_Anio = csp_Anio;
           this.csp_Fecha = csp_Fecha;
           this.csp_Mes = csp_Mes;
           this.csp_Nombre_Fecha = csp_Nombre_Fecha;
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the csp_Anio value for this Csp_Get_List_Dates_OutRecord.
     * 
     * @return csp_Anio
     */
    public java.lang.String getCsp_Anio() {
        return csp_Anio;
    }


    /**
     * Sets the csp_Anio value for this Csp_Get_List_Dates_OutRecord.
     * 
     * @param csp_Anio
     */
    public void setCsp_Anio(java.lang.String csp_Anio) {
        this.csp_Anio = csp_Anio;
    }


    /**
     * Gets the csp_Fecha value for this Csp_Get_List_Dates_OutRecord.
     * 
     * @return csp_Fecha
     */
    public java.lang.String getCsp_Fecha() {
        return csp_Fecha;
    }


    /**
     * Sets the csp_Fecha value for this Csp_Get_List_Dates_OutRecord.
     * 
     * @param csp_Fecha
     */
    public void setCsp_Fecha(java.lang.String csp_Fecha) {
        this.csp_Fecha = csp_Fecha;
    }


    /**
     * Gets the csp_Mes value for this Csp_Get_List_Dates_OutRecord.
     * 
     * @return csp_Mes
     */
    public java.lang.String getCsp_Mes() {
        return csp_Mes;
    }


    /**
     * Sets the csp_Mes value for this Csp_Get_List_Dates_OutRecord.
     * 
     * @param csp_Mes
     */
    public void setCsp_Mes(java.lang.String csp_Mes) {
        this.csp_Mes = csp_Mes;
    }


    /**
     * Gets the csp_Nombre_Fecha value for this Csp_Get_List_Dates_OutRecord.
     * 
     * @return csp_Nombre_Fecha
     */
    public java.lang.String getCsp_Nombre_Fecha() {
        return csp_Nombre_Fecha;
    }


    /**
     * Sets the csp_Nombre_Fecha value for this Csp_Get_List_Dates_OutRecord.
     * 
     * @param csp_Nombre_Fecha
     */
    public void setCsp_Nombre_Fecha(java.lang.String csp_Nombre_Fecha) {
        this.csp_Nombre_Fecha = csp_Nombre_Fecha;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Csp_Get_List_Dates_OutRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Csp_Get_List_Dates_OutRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Csp_Get_List_Dates_OutRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Csp_Get_List_Dates_OutRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Csp_Get_List_Dates_OutRecord)) return false;
        Csp_Get_List_Dates_OutRecord other = (Csp_Get_List_Dates_OutRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.csp_Anio==null && other.getCsp_Anio()==null) || 
             (this.csp_Anio!=null &&
              this.csp_Anio.equals(other.getCsp_Anio()))) &&
            ((this.csp_Fecha==null && other.getCsp_Fecha()==null) || 
             (this.csp_Fecha!=null &&
              this.csp_Fecha.equals(other.getCsp_Fecha()))) &&
            ((this.csp_Mes==null && other.getCsp_Mes()==null) || 
             (this.csp_Mes!=null &&
              this.csp_Mes.equals(other.getCsp_Mes()))) &&
            ((this.csp_Nombre_Fecha==null && other.getCsp_Nombre_Fecha()==null) || 
             (this.csp_Nombre_Fecha!=null &&
              this.csp_Nombre_Fecha.equals(other.getCsp_Nombre_Fecha()))) &&
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete();
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getCsp_Anio() != null) {
            _hashCode += getCsp_Anio().hashCode();
        }
        if (getCsp_Fecha() != null) {
            _hashCode += getCsp_Fecha().hashCode();
        }
        if (getCsp_Mes() != null) {
            _hashCode += getCsp_Mes().hashCode();
        }
        if (getCsp_Nombre_Fecha() != null) {
            _hashCode += getCsp_Nombre_Fecha().hashCode();
        }
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Csp_Get_List_Dates_OutRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Csp_Get_List_Dates_OutRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Anio");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Anio"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Fecha");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Fecha"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Mes");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Mes"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Nombre_Fecha");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Nombre_Fecha"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
