/**
 * Csp_Get_List_Grps_OutRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.portalmobile.meta4.schemas.types;

public class Csp_Get_List_Grps_OutRecord  implements java.io.Serializable {
    private java.lang.String csp_Descripcion;

    private java.lang.String csp_Id_Grupo;

    private java.lang.String csp_Nombre;

    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    public Csp_Get_List_Grps_OutRecord() {
    }

    public Csp_Get_List_Grps_OutRecord(
           java.lang.String csp_Descripcion,
           java.lang.String csp_Id_Grupo,
           java.lang.String csp_Nombre,
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete) {
           this.csp_Descripcion = csp_Descripcion;
           this.csp_Id_Grupo = csp_Id_Grupo;
           this.csp_Nombre = csp_Nombre;
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the csp_Descripcion value for this Csp_Get_List_Grps_OutRecord.
     * 
     * @return csp_Descripcion
     */
    public java.lang.String getCsp_Descripcion() {
        return csp_Descripcion;
    }


    /**
     * Sets the csp_Descripcion value for this Csp_Get_List_Grps_OutRecord.
     * 
     * @param csp_Descripcion
     */
    public void setCsp_Descripcion(java.lang.String csp_Descripcion) {
        this.csp_Descripcion = csp_Descripcion;
    }


    /**
     * Gets the csp_Id_Grupo value for this Csp_Get_List_Grps_OutRecord.
     * 
     * @return csp_Id_Grupo
     */
    public java.lang.String getCsp_Id_Grupo() {
        return csp_Id_Grupo;
    }


    /**
     * Sets the csp_Id_Grupo value for this Csp_Get_List_Grps_OutRecord.
     * 
     * @param csp_Id_Grupo
     */
    public void setCsp_Id_Grupo(java.lang.String csp_Id_Grupo) {
        this.csp_Id_Grupo = csp_Id_Grupo;
    }


    /**
     * Gets the csp_Nombre value for this Csp_Get_List_Grps_OutRecord.
     * 
     * @return csp_Nombre
     */
    public java.lang.String getCsp_Nombre() {
        return csp_Nombre;
    }


    /**
     * Sets the csp_Nombre value for this Csp_Get_List_Grps_OutRecord.
     * 
     * @param csp_Nombre
     */
    public void setCsp_Nombre(java.lang.String csp_Nombre) {
        this.csp_Nombre = csp_Nombre;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Csp_Get_List_Grps_OutRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Csp_Get_List_Grps_OutRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Csp_Get_List_Grps_OutRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Csp_Get_List_Grps_OutRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Csp_Get_List_Grps_OutRecord)) return false;
        Csp_Get_List_Grps_OutRecord other = (Csp_Get_List_Grps_OutRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.csp_Descripcion==null && other.getCsp_Descripcion()==null) || 
             (this.csp_Descripcion!=null &&
              this.csp_Descripcion.equals(other.getCsp_Descripcion()))) &&
            ((this.csp_Id_Grupo==null && other.getCsp_Id_Grupo()==null) || 
             (this.csp_Id_Grupo!=null &&
              this.csp_Id_Grupo.equals(other.getCsp_Id_Grupo()))) &&
            ((this.csp_Nombre==null && other.getCsp_Nombre()==null) || 
             (this.csp_Nombre!=null &&
              this.csp_Nombre.equals(other.getCsp_Nombre()))) &&
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete();
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getCsp_Descripcion() != null) {
            _hashCode += getCsp_Descripcion().hashCode();
        }
        if (getCsp_Id_Grupo() != null) {
            _hashCode += getCsp_Id_Grupo().hashCode();
        }
        if (getCsp_Nombre() != null) {
            _hashCode += getCsp_Nombre().hashCode();
        }
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Csp_Get_List_Grps_OutRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Csp_Get_List_Grps_OutRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Descripcion");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Descripcion"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Id_Grupo");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Id_Grupo"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Nombre");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Nombre"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
