/**
 * Ess_Control_ManagerRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.portalmobile.meta4.schemas.types;

public class Ess_Control_ManagerRecord  implements java.io.Serializable {
    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    private java.lang.String std_Id_Work_Unit;

    private java.lang.String std_N_Work_Unit;

    public Ess_Control_ManagerRecord() {
    }

    public Ess_Control_ManagerRecord(
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete,
           java.lang.String std_Id_Work_Unit,
           java.lang.String std_N_Work_Unit) {
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
           this.std_Id_Work_Unit = std_Id_Work_Unit;
           this.std_N_Work_Unit = std_N_Work_Unit;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Ess_Control_ManagerRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Ess_Control_ManagerRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Ess_Control_ManagerRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Ess_Control_ManagerRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the std_Id_Work_Unit value for this Ess_Control_ManagerRecord.
     * 
     * @return std_Id_Work_Unit
     */
    public java.lang.String getStd_Id_Work_Unit() {
        return std_Id_Work_Unit;
    }


    /**
     * Sets the std_Id_Work_Unit value for this Ess_Control_ManagerRecord.
     * 
     * @param std_Id_Work_Unit
     */
    public void setStd_Id_Work_Unit(java.lang.String std_Id_Work_Unit) {
        this.std_Id_Work_Unit = std_Id_Work_Unit;
    }


    /**
     * Gets the std_N_Work_Unit value for this Ess_Control_ManagerRecord.
     * 
     * @return std_N_Work_Unit
     */
    public java.lang.String getStd_N_Work_Unit() {
        return std_N_Work_Unit;
    }


    /**
     * Sets the std_N_Work_Unit value for this Ess_Control_ManagerRecord.
     * 
     * @param std_N_Work_Unit
     */
    public void setStd_N_Work_Unit(java.lang.String std_N_Work_Unit) {
        this.std_N_Work_Unit = std_N_Work_Unit;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Ess_Control_ManagerRecord)) return false;
        Ess_Control_ManagerRecord other = (Ess_Control_ManagerRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete() &&
            ((this.std_Id_Work_Unit==null && other.getStd_Id_Work_Unit()==null) || 
             (this.std_Id_Work_Unit!=null &&
              this.std_Id_Work_Unit.equals(other.getStd_Id_Work_Unit()))) &&
            ((this.std_N_Work_Unit==null && other.getStd_N_Work_Unit()==null) || 
             (this.std_N_Work_Unit!=null &&
              this.std_N_Work_Unit.equals(other.getStd_N_Work_Unit())));
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        if (getStd_Id_Work_Unit() != null) {
            _hashCode += getStd_Id_Work_Unit().hashCode();
        }
        if (getStd_N_Work_Unit() != null) {
            _hashCode += getStd_N_Work_Unit().hashCode();
        }
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Ess_Control_ManagerRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Ess_Control_ManagerRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Id_Work_Unit");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Id_Work_Unit"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_N_Work_Unit");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_N_Work_Unit"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
