/**
 * Ess_Get_Absentismos_Rh_SolictRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.portalmobile.meta4.schemas.types;

public class Ess_Get_Absentismos_Rh_SolictRecord  implements java.io.Serializable {
    private java.lang.String csp_Comment;

    private java.lang.Double csp_Estado;

    private java.lang.Double csp_Ordinal;

    private java.lang.String id_Organization;

    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    private java.lang.String responsable;

    private java.util.Calendar sco_Dt_End;

    private java.util.Calendar sco_Dt_Start;

    private java.lang.String sco_Id_Incidence;

    private java.lang.String sco_Nm_Incidence;

    private java.lang.Double sco_Units;

    private java.lang.String std_Id_Person;

    public Ess_Get_Absentismos_Rh_SolictRecord() {
    }

    public Ess_Get_Absentismos_Rh_SolictRecord(
           java.lang.String csp_Comment,
           java.lang.Double csp_Estado,
           java.lang.Double csp_Ordinal,
           java.lang.String id_Organization,
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete,
           java.lang.String responsable,
           java.util.Calendar sco_Dt_End,
           java.util.Calendar sco_Dt_Start,
           java.lang.String sco_Id_Incidence,
           java.lang.String sco_Nm_Incidence,
           java.lang.Double sco_Units,
           java.lang.String std_Id_Person) {
           this.csp_Comment = csp_Comment;
           this.csp_Estado = csp_Estado;
           this.csp_Ordinal = csp_Ordinal;
           this.id_Organization = id_Organization;
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
           this.responsable = responsable;
           this.sco_Dt_End = sco_Dt_End;
           this.sco_Dt_Start = sco_Dt_Start;
           this.sco_Id_Incidence = sco_Id_Incidence;
           this.sco_Nm_Incidence = sco_Nm_Incidence;
           this.sco_Units = sco_Units;
           this.std_Id_Person = std_Id_Person;
    }


    /**
     * Gets the csp_Comment value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @return csp_Comment
     */
    public java.lang.String getCsp_Comment() {
        return csp_Comment;
    }


    /**
     * Sets the csp_Comment value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @param csp_Comment
     */
    public void setCsp_Comment(java.lang.String csp_Comment) {
        this.csp_Comment = csp_Comment;
    }


    /**
     * Gets the csp_Estado value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @return csp_Estado
     */
    public java.lang.Double getCsp_Estado() {
        return csp_Estado;
    }


    /**
     * Sets the csp_Estado value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @param csp_Estado
     */
    public void setCsp_Estado(java.lang.Double csp_Estado) {
        this.csp_Estado = csp_Estado;
    }


    /**
     * Gets the csp_Ordinal value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @return csp_Ordinal
     */
    public java.lang.Double getCsp_Ordinal() {
        return csp_Ordinal;
    }


    /**
     * Sets the csp_Ordinal value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @param csp_Ordinal
     */
    public void setCsp_Ordinal(java.lang.Double csp_Ordinal) {
        this.csp_Ordinal = csp_Ordinal;
    }


    /**
     * Gets the id_Organization value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @return id_Organization
     */
    public java.lang.String getId_Organization() {
        return id_Organization;
    }


    /**
     * Sets the id_Organization value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @param id_Organization
     */
    public void setId_Organization(java.lang.String id_Organization) {
        this.id_Organization = id_Organization;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the responsable value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @return responsable
     */
    public java.lang.String getResponsable() {
        return responsable;
    }


    /**
     * Sets the responsable value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @param responsable
     */
    public void setResponsable(java.lang.String responsable) {
        this.responsable = responsable;
    }


    /**
     * Gets the sco_Dt_End value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @return sco_Dt_End
     */
    public java.util.Calendar getSco_Dt_End() {
        return sco_Dt_End;
    }


    /**
     * Sets the sco_Dt_End value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @param sco_Dt_End
     */
    public void setSco_Dt_End(java.util.Calendar sco_Dt_End) {
        this.sco_Dt_End = sco_Dt_End;
    }


    /**
     * Gets the sco_Dt_Start value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @return sco_Dt_Start
     */
    public java.util.Calendar getSco_Dt_Start() {
        return sco_Dt_Start;
    }


    /**
     * Sets the sco_Dt_Start value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @param sco_Dt_Start
     */
    public void setSco_Dt_Start(java.util.Calendar sco_Dt_Start) {
        this.sco_Dt_Start = sco_Dt_Start;
    }


    /**
     * Gets the sco_Id_Incidence value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @return sco_Id_Incidence
     */
    public java.lang.String getSco_Id_Incidence() {
        return sco_Id_Incidence;
    }


    /**
     * Sets the sco_Id_Incidence value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @param sco_Id_Incidence
     */
    public void setSco_Id_Incidence(java.lang.String sco_Id_Incidence) {
        this.sco_Id_Incidence = sco_Id_Incidence;
    }


    /**
     * Gets the sco_Nm_Incidence value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @return sco_Nm_Incidence
     */
    public java.lang.String getSco_Nm_Incidence() {
        return sco_Nm_Incidence;
    }


    /**
     * Sets the sco_Nm_Incidence value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @param sco_Nm_Incidence
     */
    public void setSco_Nm_Incidence(java.lang.String sco_Nm_Incidence) {
        this.sco_Nm_Incidence = sco_Nm_Incidence;
    }


    /**
     * Gets the sco_Units value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @return sco_Units
     */
    public java.lang.Double getSco_Units() {
        return sco_Units;
    }


    /**
     * Sets the sco_Units value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @param sco_Units
     */
    public void setSco_Units(java.lang.Double sco_Units) {
        this.sco_Units = sco_Units;
    }


    /**
     * Gets the std_Id_Person value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @return std_Id_Person
     */
    public java.lang.String getStd_Id_Person() {
        return std_Id_Person;
    }


    /**
     * Sets the std_Id_Person value for this Ess_Get_Absentismos_Rh_SolictRecord.
     * 
     * @param std_Id_Person
     */
    public void setStd_Id_Person(java.lang.String std_Id_Person) {
        this.std_Id_Person = std_Id_Person;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Ess_Get_Absentismos_Rh_SolictRecord)) return false;
        Ess_Get_Absentismos_Rh_SolictRecord other = (Ess_Get_Absentismos_Rh_SolictRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.csp_Comment==null && other.getCsp_Comment()==null) || 
             (this.csp_Comment!=null &&
              this.csp_Comment.equals(other.getCsp_Comment()))) &&
            ((this.csp_Estado==null && other.getCsp_Estado()==null) || 
             (this.csp_Estado!=null &&
              this.csp_Estado.equals(other.getCsp_Estado()))) &&
            ((this.csp_Ordinal==null && other.getCsp_Ordinal()==null) || 
             (this.csp_Ordinal!=null &&
              this.csp_Ordinal.equals(other.getCsp_Ordinal()))) &&
            ((this.id_Organization==null && other.getId_Organization()==null) || 
             (this.id_Organization!=null &&
              this.id_Organization.equals(other.getId_Organization()))) &&
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete() &&
            ((this.responsable==null && other.getResponsable()==null) || 
             (this.responsable!=null &&
              this.responsable.equals(other.getResponsable()))) &&
            ((this.sco_Dt_End==null && other.getSco_Dt_End()==null) || 
             (this.sco_Dt_End!=null &&
              this.sco_Dt_End.equals(other.getSco_Dt_End()))) &&
            ((this.sco_Dt_Start==null && other.getSco_Dt_Start()==null) || 
             (this.sco_Dt_Start!=null &&
              this.sco_Dt_Start.equals(other.getSco_Dt_Start()))) &&
            ((this.sco_Id_Incidence==null && other.getSco_Id_Incidence()==null) || 
             (this.sco_Id_Incidence!=null &&
              this.sco_Id_Incidence.equals(other.getSco_Id_Incidence()))) &&
            ((this.sco_Nm_Incidence==null && other.getSco_Nm_Incidence()==null) || 
             (this.sco_Nm_Incidence!=null &&
              this.sco_Nm_Incidence.equals(other.getSco_Nm_Incidence()))) &&
            ((this.sco_Units==null && other.getSco_Units()==null) || 
             (this.sco_Units!=null &&
              this.sco_Units.equals(other.getSco_Units()))) &&
            ((this.std_Id_Person==null && other.getStd_Id_Person()==null) || 
             (this.std_Id_Person!=null &&
              this.std_Id_Person.equals(other.getStd_Id_Person())));
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getCsp_Comment() != null) {
            _hashCode += getCsp_Comment().hashCode();
        }
        if (getCsp_Estado() != null) {
            _hashCode += getCsp_Estado().hashCode();
        }
        if (getCsp_Ordinal() != null) {
            _hashCode += getCsp_Ordinal().hashCode();
        }
        if (getId_Organization() != null) {
            _hashCode += getId_Organization().hashCode();
        }
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        if (getResponsable() != null) {
            _hashCode += getResponsable().hashCode();
        }
        if (getSco_Dt_End() != null) {
            _hashCode += getSco_Dt_End().hashCode();
        }
        if (getSco_Dt_Start() != null) {
            _hashCode += getSco_Dt_Start().hashCode();
        }
        if (getSco_Id_Incidence() != null) {
            _hashCode += getSco_Id_Incidence().hashCode();
        }
        if (getSco_Nm_Incidence() != null) {
            _hashCode += getSco_Nm_Incidence().hashCode();
        }
        if (getSco_Units() != null) {
            _hashCode += getSco_Units().hashCode();
        }
        if (getStd_Id_Person() != null) {
            _hashCode += getStd_Id_Person().hashCode();
        }
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Ess_Get_Absentismos_Rh_SolictRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Ess_Get_Absentismos_Rh_SolictRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Comment");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Comment"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Estado");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Estado"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Ordinal");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Ordinal"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("id_Organization");
        elemField.setXmlName(new javax.xml.namespace.QName("", "id_Organization"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("responsable");
        elemField.setXmlName(new javax.xml.namespace.QName("", "responsable"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Dt_End");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Dt_End"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "dateTime"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Dt_Start");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Dt_Start"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "dateTime"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Id_Incidence");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Id_Incidence"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Nm_Incidence");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Nm_Incidence"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Units");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Units"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Id_Person");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Id_Person"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
