/**
 * Ess_Get_Absentismos_Rh_ResultRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.portalmobile.meta4.schemas.types;

public class Ess_Get_Absentismos_Rh_ResultRecord  implements java.io.Serializable {
    private java.lang.Double estado;

    private java.lang.String fecha_Fin;

    private java.lang.String fecha_Inicio;

    private java.lang.String id_Absentismo;

    private java.lang.String id_Empleado;

    private java.lang.String id_Organization;

    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    private java.lang.String nm_Absentismo;

    private java.lang.String nm_Empleado;

    private java.lang.String nm_Estado;

    private java.lang.Double ordinal_Solic;

    private java.lang.Double total_Dias;

    public Ess_Get_Absentismos_Rh_ResultRecord() {
    }

    public Ess_Get_Absentismos_Rh_ResultRecord(
           java.lang.Double estado,
           java.lang.String fecha_Fin,
           java.lang.String fecha_Inicio,
           java.lang.String id_Absentismo,
           java.lang.String id_Empleado,
           java.lang.String id_Organization,
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete,
           java.lang.String nm_Absentismo,
           java.lang.String nm_Empleado,
           java.lang.String nm_Estado,
           java.lang.Double ordinal_Solic,
           java.lang.Double total_Dias) {
           this.estado = estado;
           this.fecha_Fin = fecha_Fin;
           this.fecha_Inicio = fecha_Inicio;
           this.id_Absentismo = id_Absentismo;
           this.id_Empleado = id_Empleado;
           this.id_Organization = id_Organization;
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
           this.nm_Absentismo = nm_Absentismo;
           this.nm_Empleado = nm_Empleado;
           this.nm_Estado = nm_Estado;
           this.ordinal_Solic = ordinal_Solic;
           this.total_Dias = total_Dias;
    }


    /**
     * Gets the estado value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @return estado
     */
    public java.lang.Double getEstado() {
        return estado;
    }


    /**
     * Sets the estado value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @param estado
     */
    public void setEstado(java.lang.Double estado) {
        this.estado = estado;
    }


    /**
     * Gets the fecha_Fin value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @return fecha_Fin
     */
    public java.lang.String getFecha_Fin() {
        return fecha_Fin;
    }


    /**
     * Sets the fecha_Fin value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @param fecha_Fin
     */
    public void setFecha_Fin(java.lang.String fecha_Fin) {
        this.fecha_Fin = fecha_Fin;
    }


    /**
     * Gets the fecha_Inicio value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @return fecha_Inicio
     */
    public java.lang.String getFecha_Inicio() {
        return fecha_Inicio;
    }


    /**
     * Sets the fecha_Inicio value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @param fecha_Inicio
     */
    public void setFecha_Inicio(java.lang.String fecha_Inicio) {
        this.fecha_Inicio = fecha_Inicio;
    }


    /**
     * Gets the id_Absentismo value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @return id_Absentismo
     */
    public java.lang.String getId_Absentismo() {
        return id_Absentismo;
    }


    /**
     * Sets the id_Absentismo value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @param id_Absentismo
     */
    public void setId_Absentismo(java.lang.String id_Absentismo) {
        this.id_Absentismo = id_Absentismo;
    }


    /**
     * Gets the id_Empleado value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @return id_Empleado
     */
    public java.lang.String getId_Empleado() {
        return id_Empleado;
    }


    /**
     * Sets the id_Empleado value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @param id_Empleado
     */
    public void setId_Empleado(java.lang.String id_Empleado) {
        this.id_Empleado = id_Empleado;
    }


    /**
     * Gets the id_Organization value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @return id_Organization
     */
    public java.lang.String getId_Organization() {
        return id_Organization;
    }


    /**
     * Sets the id_Organization value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @param id_Organization
     */
    public void setId_Organization(java.lang.String id_Organization) {
        this.id_Organization = id_Organization;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the nm_Absentismo value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @return nm_Absentismo
     */
    public java.lang.String getNm_Absentismo() {
        return nm_Absentismo;
    }


    /**
     * Sets the nm_Absentismo value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @param nm_Absentismo
     */
    public void setNm_Absentismo(java.lang.String nm_Absentismo) {
        this.nm_Absentismo = nm_Absentismo;
    }


    /**
     * Gets the nm_Empleado value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @return nm_Empleado
     */
    public java.lang.String getNm_Empleado() {
        return nm_Empleado;
    }


    /**
     * Sets the nm_Empleado value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @param nm_Empleado
     */
    public void setNm_Empleado(java.lang.String nm_Empleado) {
        this.nm_Empleado = nm_Empleado;
    }


    /**
     * Gets the nm_Estado value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @return nm_Estado
     */
    public java.lang.String getNm_Estado() {
        return nm_Estado;
    }


    /**
     * Sets the nm_Estado value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @param nm_Estado
     */
    public void setNm_Estado(java.lang.String nm_Estado) {
        this.nm_Estado = nm_Estado;
    }


    /**
     * Gets the ordinal_Solic value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @return ordinal_Solic
     */
    public java.lang.Double getOrdinal_Solic() {
        return ordinal_Solic;
    }


    /**
     * Sets the ordinal_Solic value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @param ordinal_Solic
     */
    public void setOrdinal_Solic(java.lang.Double ordinal_Solic) {
        this.ordinal_Solic = ordinal_Solic;
    }


    /**
     * Gets the total_Dias value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @return total_Dias
     */
    public java.lang.Double getTotal_Dias() {
        return total_Dias;
    }


    /**
     * Sets the total_Dias value for this Ess_Get_Absentismos_Rh_ResultRecord.
     * 
     * @param total_Dias
     */
    public void setTotal_Dias(java.lang.Double total_Dias) {
        this.total_Dias = total_Dias;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Ess_Get_Absentismos_Rh_ResultRecord)) return false;
        Ess_Get_Absentismos_Rh_ResultRecord other = (Ess_Get_Absentismos_Rh_ResultRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.estado==null && other.getEstado()==null) || 
             (this.estado!=null &&
              this.estado.equals(other.getEstado()))) &&
            ((this.fecha_Fin==null && other.getFecha_Fin()==null) || 
             (this.fecha_Fin!=null &&
              this.fecha_Fin.equals(other.getFecha_Fin()))) &&
            ((this.fecha_Inicio==null && other.getFecha_Inicio()==null) || 
             (this.fecha_Inicio!=null &&
              this.fecha_Inicio.equals(other.getFecha_Inicio()))) &&
            ((this.id_Absentismo==null && other.getId_Absentismo()==null) || 
             (this.id_Absentismo!=null &&
              this.id_Absentismo.equals(other.getId_Absentismo()))) &&
            ((this.id_Empleado==null && other.getId_Empleado()==null) || 
             (this.id_Empleado!=null &&
              this.id_Empleado.equals(other.getId_Empleado()))) &&
            ((this.id_Organization==null && other.getId_Organization()==null) || 
             (this.id_Organization!=null &&
              this.id_Organization.equals(other.getId_Organization()))) &&
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete() &&
            ((this.nm_Absentismo==null && other.getNm_Absentismo()==null) || 
             (this.nm_Absentismo!=null &&
              this.nm_Absentismo.equals(other.getNm_Absentismo()))) &&
            ((this.nm_Empleado==null && other.getNm_Empleado()==null) || 
             (this.nm_Empleado!=null &&
              this.nm_Empleado.equals(other.getNm_Empleado()))) &&
            ((this.nm_Estado==null && other.getNm_Estado()==null) || 
             (this.nm_Estado!=null &&
              this.nm_Estado.equals(other.getNm_Estado()))) &&
            ((this.ordinal_Solic==null && other.getOrdinal_Solic()==null) || 
             (this.ordinal_Solic!=null &&
              this.ordinal_Solic.equals(other.getOrdinal_Solic()))) &&
            ((this.total_Dias==null && other.getTotal_Dias()==null) || 
             (this.total_Dias!=null &&
              this.total_Dias.equals(other.getTotal_Dias())));
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getEstado() != null) {
            _hashCode += getEstado().hashCode();
        }
        if (getFecha_Fin() != null) {
            _hashCode += getFecha_Fin().hashCode();
        }
        if (getFecha_Inicio() != null) {
            _hashCode += getFecha_Inicio().hashCode();
        }
        if (getId_Absentismo() != null) {
            _hashCode += getId_Absentismo().hashCode();
        }
        if (getId_Empleado() != null) {
            _hashCode += getId_Empleado().hashCode();
        }
        if (getId_Organization() != null) {
            _hashCode += getId_Organization().hashCode();
        }
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        if (getNm_Absentismo() != null) {
            _hashCode += getNm_Absentismo().hashCode();
        }
        if (getNm_Empleado() != null) {
            _hashCode += getNm_Empleado().hashCode();
        }
        if (getNm_Estado() != null) {
            _hashCode += getNm_Estado().hashCode();
        }
        if (getOrdinal_Solic() != null) {
            _hashCode += getOrdinal_Solic().hashCode();
        }
        if (getTotal_Dias() != null) {
            _hashCode += getTotal_Dias().hashCode();
        }
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Ess_Get_Absentismos_Rh_ResultRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Ess_Get_Absentismos_Rh_ResultRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("estado");
        elemField.setXmlName(new javax.xml.namespace.QName("", "estado"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("fecha_Fin");
        elemField.setXmlName(new javax.xml.namespace.QName("", "fecha_Fin"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("fecha_Inicio");
        elemField.setXmlName(new javax.xml.namespace.QName("", "fecha_Inicio"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("id_Absentismo");
        elemField.setXmlName(new javax.xml.namespace.QName("", "id_Absentismo"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("id_Empleado");
        elemField.setXmlName(new javax.xml.namespace.QName("", "id_Empleado"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("id_Organization");
        elemField.setXmlName(new javax.xml.namespace.QName("", "id_Organization"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("nm_Absentismo");
        elemField.setXmlName(new javax.xml.namespace.QName("", "nm_Absentismo"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("nm_Empleado");
        elemField.setXmlName(new javax.xml.namespace.QName("", "nm_Empleado"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("nm_Estado");
        elemField.setXmlName(new javax.xml.namespace.QName("", "nm_Estado"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("ordinal_Solic");
        elemField.setXmlName(new javax.xml.namespace.QName("", "ordinal_Solic"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("total_Dias");
        elemField.setXmlName(new javax.xml.namespace.QName("", "total_Dias"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
