/**
 * Ess_Get_Noticias_Data_PrivateRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.portalmobile.meta4.schemas.types;

public class Ess_Get_Noticias_Data_PrivateRecord  implements java.io.Serializable {
    private java.lang.String csp_Description;

    private javax.activation.DataHandler csp_Doc;

    private java.lang.Double csp_Ordinal;

    private javax.activation.DataHandler csp_Photo;

    private java.lang.String csp_Title;

    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    public Ess_Get_Noticias_Data_PrivateRecord() {
    }

    public Ess_Get_Noticias_Data_PrivateRecord(
           java.lang.String csp_Description,
           javax.activation.DataHandler csp_Doc,
           java.lang.Double csp_Ordinal,
           javax.activation.DataHandler csp_Photo,
           java.lang.String csp_Title,
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete) {
           this.csp_Description = csp_Description;
           this.csp_Doc = csp_Doc;
           this.csp_Ordinal = csp_Ordinal;
           this.csp_Photo = csp_Photo;
           this.csp_Title = csp_Title;
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the csp_Description value for this Ess_Get_Noticias_Data_PrivateRecord.
     * 
     * @return csp_Description
     */
    public java.lang.String getCsp_Description() {
        return csp_Description;
    }


    /**
     * Sets the csp_Description value for this Ess_Get_Noticias_Data_PrivateRecord.
     * 
     * @param csp_Description
     */
    public void setCsp_Description(java.lang.String csp_Description) {
        this.csp_Description = csp_Description;
    }


    /**
     * Gets the csp_Doc value for this Ess_Get_Noticias_Data_PrivateRecord.
     * 
     * @return csp_Doc
     */
    public javax.activation.DataHandler getCsp_Doc() {
        return csp_Doc;
    }


    /**
     * Sets the csp_Doc value for this Ess_Get_Noticias_Data_PrivateRecord.
     * 
     * @param csp_Doc
     */
    public void setCsp_Doc(javax.activation.DataHandler csp_Doc) {
        this.csp_Doc = csp_Doc;
    }


    /**
     * Gets the csp_Ordinal value for this Ess_Get_Noticias_Data_PrivateRecord.
     * 
     * @return csp_Ordinal
     */
    public java.lang.Double getCsp_Ordinal() {
        return csp_Ordinal;
    }


    /**
     * Sets the csp_Ordinal value for this Ess_Get_Noticias_Data_PrivateRecord.
     * 
     * @param csp_Ordinal
     */
    public void setCsp_Ordinal(java.lang.Double csp_Ordinal) {
        this.csp_Ordinal = csp_Ordinal;
    }


    /**
     * Gets the csp_Photo value for this Ess_Get_Noticias_Data_PrivateRecord.
     * 
     * @return csp_Photo
     */
    public javax.activation.DataHandler getCsp_Photo() {
        return csp_Photo;
    }


    /**
     * Sets the csp_Photo value for this Ess_Get_Noticias_Data_PrivateRecord.
     * 
     * @param csp_Photo
     */
    public void setCsp_Photo(javax.activation.DataHandler csp_Photo) {
        this.csp_Photo = csp_Photo;
    }


    /**
     * Gets the csp_Title value for this Ess_Get_Noticias_Data_PrivateRecord.
     * 
     * @return csp_Title
     */
    public java.lang.String getCsp_Title() {
        return csp_Title;
    }


    /**
     * Sets the csp_Title value for this Ess_Get_Noticias_Data_PrivateRecord.
     * 
     * @param csp_Title
     */
    public void setCsp_Title(java.lang.String csp_Title) {
        this.csp_Title = csp_Title;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Ess_Get_Noticias_Data_PrivateRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Ess_Get_Noticias_Data_PrivateRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Ess_Get_Noticias_Data_PrivateRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Ess_Get_Noticias_Data_PrivateRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Ess_Get_Noticias_Data_PrivateRecord)) return false;
        Ess_Get_Noticias_Data_PrivateRecord other = (Ess_Get_Noticias_Data_PrivateRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.csp_Description==null && other.getCsp_Description()==null) || 
             (this.csp_Description!=null &&
              this.csp_Description.equals(other.getCsp_Description()))) &&
            ((this.csp_Doc==null && other.getCsp_Doc()==null) || 
             (this.csp_Doc!=null &&
              this.csp_Doc.equals(other.getCsp_Doc()))) &&
            ((this.csp_Ordinal==null && other.getCsp_Ordinal()==null) || 
             (this.csp_Ordinal!=null &&
              this.csp_Ordinal.equals(other.getCsp_Ordinal()))) &&
            ((this.csp_Photo==null && other.getCsp_Photo()==null) || 
             (this.csp_Photo!=null &&
              this.csp_Photo.equals(other.getCsp_Photo()))) &&
            ((this.csp_Title==null && other.getCsp_Title()==null) || 
             (this.csp_Title!=null &&
              this.csp_Title.equals(other.getCsp_Title()))) &&
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete();
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getCsp_Description() != null) {
            _hashCode += getCsp_Description().hashCode();
        }
        if (getCsp_Doc() != null) {
            _hashCode += getCsp_Doc().hashCode();
        }
        if (getCsp_Ordinal() != null) {
            _hashCode += getCsp_Ordinal().hashCode();
        }
        if (getCsp_Photo() != null) {
            _hashCode += getCsp_Photo().hashCode();
        }
        if (getCsp_Title() != null) {
            _hashCode += getCsp_Title().hashCode();
        }
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Ess_Get_Noticias_Data_PrivateRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Ess_Get_Noticias_Data_PrivateRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Description");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Description"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Doc");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Doc"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://xml.apache.org/xml-soap", "DataHandler"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Ordinal");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Ordinal"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Photo");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Photo"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://xml.apache.org/xml-soap", "DataHandler"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("csp_Title");
        elemField.setXmlName(new javax.xml.namespace.QName("", "csp_Title"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
