/**
 * Mss_Get_Mis_Consultas_ResultRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.portalmobile.meta4.schemas.types;

public class Mss_Get_Mis_Consultas_ResultRecord  implements java.io.Serializable {
    private java.lang.String descripcion_Parametro;

    private java.lang.String id_Meta4Object;

    private java.lang.String item_Parametro;

    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    private java.lang.String nodo_Parametro;

    private java.lang.String nombre;

    private java.lang.String nombre_Parametro;

    private java.lang.String tipo_Dato_Parametro;

    private java.lang.Double tot_Params;

    public Mss_Get_Mis_Consultas_ResultRecord() {
    }

    public Mss_Get_Mis_Consultas_ResultRecord(
           java.lang.String descripcion_Parametro,
           java.lang.String id_Meta4Object,
           java.lang.String item_Parametro,
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete,
           java.lang.String nodo_Parametro,
           java.lang.String nombre,
           java.lang.String nombre_Parametro,
           java.lang.String tipo_Dato_Parametro,
           java.lang.Double tot_Params) {
           this.descripcion_Parametro = descripcion_Parametro;
           this.id_Meta4Object = id_Meta4Object;
           this.item_Parametro = item_Parametro;
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
           this.nodo_Parametro = nodo_Parametro;
           this.nombre = nombre;
           this.nombre_Parametro = nombre_Parametro;
           this.tipo_Dato_Parametro = tipo_Dato_Parametro;
           this.tot_Params = tot_Params;
    }


    /**
     * Gets the descripcion_Parametro value for this Mss_Get_Mis_Consultas_ResultRecord.
     * 
     * @return descripcion_Parametro
     */
    public java.lang.String getDescripcion_Parametro() {
        return descripcion_Parametro;
    }


    /**
     * Sets the descripcion_Parametro value for this Mss_Get_Mis_Consultas_ResultRecord.
     * 
     * @param descripcion_Parametro
     */
    public void setDescripcion_Parametro(java.lang.String descripcion_Parametro) {
        this.descripcion_Parametro = descripcion_Parametro;
    }


    /**
     * Gets the id_Meta4Object value for this Mss_Get_Mis_Consultas_ResultRecord.
     * 
     * @return id_Meta4Object
     */
    public java.lang.String getId_Meta4Object() {
        return id_Meta4Object;
    }


    /**
     * Sets the id_Meta4Object value for this Mss_Get_Mis_Consultas_ResultRecord.
     * 
     * @param id_Meta4Object
     */
    public void setId_Meta4Object(java.lang.String id_Meta4Object) {
        this.id_Meta4Object = id_Meta4Object;
    }


    /**
     * Gets the item_Parametro value for this Mss_Get_Mis_Consultas_ResultRecord.
     * 
     * @return item_Parametro
     */
    public java.lang.String getItem_Parametro() {
        return item_Parametro;
    }


    /**
     * Sets the item_Parametro value for this Mss_Get_Mis_Consultas_ResultRecord.
     * 
     * @param item_Parametro
     */
    public void setItem_Parametro(java.lang.String item_Parametro) {
        this.item_Parametro = item_Parametro;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Mss_Get_Mis_Consultas_ResultRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Mss_Get_Mis_Consultas_ResultRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Mss_Get_Mis_Consultas_ResultRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Mss_Get_Mis_Consultas_ResultRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the nodo_Parametro value for this Mss_Get_Mis_Consultas_ResultRecord.
     * 
     * @return nodo_Parametro
     */
    public java.lang.String getNodo_Parametro() {
        return nodo_Parametro;
    }


    /**
     * Sets the nodo_Parametro value for this Mss_Get_Mis_Consultas_ResultRecord.
     * 
     * @param nodo_Parametro
     */
    public void setNodo_Parametro(java.lang.String nodo_Parametro) {
        this.nodo_Parametro = nodo_Parametro;
    }


    /**
     * Gets the nombre value for this Mss_Get_Mis_Consultas_ResultRecord.
     * 
     * @return nombre
     */
    public java.lang.String getNombre() {
        return nombre;
    }


    /**
     * Sets the nombre value for this Mss_Get_Mis_Consultas_ResultRecord.
     * 
     * @param nombre
     */
    public void setNombre(java.lang.String nombre) {
        this.nombre = nombre;
    }


    /**
     * Gets the nombre_Parametro value for this Mss_Get_Mis_Consultas_ResultRecord.
     * 
     * @return nombre_Parametro
     */
    public java.lang.String getNombre_Parametro() {
        return nombre_Parametro;
    }


    /**
     * Sets the nombre_Parametro value for this Mss_Get_Mis_Consultas_ResultRecord.
     * 
     * @param nombre_Parametro
     */
    public void setNombre_Parametro(java.lang.String nombre_Parametro) {
        this.nombre_Parametro = nombre_Parametro;
    }


    /**
     * Gets the tipo_Dato_Parametro value for this Mss_Get_Mis_Consultas_ResultRecord.
     * 
     * @return tipo_Dato_Parametro
     */
    public java.lang.String getTipo_Dato_Parametro() {
        return tipo_Dato_Parametro;
    }


    /**
     * Sets the tipo_Dato_Parametro value for this Mss_Get_Mis_Consultas_ResultRecord.
     * 
     * @param tipo_Dato_Parametro
     */
    public void setTipo_Dato_Parametro(java.lang.String tipo_Dato_Parametro) {
        this.tipo_Dato_Parametro = tipo_Dato_Parametro;
    }


    /**
     * Gets the tot_Params value for this Mss_Get_Mis_Consultas_ResultRecord.
     * 
     * @return tot_Params
     */
    public java.lang.Double getTot_Params() {
        return tot_Params;
    }


    /**
     * Sets the tot_Params value for this Mss_Get_Mis_Consultas_ResultRecord.
     * 
     * @param tot_Params
     */
    public void setTot_Params(java.lang.Double tot_Params) {
        this.tot_Params = tot_Params;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Mss_Get_Mis_Consultas_ResultRecord)) return false;
        Mss_Get_Mis_Consultas_ResultRecord other = (Mss_Get_Mis_Consultas_ResultRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.descripcion_Parametro==null && other.getDescripcion_Parametro()==null) || 
             (this.descripcion_Parametro!=null &&
              this.descripcion_Parametro.equals(other.getDescripcion_Parametro()))) &&
            ((this.id_Meta4Object==null && other.getId_Meta4Object()==null) || 
             (this.id_Meta4Object!=null &&
              this.id_Meta4Object.equals(other.getId_Meta4Object()))) &&
            ((this.item_Parametro==null && other.getItem_Parametro()==null) || 
             (this.item_Parametro!=null &&
              this.item_Parametro.equals(other.getItem_Parametro()))) &&
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete() &&
            ((this.nodo_Parametro==null && other.getNodo_Parametro()==null) || 
             (this.nodo_Parametro!=null &&
              this.nodo_Parametro.equals(other.getNodo_Parametro()))) &&
            ((this.nombre==null && other.getNombre()==null) || 
             (this.nombre!=null &&
              this.nombre.equals(other.getNombre()))) &&
            ((this.nombre_Parametro==null && other.getNombre_Parametro()==null) || 
             (this.nombre_Parametro!=null &&
              this.nombre_Parametro.equals(other.getNombre_Parametro()))) &&
            ((this.tipo_Dato_Parametro==null && other.getTipo_Dato_Parametro()==null) || 
             (this.tipo_Dato_Parametro!=null &&
              this.tipo_Dato_Parametro.equals(other.getTipo_Dato_Parametro()))) &&
            ((this.tot_Params==null && other.getTot_Params()==null) || 
             (this.tot_Params!=null &&
              this.tot_Params.equals(other.getTot_Params())));
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getDescripcion_Parametro() != null) {
            _hashCode += getDescripcion_Parametro().hashCode();
        }
        if (getId_Meta4Object() != null) {
            _hashCode += getId_Meta4Object().hashCode();
        }
        if (getItem_Parametro() != null) {
            _hashCode += getItem_Parametro().hashCode();
        }
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        if (getNodo_Parametro() != null) {
            _hashCode += getNodo_Parametro().hashCode();
        }
        if (getNombre() != null) {
            _hashCode += getNombre().hashCode();
        }
        if (getNombre_Parametro() != null) {
            _hashCode += getNombre_Parametro().hashCode();
        }
        if (getTipo_Dato_Parametro() != null) {
            _hashCode += getTipo_Dato_Parametro().hashCode();
        }
        if (getTot_Params() != null) {
            _hashCode += getTot_Params().hashCode();
        }
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Mss_Get_Mis_Consultas_ResultRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Mss_Get_Mis_Consultas_ResultRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("descripcion_Parametro");
        elemField.setXmlName(new javax.xml.namespace.QName("", "descripcion_Parametro"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("id_Meta4Object");
        elemField.setXmlName(new javax.xml.namespace.QName("", "id_Meta4Object"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("item_Parametro");
        elemField.setXmlName(new javax.xml.namespace.QName("", "item_Parametro"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("nodo_Parametro");
        elemField.setXmlName(new javax.xml.namespace.QName("", "nodo_Parametro"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("nombre");
        elemField.setXmlName(new javax.xml.namespace.QName("", "nombre"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("nombre_Parametro");
        elemField.setXmlName(new javax.xml.namespace.QName("", "nombre_Parametro"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("tipo_Dato_Parametro");
        elemField.setXmlName(new javax.xml.namespace.QName("", "tipo_Dato_Parametro"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("tot_Params");
        elemField.setXmlName(new javax.xml.namespace.QName("", "tot_Params"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
