/**
 * Sse_Responsable_WunitRecord.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.portalmobile.meta4.schemas.types;

public class Sse_Responsable_WunitRecord  implements java.io.Serializable {
    private java.lang.String m4AutoGeneratedRecordID;

    private boolean m4AutoGeneratedToDelete;

    private java.lang.String sco_Id_Hr;

    private java.lang.Double sco_Or_Hr_Period;

    private java.lang.String std_Id_Work_Unit;

    private java.lang.String std_N_Family_Name_1;

    private java.lang.String std_N_First_Name;

    private java.lang.String std_N_Maiden_Name;

    private java.lang.String std_N_Work_Unit;

    public Sse_Responsable_WunitRecord() {
    }

    public Sse_Responsable_WunitRecord(
           java.lang.String m4AutoGeneratedRecordID,
           boolean m4AutoGeneratedToDelete,
           java.lang.String sco_Id_Hr,
           java.lang.Double sco_Or_Hr_Period,
           java.lang.String std_Id_Work_Unit,
           java.lang.String std_N_Family_Name_1,
           java.lang.String std_N_First_Name,
           java.lang.String std_N_Maiden_Name,
           java.lang.String std_N_Work_Unit) {
           this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
           this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
           this.sco_Id_Hr = sco_Id_Hr;
           this.sco_Or_Hr_Period = sco_Or_Hr_Period;
           this.std_Id_Work_Unit = std_Id_Work_Unit;
           this.std_N_Family_Name_1 = std_N_Family_Name_1;
           this.std_N_First_Name = std_N_First_Name;
           this.std_N_Maiden_Name = std_N_Maiden_Name;
           this.std_N_Work_Unit = std_N_Work_Unit;
    }


    /**
     * Gets the m4AutoGeneratedRecordID value for this Sse_Responsable_WunitRecord.
     * 
     * @return m4AutoGeneratedRecordID
     */
    public java.lang.String getM4AutoGeneratedRecordID() {
        return m4AutoGeneratedRecordID;
    }


    /**
     * Sets the m4AutoGeneratedRecordID value for this Sse_Responsable_WunitRecord.
     * 
     * @param m4AutoGeneratedRecordID
     */
    public void setM4AutoGeneratedRecordID(java.lang.String m4AutoGeneratedRecordID) {
        this.m4AutoGeneratedRecordID = m4AutoGeneratedRecordID;
    }


    /**
     * Gets the m4AutoGeneratedToDelete value for this Sse_Responsable_WunitRecord.
     * 
     * @return m4AutoGeneratedToDelete
     */
    public boolean isM4AutoGeneratedToDelete() {
        return m4AutoGeneratedToDelete;
    }


    /**
     * Sets the m4AutoGeneratedToDelete value for this Sse_Responsable_WunitRecord.
     * 
     * @param m4AutoGeneratedToDelete
     */
    public void setM4AutoGeneratedToDelete(boolean m4AutoGeneratedToDelete) {
        this.m4AutoGeneratedToDelete = m4AutoGeneratedToDelete;
    }


    /**
     * Gets the sco_Id_Hr value for this Sse_Responsable_WunitRecord.
     * 
     * @return sco_Id_Hr
     */
    public java.lang.String getSco_Id_Hr() {
        return sco_Id_Hr;
    }


    /**
     * Sets the sco_Id_Hr value for this Sse_Responsable_WunitRecord.
     * 
     * @param sco_Id_Hr
     */
    public void setSco_Id_Hr(java.lang.String sco_Id_Hr) {
        this.sco_Id_Hr = sco_Id_Hr;
    }


    /**
     * Gets the sco_Or_Hr_Period value for this Sse_Responsable_WunitRecord.
     * 
     * @return sco_Or_Hr_Period
     */
    public java.lang.Double getSco_Or_Hr_Period() {
        return sco_Or_Hr_Period;
    }


    /**
     * Sets the sco_Or_Hr_Period value for this Sse_Responsable_WunitRecord.
     * 
     * @param sco_Or_Hr_Period
     */
    public void setSco_Or_Hr_Period(java.lang.Double sco_Or_Hr_Period) {
        this.sco_Or_Hr_Period = sco_Or_Hr_Period;
    }


    /**
     * Gets the std_Id_Work_Unit value for this Sse_Responsable_WunitRecord.
     * 
     * @return std_Id_Work_Unit
     */
    public java.lang.String getStd_Id_Work_Unit() {
        return std_Id_Work_Unit;
    }


    /**
     * Sets the std_Id_Work_Unit value for this Sse_Responsable_WunitRecord.
     * 
     * @param std_Id_Work_Unit
     */
    public void setStd_Id_Work_Unit(java.lang.String std_Id_Work_Unit) {
        this.std_Id_Work_Unit = std_Id_Work_Unit;
    }


    /**
     * Gets the std_N_Family_Name_1 value for this Sse_Responsable_WunitRecord.
     * 
     * @return std_N_Family_Name_1
     */
    public java.lang.String getStd_N_Family_Name_1() {
        return std_N_Family_Name_1;
    }


    /**
     * Sets the std_N_Family_Name_1 value for this Sse_Responsable_WunitRecord.
     * 
     * @param std_N_Family_Name_1
     */
    public void setStd_N_Family_Name_1(java.lang.String std_N_Family_Name_1) {
        this.std_N_Family_Name_1 = std_N_Family_Name_1;
    }


    /**
     * Gets the std_N_First_Name value for this Sse_Responsable_WunitRecord.
     * 
     * @return std_N_First_Name
     */
    public java.lang.String getStd_N_First_Name() {
        return std_N_First_Name;
    }


    /**
     * Sets the std_N_First_Name value for this Sse_Responsable_WunitRecord.
     * 
     * @param std_N_First_Name
     */
    public void setStd_N_First_Name(java.lang.String std_N_First_Name) {
        this.std_N_First_Name = std_N_First_Name;
    }


    /**
     * Gets the std_N_Maiden_Name value for this Sse_Responsable_WunitRecord.
     * 
     * @return std_N_Maiden_Name
     */
    public java.lang.String getStd_N_Maiden_Name() {
        return std_N_Maiden_Name;
    }


    /**
     * Sets the std_N_Maiden_Name value for this Sse_Responsable_WunitRecord.
     * 
     * @param std_N_Maiden_Name
     */
    public void setStd_N_Maiden_Name(java.lang.String std_N_Maiden_Name) {
        this.std_N_Maiden_Name = std_N_Maiden_Name;
    }


    /**
     * Gets the std_N_Work_Unit value for this Sse_Responsable_WunitRecord.
     * 
     * @return std_N_Work_Unit
     */
    public java.lang.String getStd_N_Work_Unit() {
        return std_N_Work_Unit;
    }


    /**
     * Sets the std_N_Work_Unit value for this Sse_Responsable_WunitRecord.
     * 
     * @param std_N_Work_Unit
     */
    public void setStd_N_Work_Unit(java.lang.String std_N_Work_Unit) {
        this.std_N_Work_Unit = std_N_Work_Unit;
    }

    private java.lang.Object __equalsCalc = null;
    public synchronized boolean equals(java.lang.Object obj) {
        if (!(obj instanceof Sse_Responsable_WunitRecord)) return false;
        Sse_Responsable_WunitRecord other = (Sse_Responsable_WunitRecord) obj;
        if (obj == null) return false;
        if (this == obj) return true;
        if (__equalsCalc != null) {
            return (__equalsCalc == obj);
        }
        __equalsCalc = obj;
        boolean _equals;
        _equals = true && 
            ((this.m4AutoGeneratedRecordID==null && other.getM4AutoGeneratedRecordID()==null) || 
             (this.m4AutoGeneratedRecordID!=null &&
              this.m4AutoGeneratedRecordID.equals(other.getM4AutoGeneratedRecordID()))) &&
            this.m4AutoGeneratedToDelete == other.isM4AutoGeneratedToDelete() &&
            ((this.sco_Id_Hr==null && other.getSco_Id_Hr()==null) || 
             (this.sco_Id_Hr!=null &&
              this.sco_Id_Hr.equals(other.getSco_Id_Hr()))) &&
            ((this.sco_Or_Hr_Period==null && other.getSco_Or_Hr_Period()==null) || 
             (this.sco_Or_Hr_Period!=null &&
              this.sco_Or_Hr_Period.equals(other.getSco_Or_Hr_Period()))) &&
            ((this.std_Id_Work_Unit==null && other.getStd_Id_Work_Unit()==null) || 
             (this.std_Id_Work_Unit!=null &&
              this.std_Id_Work_Unit.equals(other.getStd_Id_Work_Unit()))) &&
            ((this.std_N_Family_Name_1==null && other.getStd_N_Family_Name_1()==null) || 
             (this.std_N_Family_Name_1!=null &&
              this.std_N_Family_Name_1.equals(other.getStd_N_Family_Name_1()))) &&
            ((this.std_N_First_Name==null && other.getStd_N_First_Name()==null) || 
             (this.std_N_First_Name!=null &&
              this.std_N_First_Name.equals(other.getStd_N_First_Name()))) &&
            ((this.std_N_Maiden_Name==null && other.getStd_N_Maiden_Name()==null) || 
             (this.std_N_Maiden_Name!=null &&
              this.std_N_Maiden_Name.equals(other.getStd_N_Maiden_Name()))) &&
            ((this.std_N_Work_Unit==null && other.getStd_N_Work_Unit()==null) || 
             (this.std_N_Work_Unit!=null &&
              this.std_N_Work_Unit.equals(other.getStd_N_Work_Unit())));
        __equalsCalc = null;
        return _equals;
    }

    private boolean __hashCodeCalc = false;
    public synchronized int hashCode() {
        if (__hashCodeCalc) {
            return 0;
        }
        __hashCodeCalc = true;
        int _hashCode = 1;
        if (getM4AutoGeneratedRecordID() != null) {
            _hashCode += getM4AutoGeneratedRecordID().hashCode();
        }
        _hashCode += (isM4AutoGeneratedToDelete() ? Boolean.TRUE : Boolean.FALSE).hashCode();
        if (getSco_Id_Hr() != null) {
            _hashCode += getSco_Id_Hr().hashCode();
        }
        if (getSco_Or_Hr_Period() != null) {
            _hashCode += getSco_Or_Hr_Period().hashCode();
        }
        if (getStd_Id_Work_Unit() != null) {
            _hashCode += getStd_Id_Work_Unit().hashCode();
        }
        if (getStd_N_Family_Name_1() != null) {
            _hashCode += getStd_N_Family_Name_1().hashCode();
        }
        if (getStd_N_First_Name() != null) {
            _hashCode += getStd_N_First_Name().hashCode();
        }
        if (getStd_N_Maiden_Name() != null) {
            _hashCode += getStd_N_Maiden_Name().hashCode();
        }
        if (getStd_N_Work_Unit() != null) {
            _hashCode += getStd_N_Work_Unit().hashCode();
        }
        __hashCodeCalc = false;
        return _hashCode;
    }

    // Type metadata
    private static org.apache.axis.description.TypeDesc typeDesc =
        new org.apache.axis.description.TypeDesc(Sse_Responsable_WunitRecord.class, true);

    static {
        typeDesc.setXmlType(new javax.xml.namespace.QName("http://schemas.meta4.com/types", "Sse_Responsable_WunitRecord"));
        org.apache.axis.description.ElementDesc elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedRecordID");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedRecordID"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("m4AutoGeneratedToDelete");
        elemField.setXmlName(new javax.xml.namespace.QName("", "m4AutoGeneratedToDelete"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "boolean"));
        elemField.setNillable(false);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Id_Hr");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Id_Hr"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("sco_Or_Hr_Period");
        elemField.setXmlName(new javax.xml.namespace.QName("", "sco_Or_Hr_Period"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "double"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_Id_Work_Unit");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_Id_Work_Unit"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_N_Family_Name_1");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_N_Family_Name_1"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_N_First_Name");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_N_First_Name"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_N_Maiden_Name");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_N_Maiden_Name"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
        elemField = new org.apache.axis.description.ElementDesc();
        elemField.setFieldName("std_N_Work_Unit");
        elemField.setXmlName(new javax.xml.namespace.QName("", "std_N_Work_Unit"));
        elemField.setXmlType(new javax.xml.namespace.QName("http://www.w3.org/2001/XMLSchema", "string"));
        elemField.setNillable(true);
        typeDesc.addFieldDesc(elemField);
    }

    /**
     * Return type metadata object
     */
    public static org.apache.axis.description.TypeDesc getTypeDesc() {
        return typeDesc;
    }

    /**
     * Get Custom Serializer
     */
    public static org.apache.axis.encoding.Serializer getSerializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanSerializer(
            _javaType, _xmlType, typeDesc);
    }

    /**
     * Get Custom Deserializer
     */
    public static org.apache.axis.encoding.Deserializer getDeserializer(
           java.lang.String mechType, 
           java.lang.Class _javaType,  
           javax.xml.namespace.QName _xmlType) {
        return 
          new  org.apache.axis.encoding.ser.BeanDeserializer(
            _javaType, _xmlType, typeDesc);
    }

}
