/**
 * Csp_Mbl_Soap_EssService.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.portalmobile.meta4.schemas;

public interface Csp_Mbl_Soap_EssService extends java.rmi.Remote {
    public com.portalmobile.meta4.schemas.types.Ess_Delete_Abs_SolicOutput ESS_DELETE_ABS_SOLIC(java.lang.String ID_HR, java.lang.Double ORDINAL, java.lang.String OPTIONAL) throws java.rmi.RemoteException, com.portalmobile.meta4.soapservices.exception.M4SoapException;
    public com.portalmobile.meta4.schemas.types.Mss_Cancel_AbsentismoOutput MSS_CANCEL_ABSENTISMO(java.lang.String ID_HR, java.lang.Double ORDINAL, java.lang.String MOTIVO, java.lang.String OPTIONAL) throws java.rmi.RemoteException, com.portalmobile.meta4.soapservices.exception.M4SoapException;
    public com.portalmobile.meta4.schemas.types.Seg_Change_Password_UserOutput SEG_CHANGE_PASSWORD_USER(java.lang.String NEW_PASSWORD) throws java.rmi.RemoteException, com.portalmobile.meta4.soapservices.exception.M4SoapException;
    public com.portalmobile.meta4.schemas.types.Ess_Get_Absentismos_RhOutput ESS_GET_ABSENTISMOS_RH(java.lang.String ID_HR, java.lang.Double ANIO) throws java.rmi.RemoteException, com.portalmobile.meta4.soapservices.exception.M4SoapException;
    public com.portalmobile.meta4.schemas.types.Seg_Forget_Password_UserOutput SEG_FORGET_PASSWORD_USER(java.lang.String PARAM_NIF, java.lang.String PARAM_APELLIDO1, java.lang.String PARAM_MAIL) throws java.rmi.RemoteException, com.portalmobile.meta4.soapservices.exception.M4SoapException;
    public com.portalmobile.meta4.schemas.types.Ess_Download_ReciboOutput ESS_DOWNLOAD_RECIBO(java.lang.String ID_HR, java.lang.String FECHA_PAGO, java.lang.String FECHA_IMPUTACION) throws java.rmi.RemoteException, com.portalmobile.meta4.soapservices.exception.M4SoapException;
    public com.portalmobile.meta4.schemas.types.Ess_Get_Recibos_NominaOutput ESS_GET_RECIBOS_NOMINA(java.lang.String ID_HR, java.lang.Double ANIO, java.lang.String OPTIONALS) throws java.rmi.RemoteException, com.portalmobile.meta4.soapservices.exception.M4SoapException;
    public com.portalmobile.meta4.schemas.types.Ess_Save_New_AbsentismoOutput ESS_SAVE_NEW_ABSENTISMO(java.lang.String ID_HR, java.lang.String INICIO, java.lang.String FIN, java.lang.String TIPO_AUSENCIA, java.lang.String COMENTARIO, java.lang.String TIPO_RERSPONSABLE, java.lang.String OPTIONAL) throws java.rmi.RemoteException, com.portalmobile.meta4.soapservices.exception.M4SoapException;
    public com.portalmobile.meta4.schemas.types.Mss_Get_AbsentismosOutput MSS_GET_ABSENTISMOS(java.lang.String ID_HR, java.lang.String OPTIONAL) throws java.rmi.RemoteException, com.portalmobile.meta4.soapservices.exception.M4SoapException;
    public com.portalmobile.meta4.schemas.types.Mss_Confirm_AbsentismoOutput MSS_CONFIRM_ABSENTISMO(java.lang.String ID_HR, java.lang.Double ORDINAL, java.lang.String MOTIVO, java.lang.String OPTIONAL) throws java.rmi.RemoteException, com.portalmobile.meta4.soapservices.exception.M4SoapException;
    public com.portalmobile.meta4.schemas.types.Ess_Send_FileOutput ESS_SEND_FILE(java.lang.String ARG_ID_EMPLEADO, java.lang.String ARG_TP_FILE, java.lang.String ARG_EXTENSION, java.lang.String ARG_COMMENT_USER, com.portalmobile.meta4.schemas.types.Ess_Send_FileBlock ESS_SEND_FILE) throws java.rmi.RemoteException, com.portalmobile.meta4.soapservices.exception.M4SoapException;
    public com.portalmobile.meta4.schemas.types.Mss_Get_Mis_ConsultasOutput MSS_GET_MIS_CONSULTAS(java.lang.String OPTIONAL) throws java.rmi.RemoteException, com.portalmobile.meta4.soapservices.exception.M4SoapException;
    public com.portalmobile.meta4.schemas.types.M4LoadobjectOutput m4LoadObject(com.portalmobile.meta4.schemas.types.Ess_Send_FileBlock ESS_SEND_FILE, com.portalmobile.meta4.schemas.types.Csp_Mbl_Soap_EssBlock CSP_MBL_SOAP_ESS, com.portalmobile.meta4.schemas.types.Ess_Tp_Docs_SendBlock ESS_TP_DOCS_SEND, com.portalmobile.meta4.schemas.types.Mss_Workflow_AbsBlock MSS_WORKFLOW_ABS, com.portalmobile.meta4.schemas.types.Ess_Send_File_DataBlock ESS_SEND_FILE_DATA, com.portalmobile.meta4.schemas.types.Ess_Who_Is_Who_DataBlock ESS_WHO_IS_WHO_DATA, com.portalmobile.meta4.schemas.types.Ess_Get_Noticias_DataBlock ESS_GET_NOTICIAS_DATA, com.portalmobile.meta4.schemas.types.Ess_Send_File_Rh_DataBlock ESS_SEND_FILE_RH_DATA, com.portalmobile.meta4.schemas.types.Ess_Who_Is_Who_ResultBlock ESS_WHO_IS_WHO_RESULT, com.portalmobile.meta4.schemas.types.Mss_Get_Mis_ConsultasBlock MSS_GET_MIS_CONSULTAS, com.portalmobile.meta4.schemas.types.Ess_Get_Noticias_ResultBlock ESS_GET_NOTICIAS_RESULT, com.portalmobile.meta4.schemas.types.Mss_Get_Absentismos_DataBlock MSS_GET_ABSENTISMOS_DATA, com.portalmobile.meta4.schemas.types.Ess_Who_Is_Who_Data_CountBlock ESS_WHO_IS_WHO_DATA_COUNT, com.portalmobile.meta4.schemas.types.Mss_Get_Absentismos_ResultBlock MSS_GET_ABSENTISMOS_RESULT, com.portalmobile.meta4.schemas.types.Ess_Get_Absentismos_Rh_DataBlock ESS_GET_ABSENTISMOS_RH_DATA, com.portalmobile.meta4.schemas.types.Ess_Get_Recibos_Nomina_DataBlock ESS_GET_RECIBOS_NOMINA_DATA, com.portalmobile.meta4.schemas.types.Ess_Get_Tp_Documents_ResultBlock ESS_GET_TP_DOCUMENTS_RESULT, com.portalmobile.meta4.schemas.types.Mss_Get_Mis_Consultas_EngineBlock MSS_GET_MIS_CONSULTAS_ENGINE, com.portalmobile.meta4.schemas.types.Mss_Get_Mis_Consultas_ResultBlock MSS_GET_MIS_CONSULTAS_RESULT, com.portalmobile.meta4.schemas.types.Ess_Get_Absentismos_Rh_ResultBlock ESS_GET_ABSENTISMOS_RH_RESULT, com.portalmobile.meta4.schemas.types.Ess_Get_Absentismos_Rh_SolictBlock ESS_GET_ABSENTISMOS_RH_SOLICT, com.portalmobile.meta4.schemas.types.Ess_Get_Noticias_Data_PrivateBlock ESS_GET_NOTICIAS_DATA_PRIVATE, com.portalmobile.meta4.schemas.types.Ess_Get_Recibos_Nomina_ResultBlock ESS_GET_RECIBOS_NOMINA_RESULT) throws java.rmi.RemoteException, com.portalmobile.meta4.soapservices.exception.M4SoapException;
    public com.portalmobile.meta4.schemas.types.Ess_Who_Is_WhoOutput ESS_WHO_IS_WHO(java.lang.Double PAGINA, java.lang.String FILTRO, java.lang.Double ITEMS) throws java.rmi.RemoteException, com.portalmobile.meta4.soapservices.exception.M4SoapException;
    public com.portalmobile.meta4.schemas.types.Mss_Exec_QueryOutput MSS_EXEC_QUERY(java.lang.String ID_META4OBJECT, java.lang.String ARGUMENTS) throws java.rmi.RemoteException, com.portalmobile.meta4.soapservices.exception.M4SoapException;
    public com.portalmobile.meta4.schemas.types.Ess_Get_NoticiasOutput ESS_GET_NOTICIAS() throws java.rmi.RemoteException, com.portalmobile.meta4.soapservices.exception.M4SoapException;
    public com.portalmobile.meta4.schemas.types.Ess_Get_Tp_Documents_SendOutput ESS_GET_TP_DOCUMENTS_SEND() throws java.rmi.RemoteException, com.portalmobile.meta4.soapservices.exception.M4SoapException;
    public com.portalmobile.meta4.schemas.types.Mss_Get_Mis_Consultas_MetadataOutput MSS_GET_MIS_CONSULTAS_METADATA(java.lang.String ID_META4OBJECT) throws java.rmi.RemoteException, com.portalmobile.meta4.soapservices.exception.M4SoapException;
    public int retrieveM4Session(java.lang.String in0) throws java.rmi.RemoteException, com.portalmobile.meta4.soapservices.exception.M4SoapException;
}
