package com.common.hibernate.entidades;

// Generated 26-ago-2014 10:48:56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VinDevices generated by hbm2java
 */
@Entity
@Table(name = "vin_devices", catalog = "movilidad")
public class VinDevices implements java.io.Serializable {

	private String idDevice;
	private String name;
	private String comment;
	private String parseChannel;
	private String parseDeviceType;
	private Set<VinUsers> vinUsersesForIdDispLogin = new HashSet<VinUsers>(0);
	private Set<VinParamsDevice> vinParamsDevices = new HashSet<VinParamsDevice>(
			0);
	private Set<VinUsers> vinUsersesForIdDispAccess = new HashSet<VinUsers>(0);

	public VinDevices() {
	}

	public VinDevices(String idDevice, String name) {
		this.idDevice = idDevice;
		this.name = name;
	}

	public VinDevices(String idDevice, String name, String comment,
			String parseChannel, String parseDeviceType,
			Set<VinUsers> vinUsersesForIdDispLogin,
			Set<VinParamsDevice> vinParamsDevices,
			Set<VinUsers> vinUsersesForIdDispAccess) {
		this.idDevice = idDevice;
		this.name = name;
		this.comment = comment;
		this.parseChannel = parseChannel;
		this.parseDeviceType = parseDeviceType;
		this.vinUsersesForIdDispLogin = vinUsersesForIdDispLogin;
		this.vinParamsDevices = vinParamsDevices;
		this.vinUsersesForIdDispAccess = vinUsersesForIdDispAccess;
	}

	@Id
	@Column(name = "id_device", unique = true, nullable = false, length = 50)
	public String getIdDevice() {
		return this.idDevice;
	}

	public void setIdDevice(String idDevice) {
		this.idDevice = idDevice;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "comment", length = 250)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "parse_channel", length = 250)
	public String getParseChannel() {
		return this.parseChannel;
	}

	public void setParseChannel(String parseChannel) {
		this.parseChannel = parseChannel;
	}

	@Column(name = "parse_device_type", length = 50)
	public String getParseDeviceType() {
		return this.parseDeviceType;
	}

	public void setParseDeviceType(String parseDeviceType) {
		this.parseDeviceType = parseDeviceType;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vinDevicesByIdDispLogin")
	public Set<VinUsers> getVinUsersesForIdDispLogin() {
		return this.vinUsersesForIdDispLogin;
	}

	public void setVinUsersesForIdDispLogin(
			Set<VinUsers> vinUsersesForIdDispLogin) {
		this.vinUsersesForIdDispLogin = vinUsersesForIdDispLogin;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vinDevices")
	public Set<VinParamsDevice> getVinParamsDevices() {
		return this.vinParamsDevices;
	}

	public void setVinParamsDevices(Set<VinParamsDevice> vinParamsDevices) {
		this.vinParamsDevices = vinParamsDevices;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vinDevicesByIdDispAccess")
	public Set<VinUsers> getVinUsersesForIdDispAccess() {
		return this.vinUsersesForIdDispAccess;
	}

	public void setVinUsersesForIdDispAccess(
			Set<VinUsers> vinUsersesForIdDispAccess) {
		this.vinUsersesForIdDispAccess = vinUsersesForIdDispAccess;
	}

}
