package com.common.hibernate.entidades;

// Generated 21-may-2014 10:40:36 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VinLogs generated by hbm2java
 */
@Entity
@Table(name = "vin_logs", catalog = "movilidad")
public class VinLogs implements java.io.Serializable {

	private Double ordinal;
	private String idUser;
	private Date dtExec;
	private String textLog;

	public VinLogs() {
	}

	public VinLogs(String idUser, Date dtExec, String textLog) {
		this.idUser = idUser;
		this.dtExec = dtExec;
		this.textLog = textLog;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ordinal", unique = true, nullable = false, precision = 22, scale = 0)
	public Double getOrdinal() {
		return this.ordinal;
	}

	public void setOrdinal(Double ordinal) {
		this.ordinal = ordinal;
	}

	@Column(name = "id_user", nullable = false, length = 200)
	public String getIdUser() {
		return this.idUser;
	}

	public void setIdUser(String idUser) {
		this.idUser = idUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_exec", nullable = false, length = 19)
	public Date getDtExec() {
		return this.dtExec;
	}

	public void setDtExec(Date dtExec) {
		this.dtExec = dtExec;
	}

	@Column(name = "text_log", nullable = false)
	public String getTextLog() {
		return this.textLog;
	}

	public void setTextLog(String textLog) {
		this.textLog = textLog;
	}

}
