package com.common.hibernate.entidades;

// Generated 26-ago-2014 10:48:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VinNotifications generated by hbm2java
 */
@Entity
@Table(name = "vin_notifications", catalog = "movilidad")
public class VinNotifications implements java.io.Serializable {

	private VinNotificationsId id;
	private VinSystems vinSystems;
	private VinUsers vinUsers;
	private String title;
	private String message;
	private Date dtSend;
	private Date dtEnd;
	private Integer chkReaded;
	private Integer chkDeleted;

	public VinNotifications() {
	}

	public VinNotifications(VinNotificationsId id, VinSystems vinSystems,
			VinUsers vinUsers, String title, String message, Date dtSend,
			Date dtEnd) {
		this.id = id;
		this.vinSystems = vinSystems;
		this.vinUsers = vinUsers;
		this.title = title;
		this.message = message;
		this.dtSend = dtSend;
		this.dtEnd = dtEnd;
	}

	public VinNotifications(VinNotificationsId id, VinSystems vinSystems,
			VinUsers vinUsers, String title, String message, Date dtSend,
			Date dtEnd, Integer chkReaded, Integer chkDeleted) {
		this.id = id;
		this.vinSystems = vinSystems;
		this.vinUsers = vinUsers;
		this.title = title;
		this.message = message;
		this.dtSend = dtSend;
		this.dtEnd = dtEnd;
		this.chkReaded = chkReaded;
		this.chkDeleted = chkDeleted;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ordinal", column = @Column(name = "ordinal", nullable = false)),
			@AttributeOverride(name = "idUser", column = @Column(name = "id_user", nullable = false, length = 200)) })
	public VinNotificationsId getId() {
		return this.id;
	}

	public void setId(VinNotificationsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_system", nullable = false)
	public VinSystems getVinSystems() {
		return this.vinSystems;
	}

	public void setVinSystems(VinSystems vinSystems) {
		this.vinSystems = vinSystems;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user", nullable = false, insertable = false, updatable = false)
	public VinUsers getVinUsers() {
		return this.vinUsers;
	}

	public void setVinUsers(VinUsers vinUsers) {
		this.vinUsers = vinUsers;
	}

	@Column(name = "title", nullable = false, length = 250)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "message", nullable = false, length = 16777215)
	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_send", nullable = false, length = 10)
	public Date getDtSend() {
		return this.dtSend;
	}

	public void setDtSend(Date dtSend) {
		this.dtSend = dtSend;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_end", nullable = false, length = 10)
	public Date getDtEnd() {
		return this.dtEnd;
	}

	public void setDtEnd(Date dtEnd) {
		this.dtEnd = dtEnd;
	}

	@Column(name = "chk_readed")
	public Integer getChkReaded() {
		return this.chkReaded;
	}

	public void setChkReaded(Integer chkReaded) {
		this.chkReaded = chkReaded;
	}

	@Column(name = "chk_deleted")
	public Integer getChkDeleted() {
		return this.chkDeleted;
	}

	public void setChkDeleted(Integer chkDeleted) {
		this.chkDeleted = chkDeleted;
	}

}
