package com.common.hibernate.entidades;

// Generated 26-ago-2014 10:48:56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VinParamsDevice generated by hbm2java
 */
@Entity
@Table(name = "vin_params_device", catalog = "movilidad")
public class VinParamsDevice implements java.io.Serializable {

	private VinParamsDeviceId id;
	private VinParamsGlobal vinParamsGlobal;
	private VinDevices vinDevices;
	private String value;
	private String comment;

	public VinParamsDevice() {
	}

	public VinParamsDevice(VinParamsDeviceId id,
			VinParamsGlobal vinParamsGlobal, VinDevices vinDevices, String value) {
		this.id = id;
		this.vinParamsGlobal = vinParamsGlobal;
		this.vinDevices = vinDevices;
		this.value = value;
	}

	public VinParamsDevice(VinParamsDeviceId id,
			VinParamsGlobal vinParamsGlobal, VinDevices vinDevices,
			String value, String comment) {
		this.id = id;
		this.vinParamsGlobal = vinParamsGlobal;
		this.vinDevices = vinDevices;
		this.value = value;
		this.comment = comment;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idDevice", column = @Column(name = "id_device", nullable = false, length = 50)),
			@AttributeOverride(name = "idParam", column = @Column(name = "id_param", nullable = false)) })
	public VinParamsDeviceId getId() {
		return this.id;
	}

	public void setId(VinParamsDeviceId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_param", nullable = false, insertable = false, updatable = false)
	public VinParamsGlobal getVinParamsGlobal() {
		return this.vinParamsGlobal;
	}

	public void setVinParamsGlobal(VinParamsGlobal vinParamsGlobal) {
		this.vinParamsGlobal = vinParamsGlobal;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_device", nullable = false, insertable = false, updatable = false)
	public VinDevices getVinDevices() {
		return this.vinDevices;
	}

	public void setVinDevices(VinDevices vinDevices) {
		this.vinDevices = vinDevices;
	}

	@Column(name = "value", nullable = false, length = 65535)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "comment", length = 250)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

}
