package com.common.hibernate.entidades;

// Generated 26-ago-2014 10:48:56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VinParamsDeviceId generated by hbm2java
 */
@Embeddable
public class VinParamsDeviceId implements java.io.Serializable {

	private String idDevice;
	private int idParam;

	public VinParamsDeviceId() {
	}

	public VinParamsDeviceId(String idDevice, int idParam) {
		this.idDevice = idDevice;
		this.idParam = idParam;
	}

	@Column(name = "id_device", nullable = false, length = 50)
	public String getIdDevice() {
		return this.idDevice;
	}

	public void setIdDevice(String idDevice) {
		this.idDevice = idDevice;
	}

	@Column(name = "id_param", nullable = false)
	public int getIdParam() {
		return this.idParam;
	}

	public void setIdParam(int idParam) {
		this.idParam = idParam;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VinParamsDeviceId))
			return false;
		VinParamsDeviceId castOther = (VinParamsDeviceId) other;

		return ((this.getIdDevice() == castOther.getIdDevice()) || (this
				.getIdDevice() != null && castOther.getIdDevice() != null && this
				.getIdDevice().equals(castOther.getIdDevice())))
				&& (this.getIdParam() == castOther.getIdParam());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdDevice() == null ? 0 : this.getIdDevice().hashCode());
		result = 37 * result + this.getIdParam();
		return result;
	}

}
