package com.common.hibernate.entidades;

// Generated 26-ago-2014 10:48:56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VinParamsRoleId generated by hbm2java
 */
@Embeddable
public class VinParamsRoleId implements java.io.Serializable {

	private int idRole;
	private int idParam;

	public VinParamsRoleId() {
	}

	public VinParamsRoleId(int idRole, int idParam) {
		this.idRole = idRole;
		this.idParam = idParam;
	}

	@Column(name = "id_role", nullable = false)
	public int getIdRole() {
		return this.idRole;
	}

	public void setIdRole(int idRole) {
		this.idRole = idRole;
	}

	@Column(name = "id_param", nullable = false)
	public int getIdParam() {
		return this.idParam;
	}

	public void setIdParam(int idParam) {
		this.idParam = idParam;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VinParamsRoleId))
			return false;
		VinParamsRoleId castOther = (VinParamsRoleId) other;

		return (this.getIdRole() == castOther.getIdRole())
				&& (this.getIdParam() == castOther.getIdParam());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdRole();
		result = 37 * result + this.getIdParam();
		return result;
	}

}
