package com.common.hibernate.entidades;

// Generated 26-ago-2014 10:48:56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VinParamsGlobal generated by hbm2java
 */
@Entity
@Table(name = "vin_params_global", catalog = "movilidad")
public class VinParamsGlobal implements java.io.Serializable {

	private Integer id;
	private String name;
	private String comment;
	private String value;
	private Set<VinParamsProcess> vinParamsProcesses = new HashSet<VinParamsProcess>(
			0);
	private Set<VinParamsRole> vinParamsRoles = new HashSet<VinParamsRole>(0);
	private Set<VinParamsSystem> vinParamsSystems = new HashSet<VinParamsSystem>(
			0);
	private Set<VinParamsUser> vinParamsUsers = new HashSet<VinParamsUser>(0);
	private Set<VinParamsDevice> vinParamsDevices = new HashSet<VinParamsDevice>(
			0);

	public VinParamsGlobal() {
	}

	public VinParamsGlobal(String name, String value) {
		this.name = name;
		this.value = value;
	}

	public VinParamsGlobal(String name, String comment, String value,
			Set<VinParamsProcess> vinParamsProcesses,
			Set<VinParamsRole> vinParamsRoles,
			Set<VinParamsSystem> vinParamsSystems,
			Set<VinParamsUser> vinParamsUsers,
			Set<VinParamsDevice> vinParamsDevices) {
		this.name = name;
		this.comment = comment;
		this.value = value;
		this.vinParamsProcesses = vinParamsProcesses;
		this.vinParamsRoles = vinParamsRoles;
		this.vinParamsSystems = vinParamsSystems;
		this.vinParamsUsers = vinParamsUsers;
		this.vinParamsDevices = vinParamsDevices;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "comment", length = 250)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "value", nullable = false, length = 65535)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vinParamsGlobal")
	public Set<VinParamsProcess> getVinParamsProcesses() {
		return this.vinParamsProcesses;
	}

	public void setVinParamsProcesses(Set<VinParamsProcess> vinParamsProcesses) {
		this.vinParamsProcesses = vinParamsProcesses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vinParamsGlobal")
	public Set<VinParamsRole> getVinParamsRoles() {
		return this.vinParamsRoles;
	}

	public void setVinParamsRoles(Set<VinParamsRole> vinParamsRoles) {
		this.vinParamsRoles = vinParamsRoles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vinParamsGlobal")
	public Set<VinParamsSystem> getVinParamsSystems() {
		return this.vinParamsSystems;
	}

	public void setVinParamsSystems(Set<VinParamsSystem> vinParamsSystems) {
		this.vinParamsSystems = vinParamsSystems;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vinParamsGlobal")
	public Set<VinParamsUser> getVinParamsUsers() {
		return this.vinParamsUsers;
	}

	public void setVinParamsUsers(Set<VinParamsUser> vinParamsUsers) {
		this.vinParamsUsers = vinParamsUsers;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vinParamsGlobal")
	public Set<VinParamsDevice> getVinParamsDevices() {
		return this.vinParamsDevices;
	}

	public void setVinParamsDevices(Set<VinParamsDevice> vinParamsDevices) {
		this.vinParamsDevices = vinParamsDevices;
	}

}
