package com.common.hibernate.entidades;

// Generated 26-ago-2014 10:48:56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VinParamsSystemView generated by hbm2java
 */
@Entity
@Table(name = "vin_params_system_view", catalog = "movilidad")
public class VinParamsSystemView implements java.io.Serializable {

	private VinParamsSystemViewId id;

	public VinParamsSystemView() {
	}

	public VinParamsSystemView(VinParamsSystemViewId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idSystem", column = @Column(name = "id_system", nullable = false, length = 10)),
			@AttributeOverride(name = "name", column = @Column(name = "name", nullable = false, length = 100)),
			@AttributeOverride(name = "idParam", column = @Column(name = "id_param", nullable = false)),
			@AttributeOverride(name = "nameParam", column = @Column(name = "name_param", nullable = false, length = 100)),
			@AttributeOverride(name = "value", column = @Column(name = "value", nullable = false, length = 65535)),
			@AttributeOverride(name = "comment", column = @Column(name = "comment", length = 250)),
			@AttributeOverride(name = "commentParam", column = @Column(name = "comment_param", length = 250)) })
	public VinParamsSystemViewId getId() {
		return this.id;
	}

	public void setId(VinParamsSystemViewId id) {
		this.id = id;
	}

}
