package com.common.hibernate.entidades;

// Generated 26-ago-2014 10:48:56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VinProcessView generated by hbm2java
 */
@Entity
@Table(name = "vin_process_view", catalog = "movilidad")
public class VinProcessView implements java.io.Serializable {

	private VinProcessViewId id;

	public VinProcessView() {
	}

	public VinProcessView(VinProcessViewId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idProcess", column = @Column(name = "id_process", nullable = false, length = 200)),
			@AttributeOverride(name = "name", column = @Column(name = "name", nullable = false, length = 200)),
			@AttributeOverride(name = "idSystem", column = @Column(name = "id_system", length = 10)),
			@AttributeOverride(name = "nameSystem", column = @Column(name = "name_system", nullable = false, length = 100)),
			@AttributeOverride(name = "comment", column = @Column(name = "comment", length = 250)) })
	public VinProcessViewId getId() {
		return this.id;
	}

	public void setId(VinProcessViewId id) {
		this.id = id;
	}

}
