package com.common.hibernate.entidades;

// Generated 26-ago-2014 10:48:56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VinProcess generated by hbm2java
 */
@Entity
@Table(name = "vin_process", catalog = "movilidad")
public class VinProcess implements java.io.Serializable {

	private String idProcess;
	private VinSystems vinSystems;
	private String name;
	private String comment;
	private Set<VinStatistics> vinStatisticses = new HashSet<VinStatistics>(0);
	private Set<VinParamsProcess> vinParamsProcesses = new HashSet<VinParamsProcess>(
			0);

	public VinProcess() {
	}

	public VinProcess(String idProcess, String name) {
		this.idProcess = idProcess;
		this.name = name;
	}

	public VinProcess(String idProcess, VinSystems vinSystems, String name,
			String comment, Set<VinStatistics> vinStatisticses,
			Set<VinParamsProcess> vinParamsProcesses) {
		this.idProcess = idProcess;
		this.vinSystems = vinSystems;
		this.name = name;
		this.comment = comment;
		this.vinStatisticses = vinStatisticses;
		this.vinParamsProcesses = vinParamsProcesses;
	}

	@Id
	@Column(name = "id_process", unique = true, nullable = false, length = 200)
	public String getIdProcess() {
		return this.idProcess;
	}

	public void setIdProcess(String idProcess) {
		this.idProcess = idProcess;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_system")
	public VinSystems getVinSystems() {
		return this.vinSystems;
	}

	public void setVinSystems(VinSystems vinSystems) {
		this.vinSystems = vinSystems;
	}

	@Column(name = "name", nullable = false, length = 200)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "comment", length = 250)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vinProcess")
	public Set<VinStatistics> getVinStatisticses() {
		return this.vinStatisticses;
	}

	public void setVinStatisticses(Set<VinStatistics> vinStatisticses) {
		this.vinStatisticses = vinStatisticses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vinProcess")
	public Set<VinParamsProcess> getVinParamsProcesses() {
		return this.vinParamsProcesses;
	}

	public void setVinParamsProcesses(Set<VinParamsProcess> vinParamsProcesses) {
		this.vinParamsProcesses = vinParamsProcesses;
	}

}
