package com.common.hibernate.entidades;

// Generated 26-ago-2014 10:48:56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VinParamsUserViewId generated by hbm2java
 */
@Embeddable
public class VinParamsUserViewId implements java.io.Serializable {

	private String idUser;
	private String name;
	private int idParam;
	private String nameParam;
	private String value;
	private String comment;
	private String commentParam;

	public VinParamsUserViewId() {
	}

	public VinParamsUserViewId(String idUser, String name, int idParam,
			String nameParam) {
		this.idUser = idUser;
		this.name = name;
		this.idParam = idParam;
		this.nameParam = nameParam;
	}

	public VinParamsUserViewId(String idUser, String name, int idParam,
			String nameParam, String value, String comment, String commentParam) {
		this.idUser = idUser;
		this.name = name;
		this.idParam = idParam;
		this.nameParam = nameParam;
		this.value = value;
		this.comment = comment;
		this.commentParam = commentParam;
	}

	@Column(name = "id_user", nullable = false, length = 200)
	public String getIdUser() {
		return this.idUser;
	}

	public void setIdUser(String idUser) {
		this.idUser = idUser;
	}

	@Column(name = "name", nullable = false, length = 150)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "id_param", nullable = false)
	public int getIdParam() {
		return this.idParam;
	}

	public void setIdParam(int idParam) {
		this.idParam = idParam;
	}

	@Column(name = "name_param", nullable = false, length = 100)
	public String getNameParam() {
		return this.nameParam;
	}

	public void setNameParam(String nameParam) {
		this.nameParam = nameParam;
	}

	@Column(name = "value", length = 65535)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	@Column(name = "comment", length = 250)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "comment_param", length = 250)
	public String getCommentParam() {
		return this.commentParam;
	}

	public void setCommentParam(String commentParam) {
		this.commentParam = commentParam;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VinParamsUserViewId))
			return false;
		VinParamsUserViewId castOther = (VinParamsUserViewId) other;

		return ((this.getIdUser() == castOther.getIdUser()) || (this
				.getIdUser() != null && castOther.getIdUser() != null && this
				.getIdUser().equals(castOther.getIdUser())))
				&& ((this.getName() == castOther.getName()) || (this.getName() != null
						&& castOther.getName() != null && this.getName()
						.equals(castOther.getName())))
				&& (this.getIdParam() == castOther.getIdParam())
				&& ((this.getNameParam() == castOther.getNameParam()) || (this
						.getNameParam() != null
						&& castOther.getNameParam() != null && this
						.getNameParam().equals(castOther.getNameParam())))
				&& ((this.getValue() == castOther.getValue()) || (this
						.getValue() != null && castOther.getValue() != null && this
						.getValue().equals(castOther.getValue())))
				&& ((this.getComment() == castOther.getComment()) || (this
						.getComment() != null && castOther.getComment() != null && this
						.getComment().equals(castOther.getComment())))
				&& ((this.getCommentParam() == castOther.getCommentParam()) || (this
						.getCommentParam() != null
						&& castOther.getCommentParam() != null && this
						.getCommentParam().equals(castOther.getCommentParam())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdUser() == null ? 0 : this.getIdUser().hashCode());
		result = 37 * result
				+ (getName() == null ? 0 : this.getName().hashCode());
		result = 37 * result + this.getIdParam();
		result = 37 * result
				+ (getNameParam() == null ? 0 : this.getNameParam().hashCode());
		result = 37 * result
				+ (getValue() == null ? 0 : this.getValue().hashCode());
		result = 37 * result
				+ (getComment() == null ? 0 : this.getComment().hashCode());
		result = 37
				* result
				+ (getCommentParam() == null ? 0 : this.getCommentParam()
						.hashCode());
		return result;
	}

}
