package com.common.hibernate.entidades;

// Generated 26-ago-2014 10:48:56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * VinParamsSystemId generated by hbm2java
 */
@Embeddable
public class VinParamsSystemId implements java.io.Serializable {

	private String idSystem;
	private int idParam;

	public VinParamsSystemId() {
	}

	public VinParamsSystemId(String idSystem, int idParam) {
		this.idSystem = idSystem;
		this.idParam = idParam;
	}

	@Column(name = "id_system", nullable = false, length = 10)
	public String getIdSystem() {
		return this.idSystem;
	}

	public void setIdSystem(String idSystem) {
		this.idSystem = idSystem;
	}

	@Column(name = "id_param", nullable = false)
	public int getIdParam() {
		return this.idParam;
	}

	public void setIdParam(int idParam) {
		this.idParam = idParam;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VinParamsSystemId))
			return false;
		VinParamsSystemId castOther = (VinParamsSystemId) other;

		return ((this.getIdSystem() == castOther.getIdSystem()) || (this
				.getIdSystem() != null && castOther.getIdSystem() != null && this
				.getIdSystem().equals(castOther.getIdSystem())))
				&& (this.getIdParam() == castOther.getIdParam());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getIdSystem() == null ? 0 : this.getIdSystem().hashCode());
		result = 37 * result + this.getIdParam();
		return result;
	}

}
