package com.common.hibernate.entidades;

// Generated 26-ago-2014 10:48:56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VinRoles generated by hbm2java
 */
@Entity
@Table(name = "vin_roles", catalog = "movilidad")
public class VinRoles implements java.io.Serializable {

	private Integer id;
	private String name;
	private String comment;
	private String parseChannel;
	private Set<VinUsers> vinUserses = new HashSet<VinUsers>(0);
	private Set<VinParamsRole> vinParamsRoles = new HashSet<VinParamsRole>(0);

	public VinRoles() {
	}

	public VinRoles(String name) {
		this.name = name;
	}

	public VinRoles(String name, String comment, String parseChannel,
			Set<VinUsers> vinUserses, Set<VinParamsRole> vinParamsRoles) {
		this.name = name;
		this.comment = comment;
		this.parseChannel = parseChannel;
		this.vinUserses = vinUserses;
		this.vinParamsRoles = vinParamsRoles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "comment", length = 250)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "parse_channel", length = 250)
	public String getParseChannel() {
		return this.parseChannel;
	}

	public void setParseChannel(String parseChannel) {
		this.parseChannel = parseChannel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vinRoles")
	public Set<VinUsers> getVinUserses() {
		return this.vinUserses;
	}

	public void setVinUserses(Set<VinUsers> vinUserses) {
		this.vinUserses = vinUserses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "vinRoles")
	public Set<VinParamsRole> getVinParamsRoles() {
		return this.vinParamsRoles;
	}

	public void setVinParamsRoles(Set<VinParamsRole> vinParamsRoles) {
		this.vinParamsRoles = vinParamsRoles;
	}

}
