package com.common.hibernate.entidades;

// Generated 26-ago-2014 10:48:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;


/**
 * VinStatisticsId generated by hbm2java
 */
@Embeddable
public class VinStatisticsId implements java.io.Serializable {

	private int ordinal;
	private String idUser;
	private Date dateExec;

	public VinStatisticsId() {
	}

	public VinStatisticsId(int ordinal, String idUser, Date dateExec) {
		this.ordinal = ordinal;
		this.idUser = idUser;
		this.dateExec = dateExec;
	}
	

	@Column(name = "ordinal", nullable = false)
	public int getOrdinal() {
		return this.ordinal;
	}

	public void setOrdinal(int ordinal) {
		this.ordinal = ordinal;
	}

	@Column(name = "id_user", nullable = false, length = 200)
	public String getIdUser() {
		return this.idUser;
	}

	public void setIdUser(String idUser) {
		this.idUser = idUser;
	}

	@Column(name = "date_exec", nullable = false, length = 19)
	public Date getDateExec() {
		return this.dateExec;
	}

	public void setDateExec(Date dateExec) {
		this.dateExec = dateExec;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VinStatisticsId))
			return false;
		VinStatisticsId castOther = (VinStatisticsId) other;

		return (this.getOrdinal() == castOther.getOrdinal())
				&& ((this.getIdUser() == castOther.getIdUser()) || (this
						.getIdUser() != null && castOther.getIdUser() != null && this
						.getIdUser().equals(castOther.getIdUser())))
				&& ((this.getDateExec() == castOther.getDateExec()) || (this
						.getDateExec() != null
						&& castOther.getDateExec() != null && this
						.getDateExec().equals(castOther.getDateExec())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getOrdinal();
		result = 37 * result
				+ (getIdUser() == null ? 0 : this.getIdUser().hashCode());
		result = 37 * result
				+ (getDateExec() == null ? 0 : this.getDateExec().hashCode());
		return result;
	}

}
