package com.common.hibernate.entidades;

// Generated 26-ago-2014 10:48:56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VinStatistics generated by hbm2java
 */
@Entity
@Table(name = "vin_statistics", catalog = "movilidad")
public class VinStatistics implements java.io.Serializable {

	private VinStatisticsId id;
	private VinProcess vinProcess;
	private String text;

	public VinStatistics() {
	}

	public VinStatistics(VinStatisticsId id) {
		this.id = id;
	}

	public VinStatistics(VinStatisticsId id, VinProcess vinProcess, String text) {
		this.id = id;
		this.vinProcess = vinProcess;
		this.text = text;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ordinal", column = @Column(name = "ordinal", nullable = false)),
			@AttributeOverride(name = "idUser", column = @Column(name = "id_user", nullable = false, length = 200)),
			@AttributeOverride(name = "dateExec", column = @Column(name = "date_exec", nullable = false, length = 19)) })
	public VinStatisticsId getId() {
		return this.id;
	}

	public void setId(VinStatisticsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_process")
	public VinProcess getVinProcess() {
		return this.vinProcess;
	}

	public void setVinProcess(VinProcess vinProcess) {
		this.vinProcess = vinProcess;
	}

	@Column(name = "text", length = 250)
	public String getText() {
		return this.text;
	}

	public void setText(String text) {
		this.text = text;
	}

}
