package com.common.hibernate.entidades;

// Generated 26-ago-2014 10:48:56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VinStatisticsView generated by hbm2java
 */
@Entity
@Table(name = "vin_statistics_view", catalog = "movilidad")
public class VinStatisticsView implements java.io.Serializable {

	private VinStatisticsViewId id;

	public VinStatisticsView() {
	}

	public VinStatisticsView(VinStatisticsViewId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "ordinal", column = @Column(name = "ordinal", nullable = false)),
			@AttributeOverride(name = "idProcess", column = @Column(name = "id_process", length = 200)),
			@AttributeOverride(name = "nameProcess", column = @Column(name = "name_process", nullable = false, length = 200)),
			@AttributeOverride(name = "comment", column = @Column(name = "comment", length = 250)),
			@AttributeOverride(name = "idSystem", column = @Column(name = "id_system", nullable = false, length = 10)),
			@AttributeOverride(name = "nameSystem", column = @Column(name = "name_system", nullable = false, length = 100)),
			@AttributeOverride(name = "idUser", column = @Column(name = "id_user", nullable = false, length = 200)),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", nullable = false, length = 150)),
			@AttributeOverride(name = "dateExec", column = @Column(name = "date_exec", length = 19)),
			@AttributeOverride(name = "text", column = @Column(name = "text", length = 250)) })
	public VinStatisticsViewId getId() {
		return this.id;
	}

	public void setId(VinStatisticsViewId id) {
		this.id = id;
	}

}
