package com.common.hibernate.entidades;

// Generated 26-ago-2014 10:48:56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VinSystems generated by hbm2java
 */
@Entity
@Table(name = "vin_systems", catalog = "movilidad")
public class VinSystems implements java.io.Serializable {

	private String idSystem;
	private String name;
	private int chkLdap;
	private String comment;
	private int chkTokenLogin;
	private int chkAllUsers;
	private String sysUserFijo;
	private String sysPassFijo;
	private String parseChannel;
	private Set<VinParamsSystem> vinParamsSystems = new HashSet<VinParamsSystem>(
			0);
	private Set<VinUsersSystem> vinUsersSystems = new HashSet<VinUsersSystem>(0);
	private Set<VinNotifications> vinNotificationses = new HashSet<VinNotifications>(
			0);
	private Set<VinProcess> vinProcesses = new HashSet<VinProcess>(0);

	public VinSystems() {
	}

	public VinSystems(String idSystem, String name, int chkLdap,
			int chkTokenLogin, int chkAllUsers) {
		this.idSystem = idSystem;
		this.name = name;
		this.chkLdap = chkLdap;
		this.chkTokenLogin = chkTokenLogin;
		this.chkAllUsers = chkAllUsers;
	}

	public VinSystems(String idSystem, String name, int chkLdap,
			String comment, int chkTokenLogin, int chkAllUsers,
			String sysUserFijo, String sysPassFijo, String parseChannel,
			Set<VinParamsSystem> vinParamsSystems,
			Set<VinUsersSystem> vinUsersSystems,
			Set<VinNotifications> vinNotificationses,
			Set<VinProcess> vinProcesses) {
		this.idSystem = idSystem;
		this.name = name;
		this.chkLdap = chkLdap;
		this.comment = comment;
		this.chkTokenLogin = chkTokenLogin;
		this.chkAllUsers = chkAllUsers;
		this.sysUserFijo = sysUserFijo;
		this.sysPassFijo = sysPassFijo;
		this.parseChannel = parseChannel;
		this.vinParamsSystems = vinParamsSystems;
		this.vinUsersSystems = vinUsersSystems;
		this.vinNotificationses = vinNotificationses;
		this.vinProcesses = vinProcesses;
	}

	@Id
	@Column(name = "id_system", unique = true, nullable = false, length = 10)
	public String getIdSystem() {
		return this.idSystem;
	}

	public void setIdSystem(String idSystem) {
		this.idSystem = idSystem;
	}

	@Column(name = "name", nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "chk_ldap", nullable = false)
	public int getChkLdap() {
		return this.chkLdap;
	}

	public void setChkLdap(int chkLdap) {
		this.chkLdap = chkLdap;
	}

	@Column(name = "comment", length = 250)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "chk_token_login", nullable = false)
	public int getChkTokenLogin() {
		return this.chkTokenLogin;
	}

	public void setChkTokenLogin(int chkTokenLogin) {
		this.chkTokenLogin = chkTokenLogin;
	}

	@Column(name = "chk_all_users", nullable = false)
	public int getChkAllUsers() {
		return this.chkAllUsers;
	}

	public void setChkAllUsers(int chkAllUsers) {
		this.chkAllUsers = chkAllUsers;
	}

	@Column(name = "sys_user_fijo", length = 250)
	public String getSysUserFijo() {
		return this.sysUserFijo;
	}

	public void setSysUserFijo(String sysUserFijo) {
		this.sysUserFijo = sysUserFijo;
	}

	@Column(name = "sys_pass_fijo", length = 250)
	public String getSysPassFijo() {
		return this.sysPassFijo;
	}

	public void setSysPassFijo(String sysPassFijo) {
		this.sysPassFijo = sysPassFijo;
	}

	@Column(name = "parse_channel", length = 250)
	public String getParseChannel() {
		return this.parseChannel;
	}

	public void setParseChannel(String parseChannel) {
		this.parseChannel = parseChannel;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "vinSystems")
	public Set<VinParamsSystem> getVinParamsSystems() {
		return this.vinParamsSystems;
	}

	public void setVinParamsSystems(Set<VinParamsSystem> vinParamsSystems) {
		this.vinParamsSystems = vinParamsSystems;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "vinSystems")
	public Set<VinUsersSystem> getVinUsersSystems() {
		return this.vinUsersSystems;
	}

	public void setVinUsersSystems(Set<VinUsersSystem> vinUsersSystems) {
		this.vinUsersSystems = vinUsersSystems;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "vinSystems")
	public Set<VinNotifications> getVinNotificationses() {
		return this.vinNotificationses;
	}

	public void setVinNotificationses(Set<VinNotifications> vinNotificationses) {
		this.vinNotificationses = vinNotificationses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "vinSystems")
	public Set<VinProcess> getVinProcesses() {
		return this.vinProcesses;
	}

	public void setVinProcesses(Set<VinProcess> vinProcesses) {
		this.vinProcesses = vinProcesses;
	}

}
