package com.common.hibernate.entidades;

// Generated 26-ago-2014 10:48:56 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * VinUsers generated by hbm2java
 */
@Entity
@Table(name = "vin_users", catalog = "movilidad")
public class VinUsers implements java.io.Serializable {

	private String idUser;
	private VinRoles vinRoles;
	private VinDevices vinDevicesByIdDispLogin;
	private VinDevices vinDevicesByIdDispAccess;
	private String userName;
	private String nif;
	private String idEmpleadoRrhh;
	private String idOrganization;	
	private String faseAltaRrhh;
	private String password;
	private String comment;
	private String uuidAccess;
	private String uuidLogin;
	private int bloq;
	private int intentosLogin;
	private int visible;
	private Set<VinParamsUser> vinParamsUsers = new HashSet<VinParamsUser>(0);
	private Set<VinNotifications> vinNotificationses = new HashSet<VinNotifications>(
			0);
	private Set<VinUsersSystem> vinUsersSystems = new HashSet<VinUsersSystem>(0);

	public VinUsers() {
	}

	public VinUsers(String idUser, String userName, String password, int bloq,
			int intentosLogin, int visible) {
		this.idUser = idUser;
		this.userName = userName;
		this.password = password;
		this.bloq = bloq;
		this.intentosLogin = intentosLogin;
		this.visible = visible;
	}

	public VinUsers(String idUser, VinRoles vinRoles,
			VinDevices vinDevicesByIdDispLogin,
			VinDevices vinDevicesByIdDispAccess, String userName, String nif,
			String idEmpleadoRrhh, String faseAltaRrhh,String idOrganization, String password,
			String comment, String uuidAccess, String uuidLogin, int bloq,
			int intentosLogin, int visible, Set<VinParamsUser> vinParamsUsers,
			Set<VinNotifications> vinNotificationses,
			Set<VinUsersSystem> vinUsersSystems) {
		this.idUser = idUser;
		this.vinRoles = vinRoles;
		this.vinDevicesByIdDispLogin = vinDevicesByIdDispLogin;
		this.vinDevicesByIdDispAccess = vinDevicesByIdDispAccess;
		this.userName = userName;
		this.nif = nif;
		this.idEmpleadoRrhh = idEmpleadoRrhh;
		this.faseAltaRrhh = faseAltaRrhh;
		this.password = password;
		this.comment = comment;
		this.uuidAccess = uuidAccess;
		this.uuidLogin = uuidLogin;
		this.bloq = bloq;
		this.intentosLogin = intentosLogin;
		this.visible = visible;
		this.vinParamsUsers = vinParamsUsers;
		this.vinNotificationses = vinNotificationses;
		this.vinUsersSystems = vinUsersSystems;
		this.idOrganization = idOrganization;
	}

	@Id
	@Column(name = "id_user", unique = true, nullable = false, length = 200)
	public String getIdUser() {
		return this.idUser;
	}

	public void setIdUser(String idUser) {
		this.idUser = idUser;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_role")
	public VinRoles getVinRoles() {
		return this.vinRoles;
	}

	public void setVinRoles(VinRoles vinRoles) {
		this.vinRoles = vinRoles;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_disp_login")
	public VinDevices getVinDevicesByIdDispLogin() {
		return this.vinDevicesByIdDispLogin;
	}

	public void setVinDevicesByIdDispLogin(VinDevices vinDevicesByIdDispLogin) {
		this.vinDevicesByIdDispLogin = vinDevicesByIdDispLogin;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_disp_access")
	public VinDevices getVinDevicesByIdDispAccess() {
		return this.vinDevicesByIdDispAccess;
	}

	public void setVinDevicesByIdDispAccess(VinDevices vinDevicesByIdDispAccess) {
		this.vinDevicesByIdDispAccess = vinDevicesByIdDispAccess;
	}

	@Column(name = "user_name", nullable = false, length = 150)
	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	@Column(name = "nif", length = 20)
	public String getNif() {
		return this.nif;
	}

	public void setNif(String nif) {
		this.nif = nif;
	}

	@Column(name = "id_empleado_rrhh", length = 20)
	public String getIdEmpleadoRrhh() {
		return this.idEmpleadoRrhh;
	}

	public void setIdEmpleadoRrhh(String idEmpleadoRrhh) {
		this.idEmpleadoRrhh = idEmpleadoRrhh;
	}

	@Column(name = "fase_alta_rrhh", length = 20)
	public String getFaseAltaRrhh() {
		return this.faseAltaRrhh;
	}

	public void setFaseAltaRrhh(String faseAltaRrhh) {
		this.faseAltaRrhh = faseAltaRrhh;
	}
	@Column(name = "id_organization", length = 10)
	public String getIdOrganization() {
		return this.idOrganization;
	}

	public void setIdOrganization(String idOrganization) {
		this.idOrganization = idOrganization;
	}
	@Column(name = "password", nullable = false, length = 250)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "comment", length = 250)
	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	@Column(name = "uuid_access", length = 250)
	public String getUuidAccess() {
		return this.uuidAccess;
	}

	public void setUuidAccess(String uuidAccess) {
		this.uuidAccess = uuidAccess;
	}

	@Column(name = "uuid_login")
	public String getUuidLogin() {
		return this.uuidLogin;
	}

	public void setUuidLogin(String uuidLogin) {
		this.uuidLogin = uuidLogin;
	}

	@Column(name = "bloq", nullable = false)
	public int getBloq() {
		return this.bloq;
	}

	public void setBloq(int bloq) {
		this.bloq = bloq;
	}

	@Column(name = "intentos_login", nullable = false)
	public int getIntentosLogin() {
		return this.intentosLogin;
	}

	public void setIntentosLogin(int intentosLogin) {
		this.intentosLogin = intentosLogin;
	}

	@Column(name = "visible", nullable = false)
	public int getVisible() {
		return this.visible;
	}

	public void setVisible(int visible) {
		this.visible = visible;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "vinUsers")
	public Set<VinParamsUser> getVinParamsUsers() {
		return this.vinParamsUsers;
	}

	public void setVinParamsUsers(Set<VinParamsUser> vinParamsUsers) {
		this.vinParamsUsers = vinParamsUsers;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "vinUsers")
	public Set<VinNotifications> getVinNotificationses() {
		return this.vinNotificationses;
	}

	public void setVinNotificationses(Set<VinNotifications> vinNotificationses) {
		this.vinNotificationses = vinNotificationses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "vinUsers")
	public Set<VinUsersSystem> getVinUsersSystems() {
		
		return this.vinUsersSystems;
	}

	public void setVinUsersSystems(Set<VinUsersSystem> vinUsersSystems) {
		this.vinUsersSystems = vinUsersSystems;
	}
	
}
