package com.common.hibernate.entidades;

// Generated 26-ago-2014 10:48:56 by Hibernate Tools 3.4.0.CR1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * VinUsersView generated by hbm2java
 */
@Entity
@Table(name = "vin_users_view", catalog = "movilidad")
public class VinUsersView implements java.io.Serializable {

	private VinUsersViewId id;

	public VinUsersView() {
	}

	public VinUsersView(VinUsersViewId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idUser", column = @Column(name = "id_user", nullable = false, length = 200)),
			@AttributeOverride(name = "userName", column = @Column(name = "user_name", nullable = false, length = 150)),
			@AttributeOverride(name = "nif", column = @Column(name = "nif", length = 20)),
			@AttributeOverride(name = "idEmpleadoRrhh", column = @Column(name = "id_empleado_rrhh", length = 20)),
			@AttributeOverride(name = "faseAltaRrhh", column = @Column(name = "fase_alta_rrhh", length = 20)),
			@AttributeOverride(name = "comment", column = @Column(name = "comment", length = 250)),
			@AttributeOverride(name = "idRole", column = @Column(name = "id_role")),
			@AttributeOverride(name = "name", column = @Column(name = "name", length = 100)),
			@AttributeOverride(name = "uuidAccess", column = @Column(name = "uuid_access", length = 250)),
			@AttributeOverride(name = "idDispAccess", column = @Column(name = "id_disp_access", length = 50)),
			@AttributeOverride(name = "deviceName", column = @Column(name = "device_name", length = 100)),
			@AttributeOverride(name = "bloq", column = @Column(name = "bloq", nullable = false)),
			@AttributeOverride(name = "visible", column = @Column(name = "visible", nullable = false)) })
	public VinUsersViewId getId() {
		return this.id;
	}

	public void setId(VinUsersViewId id) {
		this.id = id;
	}

}
