package com.common.hibernate.entidades;

// Generated 26-ago-2014 10:48:56 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VinUsersSystem generated by hbm2java
 */
@Entity
@Table(name = "vin_users_system", catalog = "movilidad")
public class VinUsersSystem implements java.io.Serializable {

	private VinUsersSystemId id;
	private VinSystems vinSystems;
	private VinUsers vinUsers;
	private String tokenSystem;
	private Date dtCadToken;
	private String sysUser;
	private String sysPassword;
	private String idiomaSession;
	private String parseChannels;
	private String serverId;

	
	public VinUsersSystem() {
	}

	public VinUsersSystem(VinUsersSystemId id, VinSystems vinSystems,
			VinUsers vinUsers) {
		this.id = id;
		this.vinSystems = vinSystems;
		this.vinUsers = vinUsers;
	}

	public VinUsersSystem(VinUsersSystemId id, VinSystems vinSystems,
			VinUsers vinUsers, String tokenSystem, Date dtCadToken,
			String sysUser, String sysPassword, String idiomaSession,
			String parseChannels, String serverId) {
		this.id = id;
		this.vinSystems = vinSystems;
		this.vinUsers = vinUsers;
		this.tokenSystem = tokenSystem;
		this.dtCadToken = dtCadToken;
		this.sysUser = sysUser;
		this.sysPassword = sysPassword;
		this.idiomaSession = idiomaSession;
		this.parseChannels = parseChannels;
		this.serverId = serverId;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idUser", column = @Column(name = "id_user", nullable = false, length = 200)),
			@AttributeOverride(name = "idSystem", column = @Column(name = "id_system", nullable = false, length = 10)) })
	public VinUsersSystemId getId() {
		return this.id;
	}

	public void setId(VinUsersSystemId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_system", nullable = false, insertable = false, updatable = false)
	public VinSystems getVinSystems() {
		return this.vinSystems;
	}

	public void setVinSystems(VinSystems vinSystems) {
		this.vinSystems = vinSystems;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_user", nullable = false, insertable = false, updatable = false)
	public VinUsers getVinUsers() {
		return this.vinUsers;
	}

	public void setVinUsers(VinUsers vinUsers) {
		this.vinUsers = vinUsers;
	}

	@Column(name = "token_system")
	public String getTokenSystem() {
		return this.tokenSystem;
	}

	public void setTokenSystem(String tokenSystem) {
		this.tokenSystem = tokenSystem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_cad_token", length = 19)
	public Date getDtCadToken() {
		return this.dtCadToken;
	}

	public void setDtCadToken(Date dtCadToken) {
		this.dtCadToken = dtCadToken;
	}

	@Column(name = "sys_user", length = 250)
	public String getSysUser() {
		return this.sysUser;
	}

	public void setSysUser(String sysUser) {
		this.sysUser = sysUser;
	}

	@Column(name = "sys_password", length = 250)
	public String getSysPassword() {
		return this.sysPassword;
	}

	public void setSysPassword(String sysPassword) {
		this.sysPassword = sysPassword;
	}

	@Column(name = "idioma_session", length = 50)
	public String getIdiomaSession() {
		return this.idiomaSession;
	}

	public void setIdiomaSession(String idiomaSession) {
		this.idiomaSession = idiomaSession;
	}

	@Column(name = "parse_channels")
	public String getParseChannels() {
		return this.parseChannels;
	}

	public void setParseChannels(String parseChannels) {
		this.parseChannels = parseChannels;
	}
	
	@Column(name = "server_id")
	public String getServerId() {
		return serverId;
	}

	public void setServerId(String serverId) {
		this.serverId = serverId;
	}


}
