package com.common.hibernate.entidades.tinnova;
// Generated 12-abr-2016 16:30:08 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * M4cspMblRhFavId generated by hbm2java
 */
@Embeddable
public class M4cspMblRhFavId implements java.io.Serializable {

	private String idOrganization;
	private String stdIdPerson;
	private String stdIdPersonTarg;

	public M4cspMblRhFavId() {
	}

	public M4cspMblRhFavId(String idOrganization, String stdIdPerson, String stdIdPersonTarg) {
		this.idOrganization = idOrganization;
		this.stdIdPerson = stdIdPerson;
		this.stdIdPersonTarg = stdIdPersonTarg;
	}

	@Column(name = "ID_ORGANIZATION", nullable = false, length = 10)
	public String getIdOrganization() {
		return this.idOrganization;
	}

	public void setIdOrganization(String idOrganization) {
		this.idOrganization = idOrganization;
	}

	@Column(name = "STD_ID_PERSON", nullable = false, length = 20)
	public String getStdIdPerson() {
		return this.stdIdPerson;
	}

	public void setStdIdPerson(String stdIdPerson) {
		this.stdIdPerson = stdIdPerson;
	}

	@Column(name = "STD_ID_PERSON_TARG", nullable = false, length = 9)
	public String getStdIdPersonTarg() {
		return this.stdIdPersonTarg;
	}

	public void setStdIdPersonTarg(String stdIdPersonTarg) {
		this.stdIdPersonTarg = stdIdPersonTarg;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof M4cspMblRhFavId))
			return false;
		M4cspMblRhFavId castOther = (M4cspMblRhFavId) other;

		return ((this.getIdOrganization() == castOther.getIdOrganization())
				|| (this.getIdOrganization() != null && castOther.getIdOrganization() != null
						&& this.getIdOrganization().equals(castOther.getIdOrganization())))
				&& ((this.getStdIdPerson() == castOther.getStdIdPerson())
						|| (this.getStdIdPerson() != null && castOther.getStdIdPerson() != null
								&& this.getStdIdPerson().equals(castOther.getStdIdPerson())))
				&& ((this.getStdIdPersonTarg() == castOther.getStdIdPersonTarg())
						|| (this.getStdIdPersonTarg() != null && castOther.getStdIdPersonTarg() != null
								&& this.getStdIdPersonTarg().equals(castOther.getStdIdPersonTarg())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdOrganization() == null ? 0 : this.getIdOrganization().hashCode());
		result = 37 * result + (getStdIdPerson() == null ? 0 : this.getStdIdPerson().hashCode());
		result = 37 * result + (getStdIdPersonTarg() == null ? 0 : this.getStdIdPersonTarg().hashCode());
		return result;
	}

}
