package com.common.hibernate.entidades.tinnova;
// Generated 12-abr-2016 16:30:08 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * M4cspMblInfAbsId generated by hbm2java
 */
@Embeddable
public class M4cspMblInfAbsId implements java.io.Serializable {

	private String idOrganization;
	private String idEmpleado;
	private Date fechaAlta;
	private Date scoDtStart;

	public M4cspMblInfAbsId() {
	}

	public M4cspMblInfAbsId(String idOrganization, String idEmpleado, Date fechaAlta, Date scoDtStart) {
		this.idOrganization = idOrganization;
		this.idEmpleado = idEmpleado;
		this.fechaAlta = fechaAlta;
		this.scoDtStart = scoDtStart;
	}

	@Column(name = "ID_ORGANIZATION", nullable = false, length = 10)
	public String getIdOrganization() {
		return this.idOrganization;
	}

	public void setIdOrganization(String idOrganization) {
		this.idOrganization = idOrganization;
	}

	@Column(name = "ID_EMPLEADO", nullable = false, length = 20)
	public String getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado(String idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	@Column(name = "FECHA_ALTA", nullable = false, length = 23)
	public Date getFechaAlta() {
		return this.fechaAlta;
	}

	public void setFechaAlta(Date fechaAlta) {
		this.fechaAlta = fechaAlta;
	}

	@Column(name = "SCO_DT_START", nullable = false, length = 23)
	public Date getScoDtStart() {
		return this.scoDtStart;
	}

	public void setScoDtStart(Date scoDtStart) {
		this.scoDtStart = scoDtStart;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof M4cspMblInfAbsId))
			return false;
		M4cspMblInfAbsId castOther = (M4cspMblInfAbsId) other;

		return ((this.getIdOrganization() == castOther.getIdOrganization())
				|| (this.getIdOrganization() != null && castOther.getIdOrganization() != null
						&& this.getIdOrganization().equals(castOther.getIdOrganization())))
				&& ((this.getIdEmpleado() == castOther.getIdEmpleado()) || (this.getIdEmpleado() != null
						&& castOther.getIdEmpleado() != null && this.getIdEmpleado().equals(castOther.getIdEmpleado())))
				&& ((this.getFechaAlta() == castOther.getFechaAlta()) || (this.getFechaAlta() != null
						&& castOther.getFechaAlta() != null && this.getFechaAlta().equals(castOther.getFechaAlta())))
				&& ((this.getScoDtStart() == castOther.getScoDtStart())
						|| (this.getScoDtStart() != null && castOther.getScoDtStart() != null
								&& this.getScoDtStart().equals(castOther.getScoDtStart())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdOrganization() == null ? 0 : this.getIdOrganization().hashCode());
		result = 37 * result + (getIdEmpleado() == null ? 0 : this.getIdEmpleado().hashCode());
		result = 37 * result + (getFechaAlta() == null ? 0 : this.getFechaAlta().hashCode());
		result = 37 * result + (getScoDtStart() == null ? 0 : this.getScoDtStart().hashCode());
		return result;
	}

}
