package com.common.hibernate.entidades.tinnova;
// Generated 12-abr-2016 16:30:08 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4cspMblInfAbs generated by hbm2java
 */
@Entity
@Table(name = "M4CSP_MBL_INF_ABS", schema = "dbo", catalog = "EMIND")
public class M4cspMblInfAbs implements java.io.Serializable {

	private M4cspMblInfAbsId id;
	private String cspComentario;
	private String idTipoAbsentismo;
	private Date scoDtEnd;
	private String cspIdEstado;

	public M4cspMblInfAbs() {
	}

	public M4cspMblInfAbs(M4cspMblInfAbsId id) {
		this.id = id;
	}

	public M4cspMblInfAbs(M4cspMblInfAbsId id, String cspComentario, String idTipoAbsentismo, Date scoDtEnd,
			String cspIdEstado) {
		this.id = id;
		this.cspComentario = cspComentario;
		this.idTipoAbsentismo = idTipoAbsentismo;
		this.scoDtEnd = scoDtEnd;
		this.cspIdEstado = cspIdEstado;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idOrganization", column = @Column(name = "ID_ORGANIZATION", nullable = false, length = 10) ),
			@AttributeOverride(name = "idEmpleado", column = @Column(name = "ID_EMPLEADO", nullable = false, length = 20) ),
			@AttributeOverride(name = "fechaAlta", column = @Column(name = "FECHA_ALTA", nullable = false, length = 23) ),
			@AttributeOverride(name = "scoDtStart", column = @Column(name = "SCO_DT_START", nullable = false, length = 23) ) })
	public M4cspMblInfAbsId getId() {
		return this.id;
	}

	public void setId(M4cspMblInfAbsId id) {
		this.id = id;
	}

	@Column(name = "CSP_COMENTARIO", length = 254)
	public String getCspComentario() {
		return this.cspComentario;
	}

	public void setCspComentario(String cspComentario) {
		this.cspComentario = cspComentario;
	}

	@Column(name = "ID_TIPO_ABSENTISMO", length = 10)
	public String getIdTipoAbsentismo() {
		return this.idTipoAbsentismo;
	}

	public void setIdTipoAbsentismo(String idTipoAbsentismo) {
		this.idTipoAbsentismo = idTipoAbsentismo;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SCO_DT_END", length = 23)
	public Date getScoDtEnd() {
		return this.scoDtEnd;
	}

	public void setScoDtEnd(Date scoDtEnd) {
		this.scoDtEnd = scoDtEnd;
	}

	@Column(name = "CSP_ID_ESTADO", length = 5)
	public String getCspIdEstado() {
		return this.cspIdEstado;
	}

	public void setCspIdEstado(String cspIdEstado) {
		this.cspIdEstado = cspIdEstado;
	}

}
