package com.common.hibernate.entidades.tinnova;
// Generated 12-abr-2016 16:30:08 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4cspMobileNotif generated by hbm2java
 */
@Entity
@Table(name = "M4CSP_MOBILE_NOTIF", schema = "dbo", catalog = "EMIND")
public class M4cspMobileNotif implements java.io.Serializable {

	private M4cspMobileNotifId id;
	private String cspMensaje;
	private Date cspDtCaducidad;
	private String cspChkRecibido;
	private String cspDescripcion;
	private Date cspDtEnvio;
	private String cspChkDelMobile;

	public M4cspMobileNotif() {
	}

	public M4cspMobileNotif(M4cspMobileNotifId id) {
		this.id = id;
	}

	public M4cspMobileNotif(M4cspMobileNotifId id, String cspMensaje, Date cspDtCaducidad, String cspChkRecibido,
			String cspDescripcion, Date cspDtEnvio, String cspChkDelMobile) {
		this.id = id;
		this.cspMensaje = cspMensaje;
		this.cspDtCaducidad = cspDtCaducidad;
		this.cspChkRecibido = cspChkRecibido;
		this.cspDescripcion = cspDescripcion;
		this.cspDtEnvio = cspDtEnvio;
		this.cspChkDelMobile = cspChkDelMobile;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idOrganization", column = @Column(name = "ID_ORGANIZATION", nullable = false, length = 10) ),
			@AttributeOverride(name = "stdIdPerson", column = @Column(name = "STD_ID_PERSON", nullable = false, length = 20) ),
			@AttributeOverride(name = "cspOrdinal", column = @Column(name = "CSP_ORDINAL", nullable = false, precision = 9, scale = 0) ) })
	public M4cspMobileNotifId getId() {
		return this.id;
	}

	public void setId(M4cspMobileNotifId id) {
		this.id = id;
	}

	@Column(name = "CSP_MENSAJE")
	public String getCspMensaje() {
		return this.cspMensaje;
	}

	public void setCspMensaje(String cspMensaje) {
		this.cspMensaje = cspMensaje;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CSP_DT_CADUCIDAD", length = 23)
	public Date getCspDtCaducidad() {
		return this.cspDtCaducidad;
	}

	public void setCspDtCaducidad(Date cspDtCaducidad) {
		this.cspDtCaducidad = cspDtCaducidad;
	}

	@Column(name = "CSP_CHK_RECIBIDO", length = 1)
	public String getCspChkRecibido() {
		return this.cspChkRecibido;
	}

	public void setCspChkRecibido(String cspChkRecibido) {
		this.cspChkRecibido = cspChkRecibido;
	}

	@Column(name = "CSP_DESCRIPCION")
	public String getCspDescripcion() {
		return this.cspDescripcion;
	}

	public void setCspDescripcion(String cspDescripcion) {
		this.cspDescripcion = cspDescripcion;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "CSP_DT_ENVIO", length = 23)
	public Date getCspDtEnvio() {
		return this.cspDtEnvio;
	}

	public void setCspDtEnvio(Date cspDtEnvio) {
		this.cspDtEnvio = cspDtEnvio;
	}

	@Column(name = "CSP_CHK_DEL_MOBILE", length = 1)
	public String getCspChkDelMobile() {
		return this.cspChkDelMobile;
	}

	public void setCspChkDelMobile(String cspChkDelMobile) {
		this.cspChkDelMobile = cspChkDelMobile;
	}

}
