package com.common.hibernate.entidades.tinnova;
// Generated 12-abr-2016 16:30:08 by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * M4cspMblRhFav generated by hbm2java
 */
@Entity
@Table(name = "M4CSP_MBL_RH_FAV", schema = "dbo", catalog = "EMIND")
public class M4cspMblRhFav implements java.io.Serializable {

	private M4cspMblRhFavId id;
	private String cspDescripcion;

	public M4cspMblRhFav() {
	}

	public M4cspMblRhFav(M4cspMblRhFavId id) {
		this.id = id;
	}

	public M4cspMblRhFav(M4cspMblRhFavId id, String cspDescripcion) {
		this.id = id;
		this.cspDescripcion = cspDescripcion;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idOrganization", column = @Column(name = "ID_ORGANIZATION", nullable = false, length = 10) ),
			@AttributeOverride(name = "stdIdPerson", column = @Column(name = "STD_ID_PERSON", nullable = false, length = 20) ),
			@AttributeOverride(name = "stdIdPersonTarg", column = @Column(name = "STD_ID_PERSON_TARG", nullable = false, length = 9) ) })
	public M4cspMblRhFavId getId() {
		return this.id;
	}

	public void setId(M4cspMblRhFavId id) {
		this.id = id;
	}

	@Column(name = "CSP_DESCRIPCION")
	public String getCspDescripcion() {
		return this.cspDescripcion;
	}

	public void setCspDescripcion(String cspDescripcion) {
		this.cspDescripcion = cspDescripcion;
	}

}
