package com.common.hibernate.entidades.tinnova;
// Generated 12-abr-2016 16:30:08 by Hibernate Tools 3.5.0.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * M4Empleados generated by hbm2java
 */
@Entity
@Table(name = "M4_EMPLEADOS", schema = "dbo", catalog = "EMIND")
public class M4Empleados implements java.io.Serializable {

	private M4EmpleadosId id;

	public M4Empleados() {
	}

	public M4Empleados(M4EmpleadosId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idSociedad", column = @Column(name = "ID_SOCIEDAD", nullable = false, length = 2) ),
			@AttributeOverride(name = "idEmpleado", column = @Column(name = "ID_EMPLEADO", nullable = false, length = 10) ),
			@AttributeOverride(name = "nombre", column = @Column(name = "NOMBRE", nullable = false, length = 17) ),
			@AttributeOverride(name = "apellido1", column = @Column(name = "APELLIDO_1", nullable = false, length = 20) ),
			@AttributeOverride(name = "apellido2", column = @Column(name = "APELLIDO_2", length = 20) ),
			@AttributeOverride(name = "numPasaporte", column = @Column(name = "NUM_PASAPORTE", length = 20) ),
			@AttributeOverride(name = "numAfiliacionSs", column = @Column(name = "NUM_AFILIACION_SS", length = 12) ),
			@AttributeOverride(name = "fecNacimiento", column = @Column(name = "FEC_NACIMIENTO", length = 23) ),
			@AttributeOverride(name = "poblacNacimiento", column = @Column(name = "POBLAC_NACIMIENTO", length = 25) ),
			@AttributeOverride(name = "coment", column = @Column(name = "COMENT") ),
			@AttributeOverride(name = "nivelSeguridad", column = @Column(name = "NIVEL_SEGURIDAD", precision = 2, scale = 0) ),
			@AttributeOverride(name = "fecUltActualizac", column = @Column(name = "FEC_ULT_ACTUALIZAC", length = 23) ),
			@AttributeOverride(name = "idUsuario", column = @Column(name = "ID_USUARIO", length = 40) ),
			@AttributeOverride(name = "idLegal", column = @Column(name = "ID_LEGAL", nullable = false, length = 10) ),
			@AttributeOverride(name = "idNacion", column = @Column(name = "ID_NACION", nullable = false, length = 3) ),
			@AttributeOverride(name = "idSexo", column = @Column(name = "ID_SEXO", nullable = false, length = 1) ),
			@AttributeOverride(name = "idEstadoCivil", column = @Column(name = "ID_ESTADO_CIVIL", nullable = false, length = 1) ),
			@AttributeOverride(name = "idNacionalidad", column = @Column(name = "ID_NACIONALIDAD", nullable = false, length = 3) ),
			@AttributeOverride(name = "idAgrupSeguridad", column = @Column(name = "ID_AGRUP_SEGURIDAD", nullable = false, length = 10) ),
			@AttributeOverride(name = "idSubdivNacimien", column = @Column(name = "ID_SUBDIV_NACIMIEN", nullable = false, precision = 2, scale = 0) ),
			@AttributeOverride(name = "idTipIdLegalSt", column = @Column(name = "ID_TIP_ID_LEGAL_ST", nullable = false, length = 1) ),
			@AttributeOverride(name = "idLegalRepSt", column = @Column(name = "ID_LEGAL_REP_ST", length = 10) ),
			@AttributeOverride(name = "paisEmisorSt", column = @Column(name = "PAIS_EMISOR_ST", length = 3) ),
			@AttributeOverride(name = "cancelDatPer", column = @Column(name = "CANCEL_DAT_PER", nullable = false, length = 1) ) })
	public M4EmpleadosId getId() {
		return this.id;
	}

	public void setId(M4EmpleadosId id) {
		this.id = id;
	}

}
