package com.common.hibernate.entidades.tinnova;
// Generated 12-abr-2016 16:30:08 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * M4EmpleadosId generated by hbm2java
 */
@Embeddable
public class M4EmpleadosId implements java.io.Serializable {

	private String idSociedad;
	private String idEmpleado;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private String numPasaporte;
	private String numAfiliacionSs;
	private Date fecNacimiento;
	private String poblacNacimiento;
	private String coment;
	private Byte nivelSeguridad;
	private Date fecUltActualizac;
	private String idUsuario;
	private String idLegal;
	private String idNacion;
	private char idSexo;
	private char idEstadoCivil;
	private String idNacionalidad;
	private String idAgrupSeguridad;
	private byte idSubdivNacimien;
	private char idTipIdLegalSt;
	private String idLegalRepSt;
	private String paisEmisorSt;
	private String cancelDatPer;

	public M4EmpleadosId() {
	}

	public M4EmpleadosId(String idSociedad, String idEmpleado, String nombre, String apellido1, String idLegal,
			String idNacion, char idSexo, char idEstadoCivil, String idNacionalidad, String idAgrupSeguridad,
			byte idSubdivNacimien, char idTipIdLegalSt, String cancelDatPer) {
		this.idSociedad = idSociedad;
		this.idEmpleado = idEmpleado;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.idLegal = idLegal;
		this.idNacion = idNacion;
		this.idSexo = idSexo;
		this.idEstadoCivil = idEstadoCivil;
		this.idNacionalidad = idNacionalidad;
		this.idAgrupSeguridad = idAgrupSeguridad;
		this.idSubdivNacimien = idSubdivNacimien;
		this.idTipIdLegalSt = idTipIdLegalSt;
		this.cancelDatPer = cancelDatPer;
	}

	public M4EmpleadosId(String idSociedad, String idEmpleado, String nombre, String apellido1, String apellido2,
			String numPasaporte, String numAfiliacionSs, Date fecNacimiento, String poblacNacimiento, String coment,
			Byte nivelSeguridad, Date fecUltActualizac, String idUsuario, String idLegal, String idNacion, char idSexo,
			char idEstadoCivil, String idNacionalidad, String idAgrupSeguridad, byte idSubdivNacimien,
			char idTipIdLegalSt, String idLegalRepSt, String paisEmisorSt, String cancelDatPer) {
		this.idSociedad = idSociedad;
		this.idEmpleado = idEmpleado;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.numPasaporte = numPasaporte;
		this.numAfiliacionSs = numAfiliacionSs;
		this.fecNacimiento = fecNacimiento;
		this.poblacNacimiento = poblacNacimiento;
		this.coment = coment;
		this.nivelSeguridad = nivelSeguridad;
		this.fecUltActualizac = fecUltActualizac;
		this.idUsuario = idUsuario;
		this.idLegal = idLegal;
		this.idNacion = idNacion;
		this.idSexo = idSexo;
		this.idEstadoCivil = idEstadoCivil;
		this.idNacionalidad = idNacionalidad;
		this.idAgrupSeguridad = idAgrupSeguridad;
		this.idSubdivNacimien = idSubdivNacimien;
		this.idTipIdLegalSt = idTipIdLegalSt;
		this.idLegalRepSt = idLegalRepSt;
		this.paisEmisorSt = paisEmisorSt;
		this.cancelDatPer = cancelDatPer;
	}

	@Column(name = "ID_SOCIEDAD", nullable = false, length = 2)
	public String getIdSociedad() {
		return this.idSociedad;
	}

	public void setIdSociedad(String idSociedad) {
		this.idSociedad = idSociedad;
	}

	@Column(name = "ID_EMPLEADO", nullable = false, length = 10)
	public String getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado(String idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	@Column(name = "NOMBRE", nullable = false, length = 17)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "APELLIDO_1", nullable = false, length = 20)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "APELLIDO_2", length = 20)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Column(name = "NUM_PASAPORTE", length = 20)
	public String getNumPasaporte() {
		return this.numPasaporte;
	}

	public void setNumPasaporte(String numPasaporte) {
		this.numPasaporte = numPasaporte;
	}

	@Column(name = "NUM_AFILIACION_SS", length = 12)
	public String getNumAfiliacionSs() {
		return this.numAfiliacionSs;
	}

	public void setNumAfiliacionSs(String numAfiliacionSs) {
		this.numAfiliacionSs = numAfiliacionSs;
	}

	@Column(name = "FEC_NACIMIENTO", length = 23)
	public Date getFecNacimiento() {
		return this.fecNacimiento;
	}

	public void setFecNacimiento(Date fecNacimiento) {
		this.fecNacimiento = fecNacimiento;
	}

	@Column(name = "POBLAC_NACIMIENTO", length = 25)
	public String getPoblacNacimiento() {
		return this.poblacNacimiento;
	}

	public void setPoblacNacimiento(String poblacNacimiento) {
		this.poblacNacimiento = poblacNacimiento;
	}

	@Column(name = "COMENT")
	public String getComent() {
		return this.coment;
	}

	public void setComent(String coment) {
		this.coment = coment;
	}

	@Column(name = "NIVEL_SEGURIDAD", precision = 2, scale = 0)
	public Byte getNivelSeguridad() {
		return this.nivelSeguridad;
	}

	public void setNivelSeguridad(Byte nivelSeguridad) {
		this.nivelSeguridad = nivelSeguridad;
	}

	@Column(name = "FEC_ULT_ACTUALIZAC", length = 23)
	public Date getFecUltActualizac() {
		return this.fecUltActualizac;
	}

	public void setFecUltActualizac(Date fecUltActualizac) {
		this.fecUltActualizac = fecUltActualizac;
	}

	@Column(name = "ID_USUARIO", length = 40)
	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "ID_LEGAL", nullable = false, length = 10)
	public String getIdLegal() {
		return this.idLegal;
	}

	public void setIdLegal(String idLegal) {
		this.idLegal = idLegal;
	}

	@Column(name = "ID_NACION", nullable = false, length = 3)
	public String getIdNacion() {
		return this.idNacion;
	}

	public void setIdNacion(String idNacion) {
		this.idNacion = idNacion;
	}

	@Column(name = "ID_SEXO", nullable = false, length = 1)
	public char getIdSexo() {
		return this.idSexo;
	}

	public void setIdSexo(char idSexo) {
		this.idSexo = idSexo;
	}

	@Column(name = "ID_ESTADO_CIVIL", nullable = false, length = 1)
	public char getIdEstadoCivil() {
		return this.idEstadoCivil;
	}

	public void setIdEstadoCivil(char idEstadoCivil) {
		this.idEstadoCivil = idEstadoCivil;
	}

	@Column(name = "ID_NACIONALIDAD", nullable = false, length = 3)
	public String getIdNacionalidad() {
		return this.idNacionalidad;
	}

	public void setIdNacionalidad(String idNacionalidad) {
		this.idNacionalidad = idNacionalidad;
	}

	@Column(name = "ID_AGRUP_SEGURIDAD", nullable = false, length = 10)
	public String getIdAgrupSeguridad() {
		return this.idAgrupSeguridad;
	}

	public void setIdAgrupSeguridad(String idAgrupSeguridad) {
		this.idAgrupSeguridad = idAgrupSeguridad;
	}

	@Column(name = "ID_SUBDIV_NACIMIEN", nullable = false, precision = 2, scale = 0)
	public byte getIdSubdivNacimien() {
		return this.idSubdivNacimien;
	}

	public void setIdSubdivNacimien(byte idSubdivNacimien) {
		this.idSubdivNacimien = idSubdivNacimien;
	}

	@Column(name = "ID_TIP_ID_LEGAL_ST", nullable = false, length = 1)
	public char getIdTipIdLegalSt() {
		return this.idTipIdLegalSt;
	}

	public void setIdTipIdLegalSt(char idTipIdLegalSt) {
		this.idTipIdLegalSt = idTipIdLegalSt;
	}

	@Column(name = "ID_LEGAL_REP_ST", length = 10)
	public String getIdLegalRepSt() {
		return this.idLegalRepSt;
	}

	public void setIdLegalRepSt(String idLegalRepSt) {
		this.idLegalRepSt = idLegalRepSt;
	}

	@Column(name = "PAIS_EMISOR_ST", length = 3)
	public String getPaisEmisorSt() {
		return this.paisEmisorSt;
	}

	public void setPaisEmisorSt(String paisEmisorSt) {
		this.paisEmisorSt = paisEmisorSt;
	}

	@Column(name = "CANCEL_DAT_PER", nullable = false, length = 1)
	public String getCancelDatPer() {
		return this.cancelDatPer;
	}

	public void setCancelDatPer(String cancelDatPer) {
		this.cancelDatPer = cancelDatPer;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof M4EmpleadosId))
			return false;
		M4EmpleadosId castOther = (M4EmpleadosId) other;

		return ((this.getIdSociedad() == castOther.getIdSociedad()) || (this.getIdSociedad() != null
				&& castOther.getIdSociedad() != null && this.getIdSociedad().equals(castOther.getIdSociedad())))
				&& ((this.getIdEmpleado() == castOther.getIdEmpleado()) || (this.getIdEmpleado() != null
						&& castOther.getIdEmpleado() != null && this.getIdEmpleado().equals(castOther.getIdEmpleado())))
				&& ((this.getNombre() == castOther.getNombre()) || (this.getNombre() != null
						&& castOther.getNombre() != null && this.getNombre().equals(castOther.getNombre())))
				&& ((this.getApellido1() == castOther.getApellido1()) || (this.getApellido1() != null
						&& castOther.getApellido1() != null && this.getApellido1().equals(castOther.getApellido1())))
				&& ((this.getApellido2() == castOther.getApellido2()) || (this.getApellido2() != null
						&& castOther.getApellido2() != null && this.getApellido2().equals(castOther.getApellido2())))
				&& ((this.getNumPasaporte() == castOther.getNumPasaporte())
						|| (this.getNumPasaporte() != null && castOther.getNumPasaporte() != null
								&& this.getNumPasaporte().equals(castOther.getNumPasaporte())))
				&& ((this.getNumAfiliacionSs() == castOther.getNumAfiliacionSs())
						|| (this.getNumAfiliacionSs() != null && castOther.getNumAfiliacionSs() != null
								&& this.getNumAfiliacionSs().equals(castOther.getNumAfiliacionSs())))
				&& ((this.getFecNacimiento() == castOther.getFecNacimiento())
						|| (this.getFecNacimiento() != null && castOther.getFecNacimiento() != null
								&& this.getFecNacimiento().equals(castOther.getFecNacimiento())))
				&& ((this.getPoblacNacimiento() == castOther.getPoblacNacimiento())
						|| (this.getPoblacNacimiento() != null && castOther.getPoblacNacimiento() != null
								&& this.getPoblacNacimiento().equals(castOther.getPoblacNacimiento())))
				&& ((this.getComent() == castOther.getComent()) || (this.getComent() != null
						&& castOther.getComent() != null && this.getComent().equals(castOther.getComent())))
				&& ((this.getNivelSeguridad() == castOther.getNivelSeguridad())
						|| (this.getNivelSeguridad() != null && castOther.getNivelSeguridad() != null
								&& this.getNivelSeguridad().equals(castOther.getNivelSeguridad())))
				&& ((this.getFecUltActualizac() == castOther.getFecUltActualizac())
						|| (this.getFecUltActualizac() != null && castOther.getFecUltActualizac() != null
								&& this.getFecUltActualizac().equals(castOther.getFecUltActualizac())))
				&& ((this.getIdUsuario() == castOther.getIdUsuario()) || (this.getIdUsuario() != null
						&& castOther.getIdUsuario() != null && this.getIdUsuario().equals(castOther.getIdUsuario())))
				&& ((this.getIdLegal() == castOther.getIdLegal()) || (this.getIdLegal() != null
						&& castOther.getIdLegal() != null && this.getIdLegal().equals(castOther.getIdLegal())))
				&& ((this.getIdNacion() == castOther.getIdNacion()) || (this.getIdNacion() != null
						&& castOther.getIdNacion() != null && this.getIdNacion().equals(castOther.getIdNacion())))
				&& (this.getIdSexo() == castOther.getIdSexo())
				&& (this.getIdEstadoCivil() == castOther.getIdEstadoCivil())
				&& ((this.getIdNacionalidad() == castOther.getIdNacionalidad())
						|| (this.getIdNacionalidad() != null && castOther.getIdNacionalidad() != null
								&& this.getIdNacionalidad().equals(castOther.getIdNacionalidad())))
				&& ((this.getIdAgrupSeguridad() == castOther.getIdAgrupSeguridad())
						|| (this.getIdAgrupSeguridad() != null && castOther.getIdAgrupSeguridad() != null
								&& this.getIdAgrupSeguridad().equals(castOther.getIdAgrupSeguridad())))
				&& (this.getIdSubdivNacimien() == castOther.getIdSubdivNacimien())
				&& (this.getIdTipIdLegalSt() == castOther.getIdTipIdLegalSt())
				&& ((this.getIdLegalRepSt() == castOther.getIdLegalRepSt())
						|| (this.getIdLegalRepSt() != null && castOther.getIdLegalRepSt() != null
								&& this.getIdLegalRepSt().equals(castOther.getIdLegalRepSt())))
				&& ((this.getPaisEmisorSt() == castOther.getPaisEmisorSt())
						|| (this.getPaisEmisorSt() != null && castOther.getPaisEmisorSt() != null
								&& this.getPaisEmisorSt().equals(castOther.getPaisEmisorSt())))
				&& ((this.getCancelDatPer() == castOther.getCancelDatPer())
						|| (this.getCancelDatPer() != null && castOther.getCancelDatPer() != null
								&& this.getCancelDatPer().equals(castOther.getCancelDatPer())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdSociedad() == null ? 0 : this.getIdSociedad().hashCode());
		result = 37 * result + (getIdEmpleado() == null ? 0 : this.getIdEmpleado().hashCode());
		result = 37 * result + (getNombre() == null ? 0 : this.getNombre().hashCode());
		result = 37 * result + (getApellido1() == null ? 0 : this.getApellido1().hashCode());
		result = 37 * result + (getApellido2() == null ? 0 : this.getApellido2().hashCode());
		result = 37 * result + (getNumPasaporte() == null ? 0 : this.getNumPasaporte().hashCode());
		result = 37 * result + (getNumAfiliacionSs() == null ? 0 : this.getNumAfiliacionSs().hashCode());
		result = 37 * result + (getFecNacimiento() == null ? 0 : this.getFecNacimiento().hashCode());
		result = 37 * result + (getPoblacNacimiento() == null ? 0 : this.getPoblacNacimiento().hashCode());
		result = 37 * result + (getComent() == null ? 0 : this.getComent().hashCode());
		result = 37 * result + (getNivelSeguridad() == null ? 0 : this.getNivelSeguridad().hashCode());
		result = 37 * result + (getFecUltActualizac() == null ? 0 : this.getFecUltActualizac().hashCode());
		result = 37 * result + (getIdUsuario() == null ? 0 : this.getIdUsuario().hashCode());
		result = 37 * result + (getIdLegal() == null ? 0 : this.getIdLegal().hashCode());
		result = 37 * result + (getIdNacion() == null ? 0 : this.getIdNacion().hashCode());
		result = 37 * result + this.getIdSexo();
		result = 37 * result + this.getIdEstadoCivil();
		result = 37 * result + (getIdNacionalidad() == null ? 0 : this.getIdNacionalidad().hashCode());
		result = 37 * result + (getIdAgrupSeguridad() == null ? 0 : this.getIdAgrupSeguridad().hashCode());
		result = 37 * result + this.getIdSubdivNacimien();
		result = 37 * result + this.getIdTipIdLegalSt();
		result = 37 * result + (getIdLegalRepSt() == null ? 0 : this.getIdLegalRepSt().hashCode());
		result = 37 * result + (getPaisEmisorSt() == null ? 0 : this.getPaisEmisorSt().hashCode());
		result = 37 * result + (getCancelDatPer() == null ? 0 : this.getCancelDatPer().hashCode());
		return result;
	}

}
