package com.common.hibernate.entidades.tinnova;
// Generated 12-abr-2016 16:30:08 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * M4sysPReciboStId generated by hbm2java
 */
@Embeddable
public class M4sysPReciboStId implements java.io.Serializable {

	private String idSociedad;
	private String idEmpleado;
	private Date fecAltaEmpleado;
	private Date fecPaga;
	private Date fecImputacion;
	private boolean tipoRecibo;

	public M4sysPReciboStId() {
	}

	public M4sysPReciboStId(String idSociedad, String idEmpleado, Date fecAltaEmpleado, Date fecPaga,
			Date fecImputacion, boolean tipoRecibo) {
		this.idSociedad = idSociedad;
		this.idEmpleado = idEmpleado;
		this.fecAltaEmpleado = fecAltaEmpleado;
		this.fecPaga = fecPaga;
		this.fecImputacion = fecImputacion;
		this.tipoRecibo = tipoRecibo;
	}

	@Column(name = "ID_SOCIEDAD", nullable = false, length = 2)
	public String getIdSociedad() {
		return this.idSociedad;
	}

	public void setIdSociedad(String idSociedad) {
		this.idSociedad = idSociedad;
	}

	@Column(name = "ID_EMPLEADO", nullable = false, length = 10)
	public String getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado(String idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	@Column(name = "FEC_ALTA_EMPLEADO", nullable = false, length = 23)
	public Date getFecAltaEmpleado() {
		return this.fecAltaEmpleado;
	}

	public void setFecAltaEmpleado(Date fecAltaEmpleado) {
		this.fecAltaEmpleado = fecAltaEmpleado;
	}

	@Column(name = "FEC_PAGA", nullable = false, length = 23)
	public Date getFecPaga() {
		return this.fecPaga;
	}

	public void setFecPaga(Date fecPaga) {
		this.fecPaga = fecPaga;
	}

	@Column(name = "FEC_IMPUTACION", nullable = false, length = 23)
	public Date getFecImputacion() {
		return this.fecImputacion;
	}

	public void setFecImputacion(Date fecImputacion) {
		this.fecImputacion = fecImputacion;
	}

	@Column(name = "TIPO_RECIBO", nullable = false, precision = 1, scale = 0)
	public boolean isTipoRecibo() {
		return this.tipoRecibo;
	}

	public void setTipoRecibo(boolean tipoRecibo) {
		this.tipoRecibo = tipoRecibo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof M4sysPReciboStId))
			return false;
		M4sysPReciboStId castOther = (M4sysPReciboStId) other;

		return ((this.getIdSociedad() == castOther.getIdSociedad()) || (this.getIdSociedad() != null
				&& castOther.getIdSociedad() != null && this.getIdSociedad().equals(castOther.getIdSociedad())))
				&& ((this.getIdEmpleado() == castOther.getIdEmpleado()) || (this.getIdEmpleado() != null
						&& castOther.getIdEmpleado() != null && this.getIdEmpleado().equals(castOther.getIdEmpleado())))
				&& ((this.getFecAltaEmpleado() == castOther.getFecAltaEmpleado())
						|| (this.getFecAltaEmpleado() != null && castOther.getFecAltaEmpleado() != null
								&& this.getFecAltaEmpleado().equals(castOther.getFecAltaEmpleado())))
				&& ((this.getFecPaga() == castOther.getFecPaga()) || (this.getFecPaga() != null
						&& castOther.getFecPaga() != null && this.getFecPaga().equals(castOther.getFecPaga())))
				&& ((this.getFecImputacion() == castOther.getFecImputacion())
						|| (this.getFecImputacion() != null && castOther.getFecImputacion() != null
								&& this.getFecImputacion().equals(castOther.getFecImputacion())))
				&& (this.isTipoRecibo() == castOther.isTipoRecibo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdSociedad() == null ? 0 : this.getIdSociedad().hashCode());
		result = 37 * result + (getIdEmpleado() == null ? 0 : this.getIdEmpleado().hashCode());
		result = 37 * result + (getFecAltaEmpleado() == null ? 0 : this.getFecAltaEmpleado().hashCode());
		result = 37 * result + (getFecPaga() == null ? 0 : this.getFecPaga().hashCode());
		result = 37 * result + (getFecImputacion() == null ? 0 : this.getFecImputacion().hashCode());
		result = 37 * result + (this.isTipoRecibo() ? 1 : 0);
		return result;
	}

}
