package com.common.hibernate.entidades.tinnova;
// Generated 12-abr-2016 16:30:08 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4sysPReciboSt generated by hbm2java
 */
@Entity
@Table(name = "M4SYS_P_RECIBO_ST", schema = "dbo", catalog = "EMIND")
public class M4sysPReciboSt implements java.io.Serializable {

	private M4sysPReciboStId id;
	private String path;
	private int numFichero;
	private String idUsuario;
	private Date fecUltActualizac;
	private String coment;
	private String html;
	private String pathPdf;
	private byte[] pdf;

	public M4sysPReciboSt() {
	}

	public M4sysPReciboSt(M4sysPReciboStId id, String path, int numFichero) {
		this.id = id;
		this.path = path;
		this.numFichero = numFichero;
	}

	public M4sysPReciboSt(M4sysPReciboStId id, String path, int numFichero, String idUsuario, Date fecUltActualizac,
			String coment, String html, String pathPdf, byte[] pdf) {
		this.id = id;
		this.path = path;
		this.numFichero = numFichero;
		this.idUsuario = idUsuario;
		this.fecUltActualizac = fecUltActualizac;
		this.coment = coment;
		this.html = html;
		this.pathPdf = pathPdf;
		this.pdf = pdf;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idSociedad", column = @Column(name = "ID_SOCIEDAD", nullable = false, length = 2) ),
			@AttributeOverride(name = "idEmpleado", column = @Column(name = "ID_EMPLEADO", nullable = false, length = 10) ),
			@AttributeOverride(name = "fecAltaEmpleado", column = @Column(name = "FEC_ALTA_EMPLEADO", nullable = false, length = 23) ),
			@AttributeOverride(name = "fecPaga", column = @Column(name = "FEC_PAGA", nullable = false, length = 23) ),
			@AttributeOverride(name = "fecImputacion", column = @Column(name = "FEC_IMPUTACION", nullable = false, length = 23) ),
			@AttributeOverride(name = "tipoRecibo", column = @Column(name = "TIPO_RECIBO", nullable = false, precision = 1, scale = 0) ) })
	public M4sysPReciboStId getId() {
		return this.id;
	}

	public void setId(M4sysPReciboStId id) {
		this.id = id;
	}

	@Column(name = "PATH", nullable = false)
	public String getPath() {
		return this.path;
	}

	public void setPath(String path) {
		this.path = path;
	}

	@Column(name = "NUM_FICHERO", nullable = false, precision = 8, scale = 0)
	public int getNumFichero() {
		return this.numFichero;
	}

	public void setNumFichero(int numFichero) {
		this.numFichero = numFichero;
	}

	@Column(name = "ID_USUARIO", length = 40)
	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_ULT_ACTUALIZAC", length = 23)
	public Date getFecUltActualizac() {
		return this.fecUltActualizac;
	}

	public void setFecUltActualizac(Date fecUltActualizac) {
		this.fecUltActualizac = fecUltActualizac;
	}

	@Column(name = "COMENT")
	public String getComent() {
		return this.coment;
	}

	public void setComent(String coment) {
		this.coment = coment;
	}

	@Column(name = "HTML")
	public String getHtml() {
		return this.html;
	}

	public void setHtml(String html) {
		this.html = html;
	}

	@Column(name = "PATH_PDF")
	public String getPathPdf() {
		return this.pathPdf;
	}

	public void setPathPdf(String pathPdf) {
		this.pathPdf = pathPdf;
	}

	@Column(name = "PDF")
	public byte[] getPdf() {
		return this.pdf;
	}

	public void setPdf(byte[] pdf) {
		this.pdf = pdf;
	}

}
