package com.common.hibernate.entidades.tinnova;
// Generated 12-abr-2016 16:30:08 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * M4tCalendarioId generated by hbm2java
 */
@Embeddable
public class M4tCalendarioId implements java.io.Serializable {

	private String idGrupoCalendari;
	private Date fechaFestivo;

	public M4tCalendarioId() {
	}

	public M4tCalendarioId(String idGrupoCalendari, Date fechaFestivo) {
		this.idGrupoCalendari = idGrupoCalendari;
		this.fechaFestivo = fechaFestivo;
	}

	@Column(name = "ID_GRUPO_CALENDARI", nullable = false, length = 2)
	public String getIdGrupoCalendari() {
		return this.idGrupoCalendari;
	}

	public void setIdGrupoCalendari(String idGrupoCalendari) {
		this.idGrupoCalendari = idGrupoCalendari;
	}

	@Column(name = "FECHA_FESTIVO", nullable = false, length = 23)
	public Date getFechaFestivo() {
		return this.fechaFestivo;
	}

	public void setFechaFestivo(Date fechaFestivo) {
		this.fechaFestivo = fechaFestivo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof M4tCalendarioId))
			return false;
		M4tCalendarioId castOther = (M4tCalendarioId) other;

		return ((this.getIdGrupoCalendari() == castOther.getIdGrupoCalendari())
				|| (this.getIdGrupoCalendari() != null && castOther.getIdGrupoCalendari() != null
						&& this.getIdGrupoCalendari().equals(castOther.getIdGrupoCalendari())))
				&& ((this.getFechaFestivo() == castOther.getFechaFestivo())
						|| (this.getFechaFestivo() != null && castOther.getFechaFestivo() != null
								&& this.getFechaFestivo().equals(castOther.getFechaFestivo())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdGrupoCalendari() == null ? 0 : this.getIdGrupoCalendari().hashCode());
		result = 37 * result + (getFechaFestivo() == null ? 0 : this.getFechaFestivo().hashCode());
		return result;
	}

}
