package com.common.hibernate.entidades.tinnova;
// Generated 12-abr-2016 16:30:08 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4tCalendario generated by hbm2java
 */
@Entity
@Table(name = "M4T_CALENDARIO", schema = "dbo", catalog = "EMIND")
public class M4tCalendario implements java.io.Serializable {

	private M4tCalendarioId id;
	private M4tGrupoCalendar m4tGrupoCalendar;
	private String NFestivo;
	private String idUsuario;
	private Date fecUltActualizac;
	private String coment;

	public M4tCalendario() {
	}

	public M4tCalendario(M4tCalendarioId id, M4tGrupoCalendar m4tGrupoCalendar) {
		this.id = id;
		this.m4tGrupoCalendar = m4tGrupoCalendar;
	}

	public M4tCalendario(M4tCalendarioId id, M4tGrupoCalendar m4tGrupoCalendar, String NFestivo, String idUsuario,
			Date fecUltActualizac, String coment) {
		this.id = id;
		this.m4tGrupoCalendar = m4tGrupoCalendar;
		this.NFestivo = NFestivo;
		this.idUsuario = idUsuario;
		this.fecUltActualizac = fecUltActualizac;
		this.coment = coment;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idGrupoCalendari", column = @Column(name = "ID_GRUPO_CALENDARI", nullable = false, length = 2) ),
			@AttributeOverride(name = "fechaFestivo", column = @Column(name = "FECHA_FESTIVO", nullable = false, length = 23) ) })
	public M4tCalendarioId getId() {
		return this.id;
	}

	public void setId(M4tCalendarioId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_GRUPO_CALENDARI", nullable = false, insertable = false, updatable = false)
	public M4tGrupoCalendar getM4tGrupoCalendar() {
		return this.m4tGrupoCalendar;
	}

	public void setM4tGrupoCalendar(M4tGrupoCalendar m4tGrupoCalendar) {
		this.m4tGrupoCalendar = m4tGrupoCalendar;
	}

	@Column(name = "N_FESTIVO", length = 40)
	public String getNFestivo() {
		return this.NFestivo;
	}

	public void setNFestivo(String NFestivo) {
		this.NFestivo = NFestivo;
	}

	@Column(name = "ID_USUARIO", length = 40)
	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_ULT_ACTUALIZAC", length = 23)
	public Date getFecUltActualizac() {
		return this.fecUltActualizac;
	}

	public void setFecUltActualizac(Date fecUltActualizac) {
		this.fecUltActualizac = fecUltActualizac;
	}

	@Column(name = "COMENT")
	public String getComent() {
		return this.coment;
	}

	public void setComent(String coment) {
		this.coment = coment;
	}

}
