package com.common.hibernate.entidades.tinnova;
// Generated 12-abr-2016 16:30:08 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4tCentrosTrab generated by hbm2java
 */
@Entity
@Table(name = "M4T_CENTROS_TRAB", schema = "dbo", catalog = "EMIND")
public class M4tCentrosTrab implements java.io.Serializable {

	private String idCentroTrabajo;
	private M4tGrupoCalendar m4tGrupoCalendar;
	private String NCentroTrabajo;
	private String idUsuario;
	private String coment;
	private Date fecUltActualizac;
	private String domicilio;
	private String poblacion;
	private String telefono;
	private String responsable;
	private byte idSubdivGeograf;
	private Short numCentroTrabajo;
	private Integer numTrabCentrSt;
	private String codLocalCentrSt;
	private String distritoPostal;
	private String idNacion;
	private String idMunicSepe;
	private Set<M4tHistCentTrab> m4tHistCentTrabs = new HashSet<M4tHistCentTrab>(0);

	public M4tCentrosTrab() {
	}

	public M4tCentrosTrab(String idCentroTrabajo, M4tGrupoCalendar m4tGrupoCalendar, String NCentroTrabajo,
			byte idSubdivGeograf, String idNacion) {
		this.idCentroTrabajo = idCentroTrabajo;
		this.m4tGrupoCalendar = m4tGrupoCalendar;
		this.NCentroTrabajo = NCentroTrabajo;
		this.idSubdivGeograf = idSubdivGeograf;
		this.idNacion = idNacion;
	}

	public M4tCentrosTrab(String idCentroTrabajo, M4tGrupoCalendar m4tGrupoCalendar, String NCentroTrabajo,
			String idUsuario, String coment, Date fecUltActualizac, String domicilio, String poblacion, String telefono,
			String responsable, byte idSubdivGeograf, Short numCentroTrabajo, Integer numTrabCentrSt,
			String codLocalCentrSt, String distritoPostal, String idNacion, String idMunicSepe,
			Set<M4tHistCentTrab> m4tHistCentTrabs) {
		this.idCentroTrabajo = idCentroTrabajo;
		this.m4tGrupoCalendar = m4tGrupoCalendar;
		this.NCentroTrabajo = NCentroTrabajo;
		this.idUsuario = idUsuario;
		this.coment = coment;
		this.fecUltActualizac = fecUltActualizac;
		this.domicilio = domicilio;
		this.poblacion = poblacion;
		this.telefono = telefono;
		this.responsable = responsable;
		this.idSubdivGeograf = idSubdivGeograf;
		this.numCentroTrabajo = numCentroTrabajo;
		this.numTrabCentrSt = numTrabCentrSt;
		this.codLocalCentrSt = codLocalCentrSt;
		this.distritoPostal = distritoPostal;
		this.idNacion = idNacion;
		this.idMunicSepe = idMunicSepe;
		this.m4tHistCentTrabs = m4tHistCentTrabs;
	}

	@Id

	@Column(name = "ID_CENTRO_TRABAJO", unique = true, nullable = false, length = 10)
	public String getIdCentroTrabajo() {
		return this.idCentroTrabajo;
	}

	public void setIdCentroTrabajo(String idCentroTrabajo) {
		this.idCentroTrabajo = idCentroTrabajo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_GRUPO_CALENDARI", nullable = false)
	public M4tGrupoCalendar getM4tGrupoCalendar() {
		return this.m4tGrupoCalendar;
	}

	public void setM4tGrupoCalendar(M4tGrupoCalendar m4tGrupoCalendar) {
		this.m4tGrupoCalendar = m4tGrupoCalendar;
	}

	@Column(name = "N_CENTRO_TRABAJO", nullable = false, length = 40)
	public String getNCentroTrabajo() {
		return this.NCentroTrabajo;
	}

	public void setNCentroTrabajo(String NCentroTrabajo) {
		this.NCentroTrabajo = NCentroTrabajo;
	}

	@Column(name = "ID_USUARIO", length = 40)
	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "COMENT")
	public String getComent() {
		return this.coment;
	}

	public void setComent(String coment) {
		this.coment = coment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_ULT_ACTUALIZAC", length = 23)
	public Date getFecUltActualizac() {
		return this.fecUltActualizac;
	}

	public void setFecUltActualizac(Date fecUltActualizac) {
		this.fecUltActualizac = fecUltActualizac;
	}

	@Column(name = "DOMICILIO", length = 40)
	public String getDomicilio() {
		return this.domicilio;
	}

	public void setDomicilio(String domicilio) {
		this.domicilio = domicilio;
	}

	@Column(name = "POBLACION", length = 20)
	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	@Column(name = "TELEFONO", length = 40)
	public String getTelefono() {
		return this.telefono;
	}

	public void setTelefono(String telefono) {
		this.telefono = telefono;
	}

	@Column(name = "RESPONSABLE", length = 40)
	public String getResponsable() {
		return this.responsable;
	}

	public void setResponsable(String responsable) {
		this.responsable = responsable;
	}

	@Column(name = "ID_SUBDIV_GEOGRAF", nullable = false, precision = 2, scale = 0)
	public byte getIdSubdivGeograf() {
		return this.idSubdivGeograf;
	}

	public void setIdSubdivGeograf(byte idSubdivGeograf) {
		this.idSubdivGeograf = idSubdivGeograf;
	}

	@Column(name = "NUM_CENTRO_TRABAJO", precision = 3, scale = 0)
	public Short getNumCentroTrabajo() {
		return this.numCentroTrabajo;
	}

	public void setNumCentroTrabajo(Short numCentroTrabajo) {
		this.numCentroTrabajo = numCentroTrabajo;
	}

	@Column(name = "NUM_TRAB_CENTR_ST", precision = 6, scale = 0)
	public Integer getNumTrabCentrSt() {
		return this.numTrabCentrSt;
	}

	public void setNumTrabCentrSt(Integer numTrabCentrSt) {
		this.numTrabCentrSt = numTrabCentrSt;
	}

	@Column(name = "COD_LOCAL_CENTR_ST", length = 5)
	public String getCodLocalCentrSt() {
		return this.codLocalCentrSt;
	}

	public void setCodLocalCentrSt(String codLocalCentrSt) {
		this.codLocalCentrSt = codLocalCentrSt;
	}

	@Column(name = "DISTRITO_POSTAL", length = 5)
	public String getDistritoPostal() {
		return this.distritoPostal;
	}

	public void setDistritoPostal(String distritoPostal) {
		this.distritoPostal = distritoPostal;
	}

	@Column(name = "ID_NACION", nullable = false, length = 3)
	public String getIdNacion() {
		return this.idNacion;
	}

	public void setIdNacion(String idNacion) {
		this.idNacion = idNacion;
	}

	@Column(name = "ID_MUNIC_SEPE", length = 5)
	public String getIdMunicSepe() {
		return this.idMunicSepe;
	}

	public void setIdMunicSepe(String idMunicSepe) {
		this.idMunicSepe = idMunicSepe;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "m4tCentrosTrab")
	public Set<M4tHistCentTrab> getM4tHistCentTrabs() {
		return this.m4tHistCentTrabs;
	}

	public void setM4tHistCentTrabs(Set<M4tHistCentTrab> m4tHistCentTrabs) {
		this.m4tHistCentTrabs = m4tHistCentTrabs;
	}

}
