package com.common.hibernate.entidades.tinnova;
// Generated 12-abr-2016 16:30:08 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4tDatosPago generated by hbm2java
 */
@Entity
@Table(name = "M4T_DATOS_PAGO", schema = "dbo", catalog = "EMIND")
public class M4tDatosPago implements java.io.Serializable {

	private M4tDatosPagoId id;
	private M4tFasesAlta m4tFasesAlta;
	private Date fecInicio;
	private Date fecFin;
	private String idBanco;
	private String idAgencia;
	private String numCuenta;
	private String idFormaPago;
	private String idCentroPago;
	private String idTipoBenefic;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private String idLegal;
	private String viaPublica;
	private String numVia;
	private String distritoPostal;
	private String poblacion;
	private byte idSubdivGeograf;
	private String idSiglaDomicilio;
	private String idUsuario;
	private Date fecUltActualizac;
	private String coment;
	private String idMoneda;
	private String literalReg7;
	private String digitoControlSt;
	private String codOrgJudSt;
	private String NCodOrgJudSt;
	private String codOrgJudProSt;
	private String tpProcedimientSt;
	private String idExpedienteSt;
	private String anioExpedSt;
	private String digControlSt;
	private String tpConceptoSt;
	private String descTpCptoSt;
	private String cptoOrden;
	private String idNacionIban;
	private String codigoIban;
	private String codigoBic;

	public M4tDatosPago() {
	}

	public M4tDatosPago(M4tDatosPagoId id, M4tFasesAlta m4tFasesAlta, String idBanco, String idAgencia,
			String idFormaPago, String idCentroPago, String idTipoBenefic, byte idSubdivGeograf,
			String idSiglaDomicilio) {
		this.id = id;
		this.m4tFasesAlta = m4tFasesAlta;
		this.idBanco = idBanco;
		this.idAgencia = idAgencia;
		this.idFormaPago = idFormaPago;
		this.idCentroPago = idCentroPago;
		this.idTipoBenefic = idTipoBenefic;
		this.idSubdivGeograf = idSubdivGeograf;
		this.idSiglaDomicilio = idSiglaDomicilio;
	}

	public M4tDatosPago(M4tDatosPagoId id, M4tFasesAlta m4tFasesAlta, Date fecInicio, Date fecFin, String idBanco,
			String idAgencia, String numCuenta, String idFormaPago, String idCentroPago, String idTipoBenefic,
			String nombre, String apellido1, String apellido2, String idLegal, String viaPublica, String numVia,
			String distritoPostal, String poblacion, byte idSubdivGeograf, String idSiglaDomicilio, String idUsuario,
			Date fecUltActualizac, String coment, String idMoneda, String literalReg7, String digitoControlSt,
			String codOrgJudSt, String NCodOrgJudSt, String codOrgJudProSt, String tpProcedimientSt,
			String idExpedienteSt, String anioExpedSt, String digControlSt, String tpConceptoSt, String descTpCptoSt,
			String cptoOrden, String idNacionIban, String codigoIban, String codigoBic) {
		this.id = id;
		this.m4tFasesAlta = m4tFasesAlta;
		this.fecInicio = fecInicio;
		this.fecFin = fecFin;
		this.idBanco = idBanco;
		this.idAgencia = idAgencia;
		this.numCuenta = numCuenta;
		this.idFormaPago = idFormaPago;
		this.idCentroPago = idCentroPago;
		this.idTipoBenefic = idTipoBenefic;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.idLegal = idLegal;
		this.viaPublica = viaPublica;
		this.numVia = numVia;
		this.distritoPostal = distritoPostal;
		this.poblacion = poblacion;
		this.idSubdivGeograf = idSubdivGeograf;
		this.idSiglaDomicilio = idSiglaDomicilio;
		this.idUsuario = idUsuario;
		this.fecUltActualizac = fecUltActualizac;
		this.coment = coment;
		this.idMoneda = idMoneda;
		this.literalReg7 = literalReg7;
		this.digitoControlSt = digitoControlSt;
		this.codOrgJudSt = codOrgJudSt;
		this.NCodOrgJudSt = NCodOrgJudSt;
		this.codOrgJudProSt = codOrgJudProSt;
		this.tpProcedimientSt = tpProcedimientSt;
		this.idExpedienteSt = idExpedienteSt;
		this.anioExpedSt = anioExpedSt;
		this.digControlSt = digControlSt;
		this.tpConceptoSt = tpConceptoSt;
		this.descTpCptoSt = descTpCptoSt;
		this.cptoOrden = cptoOrden;
		this.idNacionIban = idNacionIban;
		this.codigoIban = codigoIban;
		this.codigoBic = codigoBic;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idSociedad", column = @Column(name = "ID_SOCIEDAD", nullable = false, length = 2) ),
			@AttributeOverride(name = "idEmpleado", column = @Column(name = "ID_EMPLEADO", nullable = false, length = 10) ),
			@AttributeOverride(name = "fecAltaEmpleado", column = @Column(name = "FEC_ALTA_EMPLEADO", nullable = false, length = 23) ),
			@AttributeOverride(name = "idDatoPago", column = @Column(name = "ID_DATO_PAGO", nullable = false, precision = 3, scale = 0) ) })
	public M4tDatosPagoId getId() {
		return this.id;
	}

	public void setId(M4tDatosPagoId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_SOCIEDAD", referencedColumnName = "ID_SOCIEDAD", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "ID_EMPLEADO", referencedColumnName = "ID_EMPLEADO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "FEC_ALTA_EMPLEADO", referencedColumnName = "FEC_ALTA_EMPLEADO", nullable = false, insertable = false, updatable = false) })
	public M4tFasesAlta getM4tFasesAlta() {
		return this.m4tFasesAlta;
	}

	public void setM4tFasesAlta(M4tFasesAlta m4tFasesAlta) {
		this.m4tFasesAlta = m4tFasesAlta;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_INICIO", length = 23)
	public Date getFecInicio() {
		return this.fecInicio;
	}

	public void setFecInicio(Date fecInicio) {
		this.fecInicio = fecInicio;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_FIN", length = 23)
	public Date getFecFin() {
		return this.fecFin;
	}

	public void setFecFin(Date fecFin) {
		this.fecFin = fecFin;
	}

	@Column(name = "ID_BANCO", nullable = false, length = 4)
	public String getIdBanco() {
		return this.idBanco;
	}

	public void setIdBanco(String idBanco) {
		this.idBanco = idBanco;
	}

	@Column(name = "ID_AGENCIA", nullable = false, length = 4)
	public String getIdAgencia() {
		return this.idAgencia;
	}

	public void setIdAgencia(String idAgencia) {
		this.idAgencia = idAgencia;
	}

	@Column(name = "NUM_CUENTA", length = 10)
	public String getNumCuenta() {
		return this.numCuenta;
	}

	public void setNumCuenta(String numCuenta) {
		this.numCuenta = numCuenta;
	}

	@Column(name = "ID_FORMA_PAGO", nullable = false, length = 10)
	public String getIdFormaPago() {
		return this.idFormaPago;
	}

	public void setIdFormaPago(String idFormaPago) {
		this.idFormaPago = idFormaPago;
	}

	@Column(name = "ID_CENTRO_PAGO", nullable = false, length = 10)
	public String getIdCentroPago() {
		return this.idCentroPago;
	}

	public void setIdCentroPago(String idCentroPago) {
		this.idCentroPago = idCentroPago;
	}

	@Column(name = "ID_TIPO_BENEFIC", nullable = false, length = 10)
	public String getIdTipoBenefic() {
		return this.idTipoBenefic;
	}

	public void setIdTipoBenefic(String idTipoBenefic) {
		this.idTipoBenefic = idTipoBenefic;
	}

	@Column(name = "NOMBRE", length = 40)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "APELLIDO_1", length = 40)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "APELLIDO_2", length = 40)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Column(name = "ID_LEGAL", length = 10)
	public String getIdLegal() {
		return this.idLegal;
	}

	public void setIdLegal(String idLegal) {
		this.idLegal = idLegal;
	}

	@Column(name = "VIA_PUBLICA", length = 30)
	public String getViaPublica() {
		return this.viaPublica;
	}

	public void setViaPublica(String viaPublica) {
		this.viaPublica = viaPublica;
	}

	@Column(name = "NUM_VIA", length = 5)
	public String getNumVia() {
		return this.numVia;
	}

	public void setNumVia(String numVia) {
		this.numVia = numVia;
	}

	@Column(name = "DISTRITO_POSTAL", length = 5)
	public String getDistritoPostal() {
		return this.distritoPostal;
	}

	public void setDistritoPostal(String distritoPostal) {
		this.distritoPostal = distritoPostal;
	}

	@Column(name = "POBLACION", length = 25)
	public String getPoblacion() {
		return this.poblacion;
	}

	public void setPoblacion(String poblacion) {
		this.poblacion = poblacion;
	}

	@Column(name = "ID_SUBDIV_GEOGRAF", nullable = false, precision = 2, scale = 0)
	public byte getIdSubdivGeograf() {
		return this.idSubdivGeograf;
	}

	public void setIdSubdivGeograf(byte idSubdivGeograf) {
		this.idSubdivGeograf = idSubdivGeograf;
	}

	@Column(name = "ID_SIGLA_DOMICILIO", nullable = false, length = 2)
	public String getIdSiglaDomicilio() {
		return this.idSiglaDomicilio;
	}

	public void setIdSiglaDomicilio(String idSiglaDomicilio) {
		this.idSiglaDomicilio = idSiglaDomicilio;
	}

	@Column(name = "ID_USUARIO", length = 40)
	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_ULT_ACTUALIZAC", length = 23)
	public Date getFecUltActualizac() {
		return this.fecUltActualizac;
	}

	public void setFecUltActualizac(Date fecUltActualizac) {
		this.fecUltActualizac = fecUltActualizac;
	}

	@Column(name = "COMENT")
	public String getComent() {
		return this.coment;
	}

	public void setComent(String coment) {
		this.coment = coment;
	}

	@Column(name = "ID_MONEDA", length = 20)
	public String getIdMoneda() {
		return this.idMoneda;
	}

	public void setIdMoneda(String idMoneda) {
		this.idMoneda = idMoneda;
	}

	@Column(name = "LITERAL_REG_7", length = 140)
	public String getLiteralReg7() {
		return this.literalReg7;
	}

	public void setLiteralReg7(String literalReg7) {
		this.literalReg7 = literalReg7;
	}

	@Column(name = "DIGITO_CONTROL_ST", length = 2)
	public String getDigitoControlSt() {
		return this.digitoControlSt;
	}

	public void setDigitoControlSt(String digitoControlSt) {
		this.digitoControlSt = digitoControlSt;
	}

	@Column(name = "COD_ORG_JUD_ST", length = 4)
	public String getCodOrgJudSt() {
		return this.codOrgJudSt;
	}

	public void setCodOrgJudSt(String codOrgJudSt) {
		this.codOrgJudSt = codOrgJudSt;
	}

	@Column(name = "N_COD_ORG_JUD_ST", length = 44)
	public String getNCodOrgJudSt() {
		return this.NCodOrgJudSt;
	}

	public void setNCodOrgJudSt(String NCodOrgJudSt) {
		this.NCodOrgJudSt = NCodOrgJudSt;
	}

	@Column(name = "COD_ORG_JUD_PRO_ST", length = 4)
	public String getCodOrgJudProSt() {
		return this.codOrgJudProSt;
	}

	public void setCodOrgJudProSt(String codOrgJudProSt) {
		this.codOrgJudProSt = codOrgJudProSt;
	}

	@Column(name = "TP_PROCEDIMIENT_ST", length = 2)
	public String getTpProcedimientSt() {
		return this.tpProcedimientSt;
	}

	public void setTpProcedimientSt(String tpProcedimientSt) {
		this.tpProcedimientSt = tpProcedimientSt;
	}

	@Column(name = "ID_EXPEDIENTE_ST", length = 4)
	public String getIdExpedienteSt() {
		return this.idExpedienteSt;
	}

	public void setIdExpedienteSt(String idExpedienteSt) {
		this.idExpedienteSt = idExpedienteSt;
	}

	@Column(name = "ANIO_EXPED_ST", length = 2)
	public String getAnioExpedSt() {
		return this.anioExpedSt;
	}

	public void setAnioExpedSt(String anioExpedSt) {
		this.anioExpedSt = anioExpedSt;
	}

	@Column(name = "DIG_CONTROL_ST", length = 1)
	public String getDigControlSt() {
		return this.digControlSt;
	}

	public void setDigControlSt(String digControlSt) {
		this.digControlSt = digControlSt;
	}

	@Column(name = "TP_CONCEPTO_ST", length = 2)
	public String getTpConceptoSt() {
		return this.tpConceptoSt;
	}

	public void setTpConceptoSt(String tpConceptoSt) {
		this.tpConceptoSt = tpConceptoSt;
	}

	@Column(name = "DESC_TP_CPTO_ST", length = 40)
	public String getDescTpCptoSt() {
		return this.descTpCptoSt;
	}

	public void setDescTpCptoSt(String descTpCptoSt) {
		this.descTpCptoSt = descTpCptoSt;
	}

	@Column(name = "CPTO_ORDEN", length = 1)
	public String getCptoOrden() {
		return this.cptoOrden;
	}

	public void setCptoOrden(String cptoOrden) {
		this.cptoOrden = cptoOrden;
	}

	@Column(name = "ID_NACION_IBAN", length = 3)
	public String getIdNacionIban() {
		return this.idNacionIban;
	}

	public void setIdNacionIban(String idNacionIban) {
		this.idNacionIban = idNacionIban;
	}

	@Column(name = "CODIGO_IBAN", length = 24)
	public String getCodigoIban() {
		return this.codigoIban;
	}

	public void setCodigoIban(String codigoIban) {
		this.codigoIban = codigoIban;
	}

	@Column(name = "CODIGO_BIC", length = 11)
	public String getCodigoBic() {
		return this.codigoBic;
	}

	public void setCodigoBic(String codigoBic) {
		this.codigoBic = codigoBic;
	}

}
