package com.common.hibernate.entidades.tinnova;
// Generated 12-abr-2016 16:30:08 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4tEmpleados generated by hbm2java
 */
@Entity
@Table(name = "M4T_EMPLEADOS", schema = "dbo", catalog = "EMIND")
public class M4tEmpleados implements java.io.Serializable {

	private M4tEmpleadosId id;
	private String nombre;
	private String apellido1;
	private String apellido2;
	private String numPasaporte;
	private String numAfiliacionSs;
	private Date fecNacimiento;
	private String poblacNacimiento;
	private String coment;
	private Byte nivelSeguridad;
	private Date fecUltActualizac;
	private String idUsuario;
	private String idLegal;
	private String idNacion;
	private char idSexo;
	private char idEstadoCivil;
	private String idNacionalidad;
	private String idAgrupSeguridad;
	private byte idSubdivNacimien;
	private char idTipIdLegalSt;
	private String idLegalRepSt;
	private String paisEmisorSt;
	private String cancelDatPer;
	private Set<M4tDepartamentos> m4tDepartamentosesForFkEmpleadDeptos = new HashSet<M4tDepartamentos>(0);
	private Set<M4tDepartamentos> m4tDepartamentosesForFkEmplDptosResps = new HashSet<M4tDepartamentos>(0);
	private Set<M4tFasesAlta> m4tFasesAltas = new HashSet<M4tFasesAlta>(0);
	private Set<M4tInfGrafEmpl> m4tInfGrafEmpls = new HashSet<M4tInfGrafEmpl>(0);

	public M4tEmpleados() {
	}

	public M4tEmpleados(M4tEmpleadosId id, String nombre, String apellido1, String idLegal, String idNacion,
			char idSexo, char idEstadoCivil, String idNacionalidad, String idAgrupSeguridad, byte idSubdivNacimien,
			char idTipIdLegalSt, String cancelDatPer) {
		this.id = id;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.idLegal = idLegal;
		this.idNacion = idNacion;
		this.idSexo = idSexo;
		this.idEstadoCivil = idEstadoCivil;
		this.idNacionalidad = idNacionalidad;
		this.idAgrupSeguridad = idAgrupSeguridad;
		this.idSubdivNacimien = idSubdivNacimien;
		this.idTipIdLegalSt = idTipIdLegalSt;
		this.cancelDatPer = cancelDatPer;
	}

	public M4tEmpleados(M4tEmpleadosId id, String nombre, String apellido1, String apellido2, String numPasaporte,
			String numAfiliacionSs, Date fecNacimiento, String poblacNacimiento, String coment, Byte nivelSeguridad,
			Date fecUltActualizac, String idUsuario, String idLegal, String idNacion, char idSexo, char idEstadoCivil,
			String idNacionalidad, String idAgrupSeguridad, byte idSubdivNacimien, char idTipIdLegalSt,
			String idLegalRepSt, String paisEmisorSt, String cancelDatPer,
			Set<M4tDepartamentos> m4tDepartamentosesForFkEmpleadDeptos,
			Set<M4tDepartamentos> m4tDepartamentosesForFkEmplDptosResps, Set<M4tFasesAlta> m4tFasesAltas,
			Set<M4tInfGrafEmpl> m4tInfGrafEmpls) {
		this.id = id;
		this.nombre = nombre;
		this.apellido1 = apellido1;
		this.apellido2 = apellido2;
		this.numPasaporte = numPasaporte;
		this.numAfiliacionSs = numAfiliacionSs;
		this.fecNacimiento = fecNacimiento;
		this.poblacNacimiento = poblacNacimiento;
		this.coment = coment;
		this.nivelSeguridad = nivelSeguridad;
		this.fecUltActualizac = fecUltActualizac;
		this.idUsuario = idUsuario;
		this.idLegal = idLegal;
		this.idNacion = idNacion;
		this.idSexo = idSexo;
		this.idEstadoCivil = idEstadoCivil;
		this.idNacionalidad = idNacionalidad;
		this.idAgrupSeguridad = idAgrupSeguridad;
		this.idSubdivNacimien = idSubdivNacimien;
		this.idTipIdLegalSt = idTipIdLegalSt;
		this.idLegalRepSt = idLegalRepSt;
		this.paisEmisorSt = paisEmisorSt;
		this.cancelDatPer = cancelDatPer;
		this.m4tDepartamentosesForFkEmpleadDeptos = m4tDepartamentosesForFkEmpleadDeptos;
		this.m4tDepartamentosesForFkEmplDptosResps = m4tDepartamentosesForFkEmplDptosResps;
		this.m4tFasesAltas = m4tFasesAltas;
		this.m4tInfGrafEmpls = m4tInfGrafEmpls;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idSociedad", column = @Column(name = "ID_SOCIEDAD", nullable = false, length = 2) ),
			@AttributeOverride(name = "idEmpleado", column = @Column(name = "ID_EMPLEADO", nullable = false, length = 10) ) })
	public M4tEmpleadosId getId() {
		return this.id;
	}

	public void setId(M4tEmpleadosId id) {
		this.id = id;
	}

	@Column(name = "NOMBRE", nullable = false, length = 17)
	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	@Column(name = "APELLIDO_1", nullable = false, length = 20)
	public String getApellido1() {
		return this.apellido1;
	}

	public void setApellido1(String apellido1) {
		this.apellido1 = apellido1;
	}

	@Column(name = "APELLIDO_2", length = 20)
	public String getApellido2() {
		return this.apellido2;
	}

	public void setApellido2(String apellido2) {
		this.apellido2 = apellido2;
	}

	@Column(name = "NUM_PASAPORTE", length = 20)
	public String getNumPasaporte() {
		return this.numPasaporte;
	}

	public void setNumPasaporte(String numPasaporte) {
		this.numPasaporte = numPasaporte;
	}

	@Column(name = "NUM_AFILIACION_SS", length = 12)
	public String getNumAfiliacionSs() {
		return this.numAfiliacionSs;
	}

	public void setNumAfiliacionSs(String numAfiliacionSs) {
		this.numAfiliacionSs = numAfiliacionSs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_NACIMIENTO", length = 23)
	public Date getFecNacimiento() {
		return this.fecNacimiento;
	}

	public void setFecNacimiento(Date fecNacimiento) {
		this.fecNacimiento = fecNacimiento;
	}

	@Column(name = "POBLAC_NACIMIENTO", length = 25)
	public String getPoblacNacimiento() {
		return this.poblacNacimiento;
	}

	public void setPoblacNacimiento(String poblacNacimiento) {
		this.poblacNacimiento = poblacNacimiento;
	}

	@Column(name = "COMENT")
	public String getComent() {
		return this.coment;
	}

	public void setComent(String coment) {
		this.coment = coment;
	}

	@Column(name = "NIVEL_SEGURIDAD", precision = 2, scale = 0)
	public Byte getNivelSeguridad() {
		return this.nivelSeguridad;
	}

	public void setNivelSeguridad(Byte nivelSeguridad) {
		this.nivelSeguridad = nivelSeguridad;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_ULT_ACTUALIZAC", length = 23)
	public Date getFecUltActualizac() {
		return this.fecUltActualizac;
	}

	public void setFecUltActualizac(Date fecUltActualizac) {
		this.fecUltActualizac = fecUltActualizac;
	}

	@Column(name = "ID_USUARIO", length = 40)
	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "ID_LEGAL", nullable = false, length = 10)
	public String getIdLegal() {
		return this.idLegal;
	}

	public void setIdLegal(String idLegal) {
		this.idLegal = idLegal;
	}

	@Column(name = "ID_NACION", nullable = false, length = 3)
	public String getIdNacion() {
		return this.idNacion;
	}

	public void setIdNacion(String idNacion) {
		this.idNacion = idNacion;
	}

	@Column(name = "ID_SEXO", nullable = false, length = 1)
	public char getIdSexo() {
		return this.idSexo;
	}

	public void setIdSexo(char idSexo) {
		this.idSexo = idSexo;
	}

	@Column(name = "ID_ESTADO_CIVIL", nullable = false, length = 1)
	public char getIdEstadoCivil() {
		return this.idEstadoCivil;
	}

	public void setIdEstadoCivil(char idEstadoCivil) {
		this.idEstadoCivil = idEstadoCivil;
	}

	@Column(name = "ID_NACIONALIDAD", nullable = false, length = 3)
	public String getIdNacionalidad() {
		return this.idNacionalidad;
	}

	public void setIdNacionalidad(String idNacionalidad) {
		this.idNacionalidad = idNacionalidad;
	}

	@Column(name = "ID_AGRUP_SEGURIDAD", nullable = false, length = 10)
	public String getIdAgrupSeguridad() {
		return this.idAgrupSeguridad;
	}

	public void setIdAgrupSeguridad(String idAgrupSeguridad) {
		this.idAgrupSeguridad = idAgrupSeguridad;
	}

	@Column(name = "ID_SUBDIV_NACIMIEN", nullable = false, precision = 2, scale = 0)
	public byte getIdSubdivNacimien() {
		return this.idSubdivNacimien;
	}

	public void setIdSubdivNacimien(byte idSubdivNacimien) {
		this.idSubdivNacimien = idSubdivNacimien;
	}

	@Column(name = "ID_TIP_ID_LEGAL_ST", nullable = false, length = 1)
	public char getIdTipIdLegalSt() {
		return this.idTipIdLegalSt;
	}

	public void setIdTipIdLegalSt(char idTipIdLegalSt) {
		this.idTipIdLegalSt = idTipIdLegalSt;
	}

	@Column(name = "ID_LEGAL_REP_ST", length = 10)
	public String getIdLegalRepSt() {
		return this.idLegalRepSt;
	}

	public void setIdLegalRepSt(String idLegalRepSt) {
		this.idLegalRepSt = idLegalRepSt;
	}

	@Column(name = "PAIS_EMISOR_ST", length = 3)
	public String getPaisEmisorSt() {
		return this.paisEmisorSt;
	}

	public void setPaisEmisorSt(String paisEmisorSt) {
		this.paisEmisorSt = paisEmisorSt;
	}

	@Column(name = "CANCEL_DAT_PER", nullable = false, length = 1)
	public String getCancelDatPer() {
		return this.cancelDatPer;
	}

	public void setCancelDatPer(String cancelDatPer) {
		this.cancelDatPer = cancelDatPer;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "m4tEmpleadosByFkEmpleadDeptos")
	public Set<M4tDepartamentos> getM4tDepartamentosesForFkEmpleadDeptos() {
		return this.m4tDepartamentosesForFkEmpleadDeptos;
	}

	public void setM4tDepartamentosesForFkEmpleadDeptos(Set<M4tDepartamentos> m4tDepartamentosesForFkEmpleadDeptos) {
		this.m4tDepartamentosesForFkEmpleadDeptos = m4tDepartamentosesForFkEmpleadDeptos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "m4tEmpleadosByFkEmplDptosResps")
	public Set<M4tDepartamentos> getM4tDepartamentosesForFkEmplDptosResps() {
		return this.m4tDepartamentosesForFkEmplDptosResps;
	}

	public void setM4tDepartamentosesForFkEmplDptosResps(Set<M4tDepartamentos> m4tDepartamentosesForFkEmplDptosResps) {
		this.m4tDepartamentosesForFkEmplDptosResps = m4tDepartamentosesForFkEmplDptosResps;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "m4tEmpleados")
	public Set<M4tFasesAlta> getM4tFasesAltas() {
		return this.m4tFasesAltas;
	}

	public void setM4tFasesAltas(Set<M4tFasesAlta> m4tFasesAltas) {
		this.m4tFasesAltas = m4tFasesAltas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "m4tEmpleados")
	public Set<M4tInfGrafEmpl> getM4tInfGrafEmpls() {
		return this.m4tInfGrafEmpls;
	}

	public void setM4tInfGrafEmpls(Set<M4tInfGrafEmpl> m4tInfGrafEmpls) {
		this.m4tInfGrafEmpls = m4tInfGrafEmpls;
	}

}
