package com.common.hibernate.entidades.tinnova;
// Generated 12-abr-2016 16:30:08 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * M4tEmpleadosId generated by hbm2java
 */
@Embeddable
public class M4tEmpleadosId implements java.io.Serializable {

	private String idSociedad;
	private String idEmpleado;

	public M4tEmpleadosId() {
	}

	public M4tEmpleadosId(String idSociedad, String idEmpleado) {
		this.idSociedad = idSociedad;
		this.idEmpleado = idEmpleado;
	}

	@Column(name = "ID_SOCIEDAD", nullable = false, length = 2)
	public String getIdSociedad() {
		return this.idSociedad;
	}

	public void setIdSociedad(String idSociedad) {
		this.idSociedad = idSociedad;
	}

	@Column(name = "ID_EMPLEADO", nullable = false, length = 10)
	public String getIdEmpleado() {
		return this.idEmpleado;
	}

	public void setIdEmpleado(String idEmpleado) {
		this.idEmpleado = idEmpleado;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof M4tEmpleadosId))
			return false;
		M4tEmpleadosId castOther = (M4tEmpleadosId) other;

		return ((this.getIdSociedad() == castOther.getIdSociedad()) || (this.getIdSociedad() != null
				&& castOther.getIdSociedad() != null && this.getIdSociedad().equals(castOther.getIdSociedad())))
				&& ((this.getIdEmpleado() == castOther.getIdEmpleado())
						|| (this.getIdEmpleado() != null && castOther.getIdEmpleado() != null
								&& this.getIdEmpleado().equals(castOther.getIdEmpleado())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getIdSociedad() == null ? 0 : this.getIdSociedad().hashCode());
		result = 37 * result + (getIdEmpleado() == null ? 0 : this.getIdEmpleado().hashCode());
		return result;
	}

}
