package com.common.hibernate.entidades.tinnova;
// Generated 12-abr-2016 16:30:08 by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4tFasesAlta generated by hbm2java
 */
@Entity
@Table(name = "M4T_FASES_ALTA", schema = "dbo", catalog = "EMIND")
public class M4tFasesAlta implements java.io.Serializable {

	private M4tFasesAltaId id;
	private M4tEmpleados m4tEmpleados;
	private Date fecBaja;
	private Date fecAntiguedad;
	private Date fecExtras;
	private String numMatricula;
	private String numPluriempleo;
	private String numHijosIrpf;
	private char idClavePercep;
	private String comentBaja;
	private String extensionTelef;
	private String direccionMail;
	private Date fecUltActualizac;
	private String coment;
	private String idUsuario;
	private String idMotivoBaja;
	private String idEstadoNomina;
	private String idEstadoPlantill;
	private String idMotivoBajaSs;
	private Date fecRetroacSt;
	private Date fecIndRetColSt;
	private boolean desactRetIndSt;
	private boolean desactRetColSt;
	private Date fecTeorFinV;
	private String idMotBajaInem;
	private Date fecFinEfectoCe;
	private String numEre;
	private Character condDiscTrab;
	private String idCnoCe;
	private String NCnoCe;
	private String tipoJornd1;
	private String diasJornd1;
	private String fecIniJornd1;
	private String fecFinJornd1;
	private String tipoJornd2;
	private String diasJornd2;
	private String fecIniJornd2;
	private String fecFinJornd2;
	private String tipoJornd3;
	private String diasJornd3;
	private String fecIniJornd3;
	private String fecFinJornd3;
	private String tipoJornd4;
	private String diasJornd4;
	private String fecIniJornd4;
	private String fecFinJornd4;
	private String genCertificado;
	private Date fecIniBonCm;
	private Date fecFinBonCm;
	private BigDecimal porEreParc;
	private Set<M4tHistDepartam> m4tHistDepartams = new HashSet<M4tHistDepartam>(0);
	private Set<M4tHistPuestos> m4tHistPuestoses = new HashSet<M4tHistPuestos>(0);
	private Set<M4tDatosPago> m4tDatosPagos = new HashSet<M4tDatosPago>(0);
	private Set<M4tHistUnidOrg> m4tHistUnidOrgs = new HashSet<M4tHistUnidOrg>(0);
	private Set<M4tAbsentismos> m4tAbsentismoses = new HashSet<M4tAbsentismos>(0);
	private Set<M4tHistCentTrab> m4tHistCentTrabs = new HashSet<M4tHistCentTrab>(0);

	public M4tFasesAlta() {
	}

	public M4tFasesAlta(M4tFasesAltaId id, M4tEmpleados m4tEmpleados, char idClavePercep, String idMotivoBaja,
			String idEstadoNomina, String idEstadoPlantill, String idMotivoBajaSs, boolean desactRetIndSt,
			boolean desactRetColSt, String idMotBajaInem, String genCertificado) {
		this.id = id;
		this.m4tEmpleados = m4tEmpleados;
		this.idClavePercep = idClavePercep;
		this.idMotivoBaja = idMotivoBaja;
		this.idEstadoNomina = idEstadoNomina;
		this.idEstadoPlantill = idEstadoPlantill;
		this.idMotivoBajaSs = idMotivoBajaSs;
		this.desactRetIndSt = desactRetIndSt;
		this.desactRetColSt = desactRetColSt;
		this.idMotBajaInem = idMotBajaInem;
		this.genCertificado = genCertificado;
	}

	public M4tFasesAlta(M4tFasesAltaId id, M4tEmpleados m4tEmpleados, Date fecBaja, Date fecAntiguedad, Date fecExtras,
			String numMatricula, String numPluriempleo, String numHijosIrpf, char idClavePercep, String comentBaja,
			String extensionTelef, String direccionMail, Date fecUltActualizac, String coment, String idUsuario,
			String idMotivoBaja, String idEstadoNomina, String idEstadoPlantill, String idMotivoBajaSs,
			Date fecRetroacSt, Date fecIndRetColSt, boolean desactRetIndSt, boolean desactRetColSt, Date fecTeorFinV,
			String idMotBajaInem, Date fecFinEfectoCe, String numEre, Character condDiscTrab, String idCnoCe,
			String NCnoCe, String tipoJornd1, String diasJornd1, String fecIniJornd1, String fecFinJornd1,
			String tipoJornd2, String diasJornd2, String fecIniJornd2, String fecFinJornd2, String tipoJornd3,
			String diasJornd3, String fecIniJornd3, String fecFinJornd3, String tipoJornd4, String diasJornd4,
			String fecIniJornd4, String fecFinJornd4, String genCertificado, Date fecIniBonCm, Date fecFinBonCm,
			BigDecimal porEreParc, Set<M4tHistDepartam> m4tHistDepartams, Set<M4tHistPuestos> m4tHistPuestoses,
			Set<M4tDatosPago> m4tDatosPagos, Set<M4tHistUnidOrg> m4tHistUnidOrgs, Set<M4tAbsentismos> m4tAbsentismoses,
			Set<M4tHistCentTrab> m4tHistCentTrabs) {
		this.id = id;
		this.m4tEmpleados = m4tEmpleados;
		this.fecBaja = fecBaja;
		this.fecAntiguedad = fecAntiguedad;
		this.fecExtras = fecExtras;
		this.numMatricula = numMatricula;
		this.numPluriempleo = numPluriempleo;
		this.numHijosIrpf = numHijosIrpf;
		this.idClavePercep = idClavePercep;
		this.comentBaja = comentBaja;
		this.extensionTelef = extensionTelef;
		this.direccionMail = direccionMail;
		this.fecUltActualizac = fecUltActualizac;
		this.coment = coment;
		this.idUsuario = idUsuario;
		this.idMotivoBaja = idMotivoBaja;
		this.idEstadoNomina = idEstadoNomina;
		this.idEstadoPlantill = idEstadoPlantill;
		this.idMotivoBajaSs = idMotivoBajaSs;
		this.fecRetroacSt = fecRetroacSt;
		this.fecIndRetColSt = fecIndRetColSt;
		this.desactRetIndSt = desactRetIndSt;
		this.desactRetColSt = desactRetColSt;
		this.fecTeorFinV = fecTeorFinV;
		this.idMotBajaInem = idMotBajaInem;
		this.fecFinEfectoCe = fecFinEfectoCe;
		this.numEre = numEre;
		this.condDiscTrab = condDiscTrab;
		this.idCnoCe = idCnoCe;
		this.NCnoCe = NCnoCe;
		this.tipoJornd1 = tipoJornd1;
		this.diasJornd1 = diasJornd1;
		this.fecIniJornd1 = fecIniJornd1;
		this.fecFinJornd1 = fecFinJornd1;
		this.tipoJornd2 = tipoJornd2;
		this.diasJornd2 = diasJornd2;
		this.fecIniJornd2 = fecIniJornd2;
		this.fecFinJornd2 = fecFinJornd2;
		this.tipoJornd3 = tipoJornd3;
		this.diasJornd3 = diasJornd3;
		this.fecIniJornd3 = fecIniJornd3;
		this.fecFinJornd3 = fecFinJornd3;
		this.tipoJornd4 = tipoJornd4;
		this.diasJornd4 = diasJornd4;
		this.fecIniJornd4 = fecIniJornd4;
		this.fecFinJornd4 = fecFinJornd4;
		this.genCertificado = genCertificado;
		this.fecIniBonCm = fecIniBonCm;
		this.fecFinBonCm = fecFinBonCm;
		this.porEreParc = porEreParc;
		this.m4tHistDepartams = m4tHistDepartams;
		this.m4tHistPuestoses = m4tHistPuestoses;
		this.m4tDatosPagos = m4tDatosPagos;
		this.m4tHistUnidOrgs = m4tHistUnidOrgs;
		this.m4tAbsentismoses = m4tAbsentismoses;
		this.m4tHistCentTrabs = m4tHistCentTrabs;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idSociedad", column = @Column(name = "ID_SOCIEDAD", nullable = false, length = 2) ),
			@AttributeOverride(name = "idEmpleado", column = @Column(name = "ID_EMPLEADO", nullable = false, length = 10) ),
			@AttributeOverride(name = "fecAltaEmpleado", column = @Column(name = "FEC_ALTA_EMPLEADO", nullable = false, length = 23) ) })
	public M4tFasesAltaId getId() {
		return this.id;
	}

	public void setId(M4tFasesAltaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_SOCIEDAD", referencedColumnName = "ID_SOCIEDAD", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "ID_EMPLEADO", referencedColumnName = "ID_EMPLEADO", nullable = false, insertable = false, updatable = false) })
	public M4tEmpleados getM4tEmpleados() {
		return this.m4tEmpleados;
	}

	public void setM4tEmpleados(M4tEmpleados m4tEmpleados) {
		this.m4tEmpleados = m4tEmpleados;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_BAJA", length = 23)
	public Date getFecBaja() {
		return this.fecBaja;
	}

	public void setFecBaja(Date fecBaja) {
		this.fecBaja = fecBaja;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_ANTIGUEDAD", length = 23)
	public Date getFecAntiguedad() {
		return this.fecAntiguedad;
	}

	public void setFecAntiguedad(Date fecAntiguedad) {
		this.fecAntiguedad = fecAntiguedad;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_EXTRAS", length = 23)
	public Date getFecExtras() {
		return this.fecExtras;
	}

	public void setFecExtras(Date fecExtras) {
		this.fecExtras = fecExtras;
	}

	@Column(name = "NUM_MATRICULA", length = 5)
	public String getNumMatricula() {
		return this.numMatricula;
	}

	public void setNumMatricula(String numMatricula) {
		this.numMatricula = numMatricula;
	}

	@Column(name = "NUM_PLURIEMPLEO", length = 15)
	public String getNumPluriempleo() {
		return this.numPluriempleo;
	}

	public void setNumPluriempleo(String numPluriempleo) {
		this.numPluriempleo = numPluriempleo;
	}

	@Column(name = "NUM_HIJOS_IRPF", length = 2)
	public String getNumHijosIrpf() {
		return this.numHijosIrpf;
	}

	public void setNumHijosIrpf(String numHijosIrpf) {
		this.numHijosIrpf = numHijosIrpf;
	}

	@Column(name = "ID_CLAVE_PERCEP", nullable = false, length = 1)
	public char getIdClavePercep() {
		return this.idClavePercep;
	}

	public void setIdClavePercep(char idClavePercep) {
		this.idClavePercep = idClavePercep;
	}

	@Column(name = "COMENT_BAJA")
	public String getComentBaja() {
		return this.comentBaja;
	}

	public void setComentBaja(String comentBaja) {
		this.comentBaja = comentBaja;
	}

	@Column(name = "EXTENSION_TELEF", length = 10)
	public String getExtensionTelef() {
		return this.extensionTelef;
	}

	public void setExtensionTelef(String extensionTelef) {
		this.extensionTelef = extensionTelef;
	}

	@Column(name = "DIRECCION_MAIL", length = 50)
	public String getDireccionMail() {
		return this.direccionMail;
	}

	public void setDireccionMail(String direccionMail) {
		this.direccionMail = direccionMail;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_ULT_ACTUALIZAC", length = 23)
	public Date getFecUltActualizac() {
		return this.fecUltActualizac;
	}

	public void setFecUltActualizac(Date fecUltActualizac) {
		this.fecUltActualizac = fecUltActualizac;
	}

	@Column(name = "COMENT")
	public String getComent() {
		return this.coment;
	}

	public void setComent(String coment) {
		this.coment = coment;
	}

	@Column(name = "ID_USUARIO", length = 40)
	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "ID_MOTIVO_BAJA", nullable = false, length = 4)
	public String getIdMotivoBaja() {
		return this.idMotivoBaja;
	}

	public void setIdMotivoBaja(String idMotivoBaja) {
		this.idMotivoBaja = idMotivoBaja;
	}

	@Column(name = "ID_ESTADO_NOMINA", nullable = false, length = 10)
	public String getIdEstadoNomina() {
		return this.idEstadoNomina;
	}

	public void setIdEstadoNomina(String idEstadoNomina) {
		this.idEstadoNomina = idEstadoNomina;
	}

	@Column(name = "ID_ESTADO_PLANTILL", nullable = false, length = 4)
	public String getIdEstadoPlantill() {
		return this.idEstadoPlantill;
	}

	public void setIdEstadoPlantill(String idEstadoPlantill) {
		this.idEstadoPlantill = idEstadoPlantill;
	}

	@Column(name = "ID_MOTIVO_BAJA_SS", nullable = false, length = 2)
	public String getIdMotivoBajaSs() {
		return this.idMotivoBajaSs;
	}

	public void setIdMotivoBajaSs(String idMotivoBajaSs) {
		this.idMotivoBajaSs = idMotivoBajaSs;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_RETROAC_ST", length = 23)
	public Date getFecRetroacSt() {
		return this.fecRetroacSt;
	}

	public void setFecRetroacSt(Date fecRetroacSt) {
		this.fecRetroacSt = fecRetroacSt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_IND_RET_COL_ST", length = 23)
	public Date getFecIndRetColSt() {
		return this.fecIndRetColSt;
	}

	public void setFecIndRetColSt(Date fecIndRetColSt) {
		this.fecIndRetColSt = fecIndRetColSt;
	}

	@Column(name = "DESACT_RET_IND_ST", nullable = false, precision = 1, scale = 0)
	public boolean isDesactRetIndSt() {
		return this.desactRetIndSt;
	}

	public void setDesactRetIndSt(boolean desactRetIndSt) {
		this.desactRetIndSt = desactRetIndSt;
	}

	@Column(name = "DESACT_RET_COL_ST", nullable = false, precision = 1, scale = 0)
	public boolean isDesactRetColSt() {
		return this.desactRetColSt;
	}

	public void setDesactRetColSt(boolean desactRetColSt) {
		this.desactRetColSt = desactRetColSt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_TEOR_FIN_V", length = 23)
	public Date getFecTeorFinV() {
		return this.fecTeorFinV;
	}

	public void setFecTeorFinV(Date fecTeorFinV) {
		this.fecTeorFinV = fecTeorFinV;
	}

	@Column(name = "ID_MOT_BAJA_INEM", nullable = false, length = 2)
	public String getIdMotBajaInem() {
		return this.idMotBajaInem;
	}

	public void setIdMotBajaInem(String idMotBajaInem) {
		this.idMotBajaInem = idMotBajaInem;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_FIN_EFECTO_CE", length = 23)
	public Date getFecFinEfectoCe() {
		return this.fecFinEfectoCe;
	}

	public void setFecFinEfectoCe(Date fecFinEfectoCe) {
		this.fecFinEfectoCe = fecFinEfectoCe;
	}

	@Column(name = "NUM_ERE", length = 12)
	public String getNumEre() {
		return this.numEre;
	}

	public void setNumEre(String numEre) {
		this.numEre = numEre;
	}

	@Column(name = "COND_DISC_TRAB", length = 1)
	public Character getCondDiscTrab() {
		return this.condDiscTrab;
	}

	public void setCondDiscTrab(Character condDiscTrab) {
		this.condDiscTrab = condDiscTrab;
	}

	@Column(name = "ID_CNO_CE", length = 10)
	public String getIdCnoCe() {
		return this.idCnoCe;
	}

	public void setIdCnoCe(String idCnoCe) {
		this.idCnoCe = idCnoCe;
	}

	@Column(name = "N_CNO_CE", length = 200)
	public String getNCnoCe() {
		return this.NCnoCe;
	}

	public void setNCnoCe(String NCnoCe) {
		this.NCnoCe = NCnoCe;
	}

	@Column(name = "TIPO_JORND_1", length = 4)
	public String getTipoJornd1() {
		return this.tipoJornd1;
	}

	public void setTipoJornd1(String tipoJornd1) {
		this.tipoJornd1 = tipoJornd1;
	}

	@Column(name = "DIAS_JORND_1", length = 5)
	public String getDiasJornd1() {
		return this.diasJornd1;
	}

	public void setDiasJornd1(String diasJornd1) {
		this.diasJornd1 = diasJornd1;
	}

	@Column(name = "FEC_INI_JORND_1", length = 10)
	public String getFecIniJornd1() {
		return this.fecIniJornd1;
	}

	public void setFecIniJornd1(String fecIniJornd1) {
		this.fecIniJornd1 = fecIniJornd1;
	}

	@Column(name = "FEC_FIN_JORND_1", length = 10)
	public String getFecFinJornd1() {
		return this.fecFinJornd1;
	}

	public void setFecFinJornd1(String fecFinJornd1) {
		this.fecFinJornd1 = fecFinJornd1;
	}

	@Column(name = "TIPO_JORND_2", length = 4)
	public String getTipoJornd2() {
		return this.tipoJornd2;
	}

	public void setTipoJornd2(String tipoJornd2) {
		this.tipoJornd2 = tipoJornd2;
	}

	@Column(name = "DIAS_JORND_2", length = 5)
	public String getDiasJornd2() {
		return this.diasJornd2;
	}

	public void setDiasJornd2(String diasJornd2) {
		this.diasJornd2 = diasJornd2;
	}

	@Column(name = "FEC_INI_JORND_2", length = 10)
	public String getFecIniJornd2() {
		return this.fecIniJornd2;
	}

	public void setFecIniJornd2(String fecIniJornd2) {
		this.fecIniJornd2 = fecIniJornd2;
	}

	@Column(name = "FEC_FIN_JORND_2", length = 10)
	public String getFecFinJornd2() {
		return this.fecFinJornd2;
	}

	public void setFecFinJornd2(String fecFinJornd2) {
		this.fecFinJornd2 = fecFinJornd2;
	}

	@Column(name = "TIPO_JORND_3", length = 4)
	public String getTipoJornd3() {
		return this.tipoJornd3;
	}

	public void setTipoJornd3(String tipoJornd3) {
		this.tipoJornd3 = tipoJornd3;
	}

	@Column(name = "DIAS_JORND_3", length = 5)
	public String getDiasJornd3() {
		return this.diasJornd3;
	}

	public void setDiasJornd3(String diasJornd3) {
		this.diasJornd3 = diasJornd3;
	}

	@Column(name = "FEC_INI_JORND_3", length = 10)
	public String getFecIniJornd3() {
		return this.fecIniJornd3;
	}

	public void setFecIniJornd3(String fecIniJornd3) {
		this.fecIniJornd3 = fecIniJornd3;
	}

	@Column(name = "FEC_FIN_JORND_3", length = 10)
	public String getFecFinJornd3() {
		return this.fecFinJornd3;
	}

	public void setFecFinJornd3(String fecFinJornd3) {
		this.fecFinJornd3 = fecFinJornd3;
	}

	@Column(name = "TIPO_JORND_4", length = 4)
	public String getTipoJornd4() {
		return this.tipoJornd4;
	}

	public void setTipoJornd4(String tipoJornd4) {
		this.tipoJornd4 = tipoJornd4;
	}

	@Column(name = "DIAS_JORND_4", length = 5)
	public String getDiasJornd4() {
		return this.diasJornd4;
	}

	public void setDiasJornd4(String diasJornd4) {
		this.diasJornd4 = diasJornd4;
	}

	@Column(name = "FEC_INI_JORND_4", length = 10)
	public String getFecIniJornd4() {
		return this.fecIniJornd4;
	}

	public void setFecIniJornd4(String fecIniJornd4) {
		this.fecIniJornd4 = fecIniJornd4;
	}

	@Column(name = "FEC_FIN_JORND_4", length = 10)
	public String getFecFinJornd4() {
		return this.fecFinJornd4;
	}

	public void setFecFinJornd4(String fecFinJornd4) {
		this.fecFinJornd4 = fecFinJornd4;
	}

	@Column(name = "GEN_CERTIFICADO", nullable = false, length = 1)
	public String getGenCertificado() {
		return this.genCertificado;
	}

	public void setGenCertificado(String genCertificado) {
		this.genCertificado = genCertificado;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_INI_BON_CM", length = 23)
	public Date getFecIniBonCm() {
		return this.fecIniBonCm;
	}

	public void setFecIniBonCm(Date fecIniBonCm) {
		this.fecIniBonCm = fecIniBonCm;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_FIN_BON_CM", length = 23)
	public Date getFecFinBonCm() {
		return this.fecFinBonCm;
	}

	public void setFecFinBonCm(Date fecFinBonCm) {
		this.fecFinBonCm = fecFinBonCm;
	}

	@Column(name = "POR_ERE_PARC", precision = 14, scale = 4)
	public BigDecimal getPorEreParc() {
		return this.porEreParc;
	}

	public void setPorEreParc(BigDecimal porEreParc) {
		this.porEreParc = porEreParc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "m4tFasesAlta")
	public Set<M4tHistDepartam> getM4tHistDepartams() {
		return this.m4tHistDepartams;
	}

	public void setM4tHistDepartams(Set<M4tHistDepartam> m4tHistDepartams) {
		this.m4tHistDepartams = m4tHistDepartams;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "m4tFasesAlta")
	public Set<M4tHistPuestos> getM4tHistPuestoses() {
		return this.m4tHistPuestoses;
	}

	public void setM4tHistPuestoses(Set<M4tHistPuestos> m4tHistPuestoses) {
		this.m4tHistPuestoses = m4tHistPuestoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "m4tFasesAlta")
	public Set<M4tDatosPago> getM4tDatosPagos() {
		return this.m4tDatosPagos;
	}

	public void setM4tDatosPagos(Set<M4tDatosPago> m4tDatosPagos) {
		this.m4tDatosPagos = m4tDatosPagos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "m4tFasesAlta")
	public Set<M4tHistUnidOrg> getM4tHistUnidOrgs() {
		return this.m4tHistUnidOrgs;
	}

	public void setM4tHistUnidOrgs(Set<M4tHistUnidOrg> m4tHistUnidOrgs) {
		this.m4tHistUnidOrgs = m4tHistUnidOrgs;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "m4tFasesAlta")
	public Set<M4tAbsentismos> getM4tAbsentismoses() {
		return this.m4tAbsentismoses;
	}

	public void setM4tAbsentismoses(Set<M4tAbsentismos> m4tAbsentismoses) {
		this.m4tAbsentismoses = m4tAbsentismoses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "m4tFasesAlta")
	public Set<M4tHistCentTrab> getM4tHistCentTrabs() {
		return this.m4tHistCentTrabs;
	}

	public void setM4tHistCentTrabs(Set<M4tHistCentTrab> m4tHistCentTrabs) {
		this.m4tHistCentTrabs = m4tHistCentTrabs;
	}

}
