package com.common.hibernate.entidades.tinnova;
// Generated 12-abr-2016 16:30:08 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4tHistDepartam generated by hbm2java
 */
@Entity
@Table(name = "M4T_HIST_DEPARTAM", schema = "dbo", catalog = "EMIND")
public class M4tHistDepartam implements java.io.Serializable {

	private M4tHistDepartamId id;
	private M4tFasesAlta m4tFasesAlta;
	private M4tDepartamentos m4tDepartamentos;
	private Date fecFin;
	private String coment;
	private Date fecUltActualizac;
	private String idUsuario;
	private String idMotivoCambio;

	public M4tHistDepartam() {
	}

	public M4tHistDepartam(M4tHistDepartamId id, M4tFasesAlta m4tFasesAlta, M4tDepartamentos m4tDepartamentos,
			String idMotivoCambio) {
		this.id = id;
		this.m4tFasesAlta = m4tFasesAlta;
		this.m4tDepartamentos = m4tDepartamentos;
		this.idMotivoCambio = idMotivoCambio;
	}

	public M4tHistDepartam(M4tHistDepartamId id, M4tFasesAlta m4tFasesAlta, M4tDepartamentos m4tDepartamentos,
			Date fecFin, String coment, Date fecUltActualizac, String idUsuario, String idMotivoCambio) {
		this.id = id;
		this.m4tFasesAlta = m4tFasesAlta;
		this.m4tDepartamentos = m4tDepartamentos;
		this.fecFin = fecFin;
		this.coment = coment;
		this.fecUltActualizac = fecUltActualizac;
		this.idUsuario = idUsuario;
		this.idMotivoCambio = idMotivoCambio;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idSociedad", column = @Column(name = "ID_SOCIEDAD", nullable = false, length = 2) ),
			@AttributeOverride(name = "idEmpleado", column = @Column(name = "ID_EMPLEADO", nullable = false, length = 10) ),
			@AttributeOverride(name = "fecAltaEmpleado", column = @Column(name = "FEC_ALTA_EMPLEADO", nullable = false, length = 23) ),
			@AttributeOverride(name = "fecInicio", column = @Column(name = "FEC_INICIO", nullable = false, length = 23) ) })
	public M4tHistDepartamId getId() {
		return this.id;
	}

	public void setId(M4tHistDepartamId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_SOCIEDAD", referencedColumnName = "ID_SOCIEDAD", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "ID_EMPLEADO", referencedColumnName = "ID_EMPLEADO", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "FEC_ALTA_EMPLEADO", referencedColumnName = "FEC_ALTA_EMPLEADO", nullable = false, insertable = false, updatable = false) })
	public M4tFasesAlta getM4tFasesAlta() {
		return this.m4tFasesAlta;
	}

	public void setM4tFasesAlta(M4tFasesAlta m4tFasesAlta) {
		this.m4tFasesAlta = m4tFasesAlta;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_SOCIEDAD", referencedColumnName = "ID_SOCIEDAD", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "ID_DEPARTAMENTO", referencedColumnName = "ID_DEPARTAMENTO", nullable = false, insertable = false, updatable = false) })
	public M4tDepartamentos getM4tDepartamentos() {
		return this.m4tDepartamentos;
	}

	public void setM4tDepartamentos(M4tDepartamentos m4tDepartamentos) {
		this.m4tDepartamentos = m4tDepartamentos;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_FIN", length = 23)
	public Date getFecFin() {
		return this.fecFin;
	}

	public void setFecFin(Date fecFin) {
		this.fecFin = fecFin;
	}

	@Column(name = "COMENT")
	public String getComent() {
		return this.coment;
	}

	public void setComent(String coment) {
		this.coment = coment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_ULT_ACTUALIZAC", length = 23)
	public Date getFecUltActualizac() {
		return this.fecUltActualizac;
	}

	public void setFecUltActualizac(Date fecUltActualizac) {
		this.fecUltActualizac = fecUltActualizac;
	}

	@Column(name = "ID_USUARIO", length = 40)
	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "ID_MOTIVO_CAMBIO", nullable = false, length = 2)
	public String getIdMotivoCambio() {
		return this.idMotivoCambio;
	}

	public void setIdMotivoCambio(String idMotivoCambio) {
		this.idMotivoCambio = idMotivoCambio;
	}

}
