package com.common.hibernate.entidades.tinnova;
// Generated 12-abr-2016 16:30:08 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * M4tInfGrafEmpl generated by hbm2java
 */
@Entity
@Table(name = "M4T_INF_GRAF_EMPL", schema = "dbo", catalog = "EMIND")
public class M4tInfGrafEmpl implements java.io.Serializable {

	private M4tInfGrafEmplId id;
	private M4tEmpleados m4tEmpleados;
	private String NFichero;
	private String NDirectorio;
	private String coment;
	private Date fecUltActualizac;
	private String idUsuario;
	private String infOrdinal;
	private String idTipInfGrafica;

	public M4tInfGrafEmpl() {
	}

	public M4tInfGrafEmpl(M4tInfGrafEmplId id, M4tEmpleados m4tEmpleados, String idTipInfGrafica) {
		this.id = id;
		this.m4tEmpleados = m4tEmpleados;
		this.idTipInfGrafica = idTipInfGrafica;
	}

	public M4tInfGrafEmpl(M4tInfGrafEmplId id, M4tEmpleados m4tEmpleados, String NFichero, String NDirectorio,
			String coment, Date fecUltActualizac, String idUsuario, String infOrdinal, String idTipInfGrafica) {
		this.id = id;
		this.m4tEmpleados = m4tEmpleados;
		this.NFichero = NFichero;
		this.NDirectorio = NDirectorio;
		this.coment = coment;
		this.fecUltActualizac = fecUltActualizac;
		this.idUsuario = idUsuario;
		this.infOrdinal = infOrdinal;
		this.idTipInfGrafica = idTipInfGrafica;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idSociedad", column = @Column(name = "ID_SOCIEDAD", nullable = false, length = 2) ),
			@AttributeOverride(name = "idEmpleado", column = @Column(name = "ID_EMPLEADO", nullable = false, length = 10) ),
			@AttributeOverride(name = "idOrdinal", column = @Column(name = "ID_ORDINAL", nullable = false, precision = 6, scale = 0) ) })
	public M4tInfGrafEmplId getId() {
		return this.id;
	}

	public void setId(M4tInfGrafEmplId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_SOCIEDAD", referencedColumnName = "ID_SOCIEDAD", nullable = false, insertable = false, updatable = false),
			@JoinColumn(name = "ID_EMPLEADO", referencedColumnName = "ID_EMPLEADO", nullable = false, insertable = false, updatable = false) })
	public M4tEmpleados getM4tEmpleados() {
		return this.m4tEmpleados;
	}

	public void setM4tEmpleados(M4tEmpleados m4tEmpleados) {
		this.m4tEmpleados = m4tEmpleados;
	}

	@Column(name = "N_FICHERO")
	public String getNFichero() {
		return this.NFichero;
	}

	public void setNFichero(String NFichero) {
		this.NFichero = NFichero;
	}

	@Column(name = "N_DIRECTORIO")
	public String getNDirectorio() {
		return this.NDirectorio;
	}

	public void setNDirectorio(String NDirectorio) {
		this.NDirectorio = NDirectorio;
	}

	@Column(name = "COMENT")
	public String getComent() {
		return this.coment;
	}

	public void setComent(String coment) {
		this.coment = coment;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "FEC_ULT_ACTUALIZAC", length = 23)
	public Date getFecUltActualizac() {
		return this.fecUltActualizac;
	}

	public void setFecUltActualizac(Date fecUltActualizac) {
		this.fecUltActualizac = fecUltActualizac;
	}

	@Column(name = "ID_USUARIO", length = 40)
	public String getIdUsuario() {
		return this.idUsuario;
	}

	public void setIdUsuario(String idUsuario) {
		this.idUsuario = idUsuario;
	}

	@Column(name = "INF_ORDINAL", length = 50)
	public String getInfOrdinal() {
		return this.infOrdinal;
	}

	public void setInfOrdinal(String infOrdinal) {
		this.infOrdinal = infOrdinal;
	}

	@Column(name = "ID_TIP_INF_GRAFICA", nullable = false, length = 10)
	public String getIdTipInfGrafica() {
		return this.idTipInfGrafica;
	}

	public void setIdTipInfGrafica(String idTipInfGrafica) {
		this.idTipInfGrafica = idTipInfGrafica;
	}

}
